// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/alert-dialog/alert-dialog.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createAlertDialog } from "../controllers/alert-dialog";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LAlertDialogSize = "sm" | "md";

/** Allowed `tone` values (manifest variant group "tone", attr `data-variant` on panel). */
export type LAlertDialogTone = "default" | "destructive";

export interface LAlertDialogProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Cancel"). */
  cancelText?: string;
  /** Template text/attr substitution (default: "Confirm"). */
  confirmText?: string;
  /** Template text/attr substitution (default: ""). */
  description?: string;
  /** Template text/attr substitution (default: ""). */
  title?: string;
  /** Toggles the template's bare data attribute. */
  confirmRequired?: boolean;
  /** `data-size` on panel; omitted when unset (manifest default: "sm"). */
  size?: LAlertDialogSize;
  /** `data-variant` on panel; omitted when unset (manifest default: "destructive"). */
  tone?: LAlertDialogTone;
}

/** `alert-dialog` — Interruptive confirmation dialog (role=alertdialog) for destructive or irreversible actions Emits: `@cancel`, `@confirm` (payload: `(detail, event)`). Exposes: `open()`, `close()`, `toggle()`. */
export const LAlertDialog = defineFaqirRecipe<LAlertDialogProps>({
  name: "alert-dialog",
  create: createAlertDialog,
  methods: ["open", "close", "toggle"],
  events: ["cancel", "confirm"],
  stringProps: [{ prop: "cancelText", default: "Cancel" }, { prop: "confirmText", default: "Confirm" }, { prop: "description", default: "" }, { prop: "title", default: "" }],
  boolProps: ["confirmRequired"],
  variantProps: [
    { prop: "size", values: ["sm", "md"] },
    { prop: "tone", values: ["default", "destructive"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["alert-dialog"]],["data-state",["closed"]],["id",[{"p":"id"}]],["data-confirm-required",{"b":"confirmRequired"}]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]]],"children":[],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["alertdialog"]],["aria-modal",["true"]],["aria-labelledby",[{"p":"id"},"-title"]],["aria-describedby",[{"p":"id"},"-desc"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"h2","attrs":[["id",[{"p":"id"},"-title"]],["data-part",["title"]]],"children":[{"p":"title"}],"slot":"title"}],"slot":"header"},{"tag":"div","attrs":[["data-part",["body"]]],"children":[{"tag":"p","attrs":[["id",[{"p":"id"},"-desc"]],["data-part",["description"]]],"children":[{"p":"description"}],"slot":"description"}],"slot":"body"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[{"tag":"button","attrs":[["data-ui",["button"]],["data-part",["cancel"]],["data-variant",["outline"]]],"children":[{"p":"cancelText"}],"slot":"cancel"},{"tag":"button","attrs":[["data-ui",["button"]],["data-part",["confirm"]],["data-variant",["destructive"]]],"children":[{"p":"confirmText"}],"slot":"confirm"}],"slot":"footer"}],"slot":"panel","dyn":[["tone","data-variant"],["size","data-size"]]}]} as unknown as RecipeNode,
});

export default LAlertDialog;
