// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/calendar/calendar.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createCalendar } from "../controllers/calendar";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LCalendarSize = "sm" | "md" | "lg";

export interface LCalendarProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LCalendarSize;
}

/** `calendar` — Standalone month-grid calendar with roving-tabindex keyboard navigation, min/max/disabled dates, and single or range selection — extracted from date-picker so availability grids and range pickers can use it directly Emits: `@calendar-change` (payload: `(detail, event)`). Exposes: `getValue()`, `setValue()`, `clear()`, `navigate()`, `selectDate()`, `focusDate()`, `setMin()`, `setMax()`, `setDisabledDates()`. */
export const LCalendar = defineFaqirRecipe<LCalendarProps>({
  name: "calendar",
  create: createCalendar,
  methods: ["getValue", "setValue", "clear", "navigate", "selectDate", "focusDate", "setMin", "setMax", "setDisabledDates"],
  events: ["calendar-change"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["calendar"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"button","attrs":[["data-part",["nav-prev"]],["type",["button"]],["aria-label",["Previous month"]]],"children":["‹"],"slot":"nav-prev"},{"tag":"span","attrs":[["data-part",["month-label"]]],"children":[],"slot":"month-label"},{"tag":"button","attrs":[["data-part",["nav-next"]],["type",["button"]],["aria-label",["Next month"]]],"children":["›"],"slot":"nav-next"}],"slot":"header"},{"tag":"table","attrs":[["data-part",["grid"]],["role",["grid"]],["aria-label",["Calendar"]]],"children":[{"tag":"thead","attrs":[],"children":[{"tag":"tr","attrs":[],"children":[{"tag":"th","attrs":[],"children":["Su"]},{"tag":"th","attrs":[],"children":["Mo"]},{"tag":"th","attrs":[],"children":["Tu"]},{"tag":"th","attrs":[],"children":["We"]},{"tag":"th","attrs":[],"children":["Th"]},{"tag":"th","attrs":[],"children":["Fr"]},{"tag":"th","attrs":[],"children":["Sa"]}]}]},{"tag":"tbody","attrs":[["data-part",["grid-body"]]],"children":[],"slot":"grid-body"}],"slot":"grid"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LCalendar;
