// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/combobox/combobox.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createCombobox } from "../controllers/combobox";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LComboboxSize = "sm" | "md" | "lg";

export interface LComboboxProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LComboboxSize;
}

/** `combobox` — Autocomplete input with filtered dropdown list for type-ahead search Exposes: `open()`, `close()`, `filter()`, `selectOption()`, `getValue()`, `setValue()`. */
export const LCombobox = defineFaqirRecipe<LComboboxProps>({
  name: "combobox",
  create: createCombobox,
  methods: ["open", "close", "filter", "selectOption", "getValue", "setValue"],
  events: [],
  stringProps: [{ prop: "placeholder", default: "" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["combobox"]],["data-state",["closed"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-autocomplete",["list"]],["aria-controls",[{"p":"id"},"-listbox"]],["placeholder",[{"p":"placeholder"}]]],"children":[],"slot":"input"},{"tag":"ul","attrs":[["data-part",["listbox"]],["role",["listbox"]],["id",[{"p":"id"},"-listbox"]],["hidden",true]],"children":[{"tag":"li","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]]],"children":[]},{"tag":"li","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]]],"children":[]},{"tag":"li","attrs":[["data-part",["empty"]],["hidden",true]],"children":["No results found"],"slot":"empty"}],"slot":"listbox"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LCombobox;
