// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/command-palette/command-palette.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createCommandPalette } from "../controllers/command-palette";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LCommandPaletteSize = "sm" | "md" | "lg";

export interface LCommandPaletteProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on panel; omitted when unset (manifest default: "md"). */
  size?: LCommandPaletteSize;
}

/** `command-palette` — Cmd+K style modal command interface with search and keyboard navigation Exposes: `open()`, `close()`, `filter()`, `selectItem()`, `registerCommand()`. */
export const LCommandPalette = defineFaqirRecipe<LCommandPaletteProps>({
  name: "command-palette",
  create: createCommandPalette,
  methods: ["open", "close", "filter", "selectItem", "registerCommand"],
  events: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["command-palette"]],["data-state",["closed"]]],"children":[{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["dialog"]],["aria-modal",["true"]],["aria-label",["Command palette"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["search-wrapper"]]],"children":[{"tag":"input","attrs":[["data-part",["search"]],["type",["text"]],["role",["combobox"]],["aria-expanded",["true"]],["aria-autocomplete",["list"]],["aria-controls",[{"p":"id"},"-list"]],["placeholder",["Type a command or search..."]]],"children":[],"slot":"search"}]},{"tag":"div","attrs":[["data-part",["list"]],["role",["listbox"]],["id",[{"p":"id"},"-list"]]],"children":[{"tag":"div","attrs":[["data-part",["group"]]],"children":[{"tag":"div","attrs":[["data-part",["group-label"]]],"children":[]},{"tag":"div","attrs":[["data-part",["item"]],["role",["option"]],["aria-selected",["false"]]],"children":[{"tag":"span","attrs":[["data-part",["item-label"]]],"children":[]},{"tag":"kbd","attrs":[["data-part",["kbd"]]],"children":[],"slot":"kbd"}],"slot":"item"}],"slot":"group"},{"tag":"div","attrs":[["data-part",["empty"]],["hidden",true]],"children":["No commands found"],"slot":"empty"}],"slot":"list"}],"slot":"panel","dyn":[["size","data-size"]]}]} as unknown as RecipeNode,
});

export default LCommandPalette;
