// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/context-menu/context-menu.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createContextMenu } from "../controllers/context-menu";

export interface LContextMenuProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
}

/** `context-menu` — Context menu opened at the pointer or from the keyboard with complete menu navigation Exposes: `open()`, `close()`. */
export const LContextMenu = defineFaqirRecipe<LContextMenuProps>({
  name: "context-menu",
  create: createContextMenu,
  methods: ["open", "close"],
  events: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["context-menu"]],["data-state",["closed"]]],"children":[{"tag":"div","attrs":[["data-part",["target"]],["role",["button"]],["tabindex",["0"]],["aria-haspopup",["menu"]],["aria-expanded",["false"]],["aria-controls",[{"p":"id"},"-menu"]]],"children":[],"slot":"target"},{"tag":"div","attrs":[["data-part",["menu"]],["id",[{"p":"id"},"-menu"]],["role",["menu"]],["aria-label",["Context actions"]],["hidden",true]],"children":[{"tag":"button","attrs":[["data-part",["item"]],["type",["button"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]},{"tag":"button","attrs":[["data-part",["item"]],["type",["button"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]},{"tag":"hr","attrs":[["data-part",["separator"]],["role",["separator"]],["aria-orientation",["horizontal"]]],"children":[],"slot":"separator"},{"tag":"button","attrs":[["data-part",["item"]],["type",["button"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]}],"slot":"menu"}]} as unknown as RecipeNode,
});

export default LContextMenu;
