// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/date-picker/date-picker.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createDatePicker } from "../controllers/date-picker";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LDatePickerSize = "sm" | "md" | "lg";

export interface LDatePickerProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LDatePickerSize;
}

/** `date-picker` — Date input with calendar dropdown for date selection — the month grid is the nested `calendar` recipe Emits: `@calendar-change`, `@date-change` (payload: `(detail, event)`). Exposes: `open()`, `close()`, `getValue()`, `setValue()`, `navigate()`, `selectDate()`. */
export const LDatePicker = defineFaqirRecipe<LDatePickerProps>({
  name: "date-picker",
  create: createDatePicker,
  methods: ["open", "close", "getValue", "setValue", "navigate", "selectDate"],
  events: ["calendar-change", "date-change"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["date-picker"]],["data-state",["closed"]]],"children":[{"tag":"div","attrs":[["data-part",["trigger"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["placeholder",["Select a date"]],["readonly",true],["aria-haspopup",["dialog"]],["aria-expanded",["false"]],["aria-label",["Choose date"]]],"children":[],"slot":"input"},{"tag":"span","attrs":[["data-part",["icon"]],["aria-hidden",["true"]]],"children":["📅"],"slot":"icon"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["calendar"]],["role",["dialog"]],["aria-label",["Date picker"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-ui",["calendar"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"button","attrs":[["data-part",["nav-prev"]],["type",["button"]],["aria-label",["Previous month"]]],"children":["‹"]},{"tag":"span","attrs":[["data-part",["month-label"]]],"children":[]},{"tag":"button","attrs":[["data-part",["nav-next"]],["type",["button"]],["aria-label",["Next month"]]],"children":["›"]}]},{"tag":"table","attrs":[["data-part",["grid"]],["role",["grid"]],["aria-label",["Calendar"]]],"children":[{"tag":"thead","attrs":[],"children":[{"tag":"tr","attrs":[],"children":[{"tag":"th","attrs":[],"children":["Su"]},{"tag":"th","attrs":[],"children":["Mo"]},{"tag":"th","attrs":[],"children":["Tu"]},{"tag":"th","attrs":[],"children":["We"]},{"tag":"th","attrs":[],"children":["Th"]},{"tag":"th","attrs":[],"children":["Fr"]},{"tag":"th","attrs":[],"children":["Sa"]}]}]},{"tag":"tbody","attrs":[["data-part",["grid-body"]]],"children":[]}]}]}],"slot":"calendar"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LDatePicker;
