// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/dialog/dialog.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createDialog } from "../controllers/dialog";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LDialogSize = "sm" | "md" | "lg" | "full";

/** Allowed `tone` values (manifest variant group "tone", attr `data-variant` on panel). */
export type LDialogTone = "default" | "danger";

export interface LDialogProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  title?: string;
  /** Template text/attr substitution (default: "Open"). */
  triggerText?: string;
  /** `data-size` on panel; omitted when unset (manifest default: "md"). */
  size?: LDialogSize;
  /** `data-variant` on panel; omitted when unset (manifest default: "default"). */
  tone?: LDialogTone;
}

/** `dialog` — Modal dialog with focus trap, escape-to-close, and overlay backdrop Emits: `@cancel`, `@confirm` (payload: `(detail, event)`). Exposes: `open()`, `close()`, `toggle()`. */
export const LDialog = defineFaqirRecipe<LDialogProps>({
  name: "dialog",
  create: createDialog,
  methods: ["open", "close", "toggle"],
  events: ["cancel", "confirm"],
  stringProps: [{ prop: "title", default: "" }, { prop: "triggerText", default: "Open" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg", "full"] },
    { prop: "tone", values: ["default", "danger"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["dialog"]],["data-state",["closed"]],["id",[{"p":"id"}]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["dialog"]],["aria-modal",["true"]],["aria-labelledby",[{"p":"id"},"-title"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"h2","attrs":[["id",[{"p":"id"},"-title"]],["data-part",["title"]]],"children":[{"p":"title"}],"slot":"title"},{"tag":"button","attrs":[["data-part",["close"]],["aria-label",["Close dialog"]]],"children":["✕"],"slot":"close"}],"slot":"header"},{"tag":"div","attrs":[["data-part",["body"]]],"children":[],"slot":"body"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[],"slot":"footer"}],"slot":"panel","dyn":[["size","data-size"],["tone","data-variant"]]}]} as unknown as RecipeNode,
});

export default LDialog;
