// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/dropdown/dropdown.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createDropdown } from "../controllers/dropdown";

/** Allowed `align` values (manifest variant group "align", attr `data-variant` on menu). */
export type LDropdownAlign = "start" | "end";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LDropdownSize = "sm" | "md" | "lg";

export interface LDropdownProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Menu"). */
  triggerText?: string;
  /** `data-variant` on menu; omitted when unset (manifest default: "start"). */
  align?: LDropdownAlign;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LDropdownSize;
}

/** `dropdown` — Dropdown menu with keyboard navigation and click-outside-to-close Exposes: `open()`, `close()`, `toggle()`. */
export const LDropdown = defineFaqirRecipe<LDropdownProps>({
  name: "dropdown",
  create: createDropdown,
  methods: ["open", "close", "toggle"],
  events: [],
  stringProps: [{ prop: "triggerText", default: "Menu" }],
  boolProps: [],
  variantProps: [
    { prop: "align", values: ["start", "end"] },
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["dropdown"]],["data-state",["closed"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["aria-haspopup",["true"]],["aria-expanded",["false"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["menu"]],["role",["menu"]],["hidden",true]],"children":[{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]},{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]},{"tag":"hr","attrs":[["data-part",["separator"]]],"children":[],"slot":"separator"},{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]}],"slot":"menu","dyn":[["align","data-variant"]]}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LDropdown;
