// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/menubar/menubar.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createMenubar } from "../controllers/menubar";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LMenubarSize = "sm" | "md" | "lg";

export interface LMenubarProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Application menu"). */
  label?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LMenubarSize;
}

/** `menubar` — Horizontal application menubar with roving focus and keyboard-operated submenus Exposes: `open()`, `close()`. */
export const LMenubar = defineFaqirRecipe<LMenubarProps>({
  name: "menubar",
  create: createMenubar,
  methods: ["open", "close"],
  events: [],
  stringProps: [{ prop: "label", default: "Application menu" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["menubar"]],["data-state",["closed"]],["role",["menubar"]],["aria-label",[{"p":"label"}]]],"children":[{"tag":"div","attrs":[["data-part",["group"]],["role",["none"]]],"children":[{"tag":"button","attrs":[["type",["button"]],["data-part",["trigger"]],["id",[{"p":"id"},"-file"]],["role",["menuitem"]],["tabindex",["0"]],["aria-haspopup",["menu"]],["aria-expanded",["false"]],["aria-controls",[{"p":"id"},"-file-menu"]]],"children":[]},{"tag":"div","attrs":[["data-part",["submenu"]],["id",[{"p":"id"},"-file-menu"]],["role",["menu"]],["aria-labelledby",[{"p":"id"},"-file"]],["hidden",true]],"children":[{"tag":"button","attrs":[["type",["button"]],["data-part",["item"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]},{"tag":"button","attrs":[["type",["button"]],["data-part",["item"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]},{"tag":"hr","attrs":[["data-part",["separator"]],["role",["separator"]]],"children":[],"slot":"separator"},{"tag":"button","attrs":[["type",["button"]],["data-part",["item"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]}]}]},{"tag":"div","attrs":[["data-part",["group"]],["role",["none"]]],"children":[{"tag":"button","attrs":[["type",["button"]],["data-part",["trigger"]],["id",[{"p":"id"},"-edit"]],["role",["menuitem"]],["tabindex",["-1"]],["aria-haspopup",["menu"]],["aria-expanded",["false"]],["aria-controls",[{"p":"id"},"-edit-menu"]]],"children":[]},{"tag":"div","attrs":[["data-part",["submenu"]],["id",[{"p":"id"},"-edit-menu"]],["role",["menu"]],["aria-labelledby",[{"p":"id"},"-edit"]],["hidden",true]],"children":[{"tag":"button","attrs":[["type",["button"]],["data-part",["item"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]},{"tag":"button","attrs":[["type",["button"]],["data-part",["item"]],["role",["menuitem"]],["tabindex",["-1"]]],"children":[]}]}]}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LMenubar;
