// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/select-custom/select-custom.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createSelectCustom } from "../controllers/select-custom";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LSelectCustomSize = "sm" | "md" | "lg";

export interface LSelectCustomProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
  /** Template text/attr substitution (default: ""). */
  value?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LSelectCustomSize;
}

/** `select-custom` — Custom styled select dropdown with search filtering and keyboard navigation Exposes: `open()`, `close()`, `toggle()`, `select()`, `getValue()`. */
export const LSelectCustom = defineFaqirRecipe<LSelectCustomProps>({
  name: "select-custom",
  create: createSelectCustom,
  methods: ["open", "close", "toggle", "select", "getValue"],
  events: [],
  stringProps: [{ prop: "placeholder", default: "" }, { prop: "value", default: "" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["select-custom"]],["data-state",["closed"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-haspopup",["listbox"]],["aria-controls",[{"p":"id"},"-listbox"]]],"children":[{"tag":"span","attrs":[["data-part",["value"]],["data-placeholder",true]],"children":[{"p":"placeholder"}],"slot":"value"},{"tag":"span","attrs":[["data-part",["chevron"]],["aria-hidden",["true"]]],"children":["▾"]}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["listbox"]],["role",["listbox"]],["id",[{"p":"id"},"-listbox"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]],["data-value",[{"p":"value"}]]],"children":[]},{"tag":"div","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]],["data-value",[{"p":"value"}]]],"children":[]}],"slot":"listbox"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
});

export default LSelectCustom;
