// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/sidebar/sidebar.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createSidebar } from "../controllers/sidebar";

export interface LSidebarProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
}

/** `sidebar` — Collapsible application sidebar with three modes — expanded, rail (icons only), and a mobile off-canvas drawer — switched responsively and toggled from the keyboard Exposes: `toggle()`, `expand()`, `collapse()`, `open()`, `close()`, `isMobile()`, `getState()`. */
export const LSidebar = defineFaqirRecipe<LSidebarProps>({
  name: "sidebar",
  create: createSidebar,
  methods: ["toggle", "expand", "collapse", "open", "close", "isMobile", "getState"],
  events: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["sidebar"]],["data-state",["expanded"]],["id",[{"p":"id"}]]],"children":[{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"aside","attrs":[["data-part",["panel"]],["aria-label",["Primary navigation"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"a","attrs":[["data-part",["brand"]],["href",["#"]]],"children":[{"tag":"span","attrs":[["data-part",["brand-icon"]],["aria-hidden",["true"]]],"children":[],"slot":"brand-icon"},{"tag":"span","attrs":[["data-part",["brand-label"]]],"children":[],"slot":"brand-label"}],"slot":"brand"},{"tag":"button","attrs":[["data-part",["trigger"]],["aria-label",["Toggle sidebar"]],["aria-expanded",["true"]],["aria-controls",[{"p":"id"}]]],"children":[],"slot":"trigger"}],"slot":"header"},{"tag":"nav","attrs":[["data-part",["nav"]],["aria-label",["Main"]]],"children":[{"tag":"a","attrs":[["data-part",["item"]],["href",["#"]],["aria-current",["page"]]],"children":[{"tag":"span","attrs":[["data-part",["icon"]],["aria-hidden",["true"]]],"children":[],"slot":"icon"},{"tag":"span","attrs":[["data-part",["label"]]],"children":[],"slot":"label"}],"slot":"item"}],"slot":"nav"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[],"slot":"footer"}],"slot":"panel"}]} as unknown as RecipeNode,
});

export default LSidebar;
