// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/slider/slider.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createSlider } from "../controllers/slider";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LSliderSize = "sm" | "md" | "lg";

/** Allowed `type` values (manifest variant group "type", attr `data-variant` on root). */
export type LSliderType = "single" | "range";

export interface LSliderProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  value?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LSliderSize;
  /** `data-variant` on root; omitted when unset (manifest default: "single"). */
  type?: LSliderType;
}

/** `slider` — Draggable range input with single-thumb and two-thumb (range) modes, full keyboard control, and screen-reader-correct ARIA Emits: `@change` (payload: `(detail, event)`). Exposes: `setValue()`, `getValue()`, `getValues()`, `setFormatter()`. */
export const LSlider = defineFaqirRecipe<LSliderProps>({
  name: "slider",
  create: createSlider,
  methods: ["setValue", "getValue", "getValues", "setFormatter"],
  events: ["change"],
  stringProps: [{ prop: "value", default: "" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
    { prop: "type", values: ["single", "range"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["slider"]],["data-variant",["single"]],["data-min",["0"]],["data-max",["100"]],["data-step",["1"]],["data-value",[{"p":"value"}]],["style",["--slider-start: 0%; --slider-end: ",{"p":"value"},"%"]]],"children":[{"tag":"div","attrs":[["data-part",["track"]]],"children":[{"tag":"div","attrs":[["data-part",["range"]]],"children":[],"slot":"range"},{"tag":"div","attrs":[["data-part",["thumb"]],["role",["slider"]],["tabindex",["0"]],["aria-valuemin",["0"]],["aria-valuemax",["100"]],["aria-valuenow",[{"p":"value"}]],["style",["--pos: ",{"p":"value"},"%"]]],"children":[],"slot":"thumb"}],"slot":"track"},{"tag":"output","attrs":[["data-part",["output"]]],"children":[{"p":"value"}],"slot":"output"}],"dyn":[["type","data-variant"],["size","data-size"]]} as unknown as RecipeNode,
});

export default LSlider;
