// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/tag-input/tag-input.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createTagInput } from "../controllers/tag-input";

export interface LTagInputProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
}

/** `tag-input` — Multi-value input composing the chip primitive and combobox listbox behaviour — type + Enter to add tags, Backspace to remove the last, dismiss buttons per tag, optional filtered suggestions, and a configurable duplicates policy Exposes: `getValue()`, `setValue()`, `addTag()`, `removeTag()`, `clear()`. */
export const LTagInput = defineFaqirRecipe<LTagInputProps>({
  name: "tag-input",
  create: createTagInput,
  methods: ["getValue", "setValue", "addTag", "removeTag", "clear"],
  events: [],
  stringProps: [{ prop: "placeholder", default: "" }],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["tag-input"]],["data-state",["closed"]]],"children":[{"tag":"span","attrs":[["data-part",["taglist"]],["role",["group"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-autocomplete",["list"]],["placeholder",[{"p":"placeholder"}]]],"children":[],"slot":"input"}],"slot":"taglist"},{"tag":"input","attrs":[["data-part",["value"]],["type",["hidden"]]],"children":[],"slot":"value"}]} as unknown as RecipeNode,
});

export default LTagInput;
