// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/toast/toast.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createToastContainer } from "../controllers/toast";

/** Allowed `position` values (manifest variant group "position", attr `data-variant` on container). */
export type LToastPosition = "top-right" | "top-left" | "bottom-right" | "bottom-left";

export interface LToastProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-variant` on container; omitted when unset (manifest default: "top-right"). */
  position?: LToastPosition;
}

/** `toast` — Auto-dismissing notification messages with stack management Exposes: `add()`, `dismiss()`, `dismissAll()`. */
export const LToast = defineFaqirRecipe<LToastProps>({
  name: "toast",
  create: createToastContainer,
  methods: ["add", "dismiss", "dismissAll"],
  events: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "position", values: ["top-right", "top-left", "bottom-right", "bottom-left"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["toast"]],["data-part",["container"]],["role",["region"]],["aria-label",["Notifications"]],["id",[{"p":"id"}]]],"children":[],"dyn":[["position","data-variant"]]} as unknown as RecipeNode,
});

export default LToast;
