// AUTO-GENERATED by `faqir bindings vue` from registry/recipes/tooltip/tooltip.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirRecipe } from "../recipe-runtime";
import type { RecipeNode } from "../recipe-runtime";
import { createTooltip } from "../controllers/tooltip";

/** Allowed `position` values (manifest variant group "position", attr `data-variant` on root). */
export type LTooltipPosition = "top" | "bottom" | "left" | "right";

export interface LTooltipProps {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-variant` on root; omitted when unset (manifest default: "top"). */
  position?: LTooltipPosition;
}

/** `tooltip` — Informational popup shown on hover or focus of trigger element Exposes: `show()`, `hide()`. */
export const LTooltip = defineFaqirRecipe<LTooltipProps>({
  name: "tooltip",
  create: createTooltip,
  methods: ["show", "hide"],
  events: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "position", values: ["top", "bottom", "left", "right"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["tooltip"]],["data-state",["hidden"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["aria-describedby",[{"p":"id"},"-content"]]],"children":[],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["content"]],["id",[{"p":"id"},"-content"]],["role",["tooltip"]],["hidden",true]],"children":[],"slot":"content"}],"dyn":[["position","data-variant"]]} as unknown as RecipeNode,
});

export default LTooltip;
