// Codegen tests for `faqir bindings react` (task 0.7-01): per-primitive
// snapshots, the manifest-drift guard (regenerating must produce zero diff
// against the committed files — §11.1 made literal), the structural guarantees
// (every primitive generated, typed props for every variant group, zero
// hand-written per-component code, runtime within its line budget), and the
// RSC-safety invariant: no `"use client"` directive anywhere in the package.

import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadPrimitiveIRs, pascalCase } from "../../../src/bindings/ir";
import { emitReactPackage } from "../../../src/bindings/react";
import { getRegistryPath } from "../../../src/utils/fs";
import { listRegistryComponents } from "../../../src/utils/components";

const PKG = join(import.meta.dir, "..");
const SRC = join(PKG, "src");

const irs = await loadPrimitiveIRs(getRegistryPath());
const generated = emitReactPackage(irs);

describe("bindings react codegen", () => {
  it("generates a component for every registry primitive", () => {
    const primitives = listRegistryComponents(getRegistryPath(), "primitives").sort();
    expect(irs.map((ir) => ir.name)).toEqual(primitives);
    for (const name of primitives) {
      expect(generated.has(`components/${name}.ts`)).toBe(true);
    }
    expect(generated.has("index.ts")).toBe(true);
  });

  it("types every root variant group as a literal union", () => {
    for (const ir of irs) {
      const source = generated.get(`components/${ir.name}.ts`)!;
      for (const v of ir.variants) {
        const typeName = `${ir.componentName}${pascalCase(v.prop)}`;
        expect(source).toContain(`export type ${typeName} = `);
        for (const value of v.values) expect(source).toContain(JSON.stringify(value));
      }
      expect(source).toContain(`export interface ${ir.componentName}Props`);
    }
  });

  it("named slots become ReactNode props (button icon, card parts)", () => {
    const button = generated.get("components/button.ts")!;
    expect(button).toContain("icon?: ReactNode;");
    const card = generated.get("components/card.ts")!;
    for (const part of ["header", "title", "description", "body", "footer"]) {
      expect(card).toContain(`${part}?: ReactNode;`);
    }
  });

  it("declared prop names are Omitted from the intrinsic element base (size/title collisions)", () => {
    // `size` is `number` on <input>; `title` is `string` on every element —
    // both would break `extends` without the Omit.
    const input = generated.get("components/input.ts")!;
    expect(input).toContain(`Omit<ComponentPropsWithoutRef<"input">,`);
    expect(input).toMatch(/Omit<ComponentPropsWithoutRef<"input">, [^>]*"size"[^>]*>/);
    const card = generated.get("components/card.ts")!;
    expect(card).toMatch(/Omit<ComponentPropsWithoutRef<"div">, [^>]*"title"[^>]*>/);
  });

  it("void roots have no slots and no default slot (input, separator)", () => {
    for (const name of ["input", "separator", "radio", "checkbox"]) {
      const ir = irs.find((i) => i.name === name)!;
      expect(ir.voidRoot).toBe(true);
      expect(ir.slots).toEqual([]);
      expect(ir.defaultSlot).toBe(false);
      // No ReactNode import when there are no slots.
      expect(generated.get(`components/${name}.ts`)!).not.toContain("ReactNode");
    }
  });

  it("snapshot per primitive", () => {
    for (const ir of irs) {
      expect(generated.get(`components/${ir.name}.ts`)!).toMatchSnapshot(`react:${ir.name}`);
    }
    expect(generated.get("index.ts")!).toMatchSnapshot("react:index");
  });
});

describe("manifest-drift guard (§11.1: bindings can't drift)", () => {
  it("committed files byte-match a fresh regeneration", () => {
    for (const [rel, content] of generated) {
      const path = join(SRC, rel);
      expect(existsSync(path)).toBe(true);
      expect(readFileSync(path, "utf8")).toBe(content);
    }
  });

  it("no stale generated files linger", () => {
    const committed = readdirSync(join(SRC, "components")).filter((f) => f.endsWith(".ts"));
    const fresh = [...generated.keys()]
      .filter((k) => k.startsWith("components/"))
      .map((k) => k.slice("components/".length));
    expect(committed.sort()).toEqual(fresh.sort());
  });
});

describe("zero hand-written per-component code", () => {
  it("every component module is generated and spec-only", () => {
    for (const file of readdirSync(join(SRC, "components"))) {
      const source = readFileSync(join(SRC, "components", file), "utf8");
      expect(source.startsWith("// AUTO-GENERATED by `faqir bindings react`")).toBe(true);
      // Spec-only: no render logic in generated modules — the runtime owns it.
      expect(source).not.toContain("createElement");
      expect(source).not.toContain("forwardRef");
    }
  });

  it("runtime.ts is the only hand-written module and stays within budget", () => {
    const files = readdirSync(SRC).filter((f) => f.endsWith(".ts") && f !== "index.ts");
    const handWritten = files.filter((f) => {
      if (f === "runtime.ts") return true;
      return !readFileSync(join(SRC, f), "utf8").startsWith("// AUTO-GENERATED");
    });
    expect(handWritten).toEqual(["runtime.ts"]);
    const total = readFileSync(join(SRC, "runtime.ts"), "utf8").trimEnd().split("\n").length;
    console.log(`runtime.ts: ${total} lines`);
    expect(total).toBeLessThanOrEqual(150);
  });
});

// A `"use client"` / `'use client'` module directive at a statement line (not
// inside a comment, where the runtime legitimately mentions it).
const USE_CLIENT_DIRECTIVE = /^\s*["']use client["'];?\s*$/m;

describe("RSC safety (task 0.7-01)", () => {
  it('no primitive module or the runtime carries a "use client" directive', () => {
    for (const [, content] of generated) {
      expect(content).not.toMatch(USE_CLIENT_DIRECTIVE);
    }
    expect(readFileSync(join(SRC, "runtime.ts"), "utf8")).not.toMatch(USE_CLIENT_DIRECTIVE);
  });

  it("the runtime imports no client-only React APIs (no hooks, no react-dom)", () => {
    const runtime = readFileSync(join(SRC, "runtime.ts"), "utf8");
    expect(runtime).not.toContain("react-dom");
    expect(runtime).not.toMatch(/\buse[A-Z]\w*/); // useState/useEffect/useRef/…
  });
});
