// Vue 3 emitter for the bindings codegen (task 0.6-12, FAQIR-NEXT §11.2).
// Consumes the target-agnostic ComponentIR and emits one TypeScript module per
// primitive: literal-union prop types + a spec passed to the hand-written
// `defineFaqirPrimitive` runtime. Output is deterministic (sorted components,
// manifest-order members) so regeneration is byte-stable — the drift guard
// depends on that.

import { pascalCase, type ComponentIR, type IRState } from "./ir";

const HEADER = (ir: ComponentIR) =>
  `// AUTO-GENERATED by \`faqir bindings vue\` from ${ir.manifestPath}.
// Do not edit — regenerate with \`faqir bindings vue\`.
`;

function quote(s: string): string {
  return JSON.stringify(s);
}

function union(values: string[]): string {
  return values.map(quote).join(" | ");
}

function stateDoc(s: IRState): string {
  if (s.kind === "aria") return `Reflected as \`${s.attr}="true"|"false"\`.`;
  if (s.kind === "presence") return `Sets the \`${s.attr}\` attribute.`;
  return `Sets \`${s.attr}="${s.value}"\`.`;
}

/** Emit the TypeScript module for one primitive. */
export function emitVueComponent(ir: ComponentIR): string {
  const lines: string[] = [HEADER(ir)];
  lines.push(`import { defineFaqirPrimitive } from "../runtime";`);
  lines.push("");

  // Literal union type per variant group.
  for (const v of ir.variants) {
    const typeName = `${ir.componentName}${pascalCase(v.prop)}`;
    lines.push(
      `/** Allowed \`${v.prop}\` values (manifest variant group ${quote(v.group)}, attr \`${v.attr}\`). */`
    );
    lines.push(`export type ${typeName} = ${union(v.values)};`);
    lines.push("");
  }

  // Props interface.
  lines.push(`export interface ${ir.componentName}Props {`);
  for (const v of ir.variants) {
    const typeName = `${ir.componentName}${pascalCase(v.prop)}`;
    lines.push(`  /** \`${v.attr}\`; omitted when unset (manifest default: ${quote(v.default)}). */`);
    lines.push(`  ${v.prop}?: ${typeName};`);
  }
  for (const s of ir.states) {
    lines.push(`  /** ${stateDoc(s)} */`);
    lines.push(`  ${s.prop}?: boolean;`);
  }
  lines.push(`}`);
  lines.push("");

  // Component definition — pure spec, interpreted by the runtime.
  lines.push(`/** \`${ir.name}\` — ${ir.description.replace(/\*\//g, "*\\/")} */`);
  lines.push(`export const ${ir.componentName} = defineFaqirPrimitive<${ir.componentName}Props>({`);
  lines.push(`  name: ${quote(ir.name)},`);
  lines.push(`  tag: ${quote(ir.tag)},`);

  if (ir.variants.length === 0) {
    lines.push(`  variants: [],`);
  } else {
    lines.push(`  variants: [`);
    for (const v of ir.variants) {
      lines.push(`    { prop: ${quote(v.prop)}, attr: ${quote(v.attr)}, values: [${v.values.map(quote).join(", ")}] },`);
    }
    lines.push(`  ],`);
  }

  if (ir.states.length === 0) {
    lines.push(`  states: [],`);
  } else {
    lines.push(`  states: [`);
    for (const s of ir.states) {
      const value = s.value === null ? "null" : quote(s.value);
      lines.push(`    { prop: ${quote(s.prop)}, attr: ${quote(s.attr)}, value: ${value}, kind: ${quote(s.kind)} },`);
    }
    lines.push(`  ],`);
  }

  if (ir.slots.length === 0) {
    lines.push(`  slots: [],`);
  } else {
    lines.push(`  slots: [`);
    for (const sl of ir.slots) {
      lines.push(`    { name: ${quote(sl.name)}, tag: ${quote(sl.tag)}, required: ${sl.required}, isVoid: ${sl.isVoid} },`);
    }
    lines.push(`  ],`);
  }

  lines.push(`  defaultSlot: ${ir.defaultSlot},`);
  lines.push(`});`);
  lines.push("");
  lines.push(`export default ${ir.componentName};`);
  lines.push("");
  return lines.join("\n");
}

/** Emit the package barrel re-exporting every component, its types, and the runtime. */
export function emitVueIndex(irs: ComponentIR[]): string {
  const lines: string[] = [
    `// AUTO-GENERATED by \`faqir bindings vue\`. Do not edit — regenerate instead.`,
    ``,
    `export { defineFaqirPrimitive } from "./runtime";`,
    `export type { FaqirPrimitiveSpec, SpecVariant, SpecState, SpecSlot } from "./runtime";`,
    ``,
  ];
  for (const ir of irs) {
    const types = [
      `${ir.componentName}Props`,
      ...ir.variants.map((v) => `${ir.componentName}${pascalCase(v.prop)}`),
    ];
    lines.push(`export { ${ir.componentName} } from "./components/${ir.name}";`);
    lines.push(`export type { ${types.join(", ")} } from "./components/${ir.name}";`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Full generation manifest: relative path → file content. */
export function emitVuePackage(irs: ComponentIR[]): Map<string, string> {
  const files = new Map<string, string>();
  for (const ir of irs) {
    files.set(`components/${ir.name}.ts`, emitVueComponent(ir));
  }
  files.set(`index.ts`, emitVueIndex(irs));
  return files;
}
