// ═══════════════════════════════════════════════════════════════════════════
// Document running headers and footers  [task 0.6-07 · §7.4]
// ═══════════════════════════════════════════════════════════════════════════
//
// The document pattern exposes explicit doc-header/doc-footer parts. In print,
// each part uses a declaration-stack fallback: position:fixed repeats in
// browser print engines, while paged-media engines that understand running()
// promote the same element into @page margin boxes through element(). Page
// numbers are generated by the predefined CSS page/pages counters. A dedicated
// fixture forces three pages without adding a duplicate visual-matrix entry.

import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { auditHtmlSource } from "../../src/audit/checker";
import { validateManifest, type Manifest } from "../../src/manifest";
import { extractComponents } from "../../src/parser/html-parser";
import { loadRegistryManifestMap } from "../../src/utils/components";

const ROOT = join(import.meta.dir, "../..");
const REGISTRY = join(ROOT, "registry");
const DOCUMENT_DIR = join(REGISTRY, "patterns/document");
const CSS = readFileSync(join(DOCUMENT_DIR, "document.css"), "utf8");
const HTML = readFileSync(join(DOCUMENT_DIR, "document.html"), "utf8");
const PRINT_HTML = readFileSync(join(DOCUMENT_DIR, "document-print.html"), "utf8");
const TOKENS = readFileSync(join(REGISTRY, "tokens/document.css"), "utf8");

type RendererSupport = {
  mechanism: string;
  notes: string;
};

type DocumentManifest = Manifest & {
  renderer_support: Record<string, RendererSupport>;
  files: Manifest["files"] & { print_reference: string };
};

const MANIFEST = JSON.parse(
  readFileSync(join(DOCUMENT_DIR, "document.manifest.json"), "utf8"),
) as DocumentManifest;

function printPartRule(part: "doc-header" | "doc-footer"): string {
  const print = CSS.slice(CSS.indexOf("\n@media print {") + 1);
  const match = new RegExp(
    `\\[data-ui="document"\\]\\s*>\\s*\\[data-part="${part}"\\][^{]*\\{([^}]*)\\}`,
  ).exec(print);
  expect(match, `missing print rule for ${part}`).not.toBeNull();
  return match![1];
}

describe("document · running header/footer CSS contract", () => {
  it("defines tokenized fixed-fallback geometry for both running parts", () => {
    expect(TOKENS).toContain("--doc-running-header-height:");
    expect(TOKENS).toContain("--doc-running-footer-height:");
    expect(TOKENS).toContain("--doc-running-gap:");
    expect(CSS).toContain("var(--doc-running-header-height)");
    expect(CSS).toContain("var(--doc-running-footer-height)");
  });

  it("keeps position:fixed before running() so unsupported engines retain the fallback", () => {
    const print = CSS.slice(CSS.indexOf("\n@media print {") + 1);
    expect(print).toContain('[data-part="doc-header"]');
    expect(print).toContain('[data-part="doc-footer"]');

    const header = printPartRule("doc-header");
    expect(header.indexOf("position: fixed;")).toBeGreaterThanOrEqual(0);
    expect(header.indexOf("position: running(faqir-doc-header);")).toBeGreaterThan(
      header.indexOf("position: fixed;"),
    );

    const footer = printPartRule("doc-footer");
    expect(footer.indexOf("position: fixed;")).toBeGreaterThanOrEqual(0);
    expect(footer.indexOf("position: running(faqir-doc-footer);")).toBeGreaterThan(
      footer.indexOf("position: fixed;"),
    );
  });

  it("scopes the fixed fallback spacing to print engines without running()", () => {
    const print = CSS.slice(CSS.indexOf("\n@media print {") + 1);
    expect(print).toContain(
      "@supports not (position: running(faqir-doc-header))",
    );
    expect(print).toContain("padding-block-start: calc(var(--doc-running-header-height)");
    expect(print).toContain("padding-block-end: calc(var(--doc-running-footer-height)");
    expect(print).toContain("-webkit-box-decoration-break: clone;");
    expect(print).toContain("box-decoration-break: clone;");
    expect(printPartRule("doc-header")).toContain("inset-block-start: 0;");
    expect(printPartRule("doc-footer")).toContain("inset-block-end: 0;");
  });

  it("places running elements into @page margin boxes and emits page counters", () => {
    expect(CSS).toContain("@top-center");
    expect(CSS).toContain("content: element(faqir-doc-header);");
    expect(CSS).toContain("@bottom-center");
    expect(CSS).toContain("content: element(faqir-doc-footer);");
    expect(CSS).toContain("@bottom-right");
    expect(CSS).toContain("counter(page)");
    expect(CSS).toContain("counter(pages)");
  });

  it("retains legacy header/footer selectors as non-breaking aliases", () => {
    expect(CSS).toContain('[data-part="header"]');
    expect(CSS).toContain('[data-part="footer"]');
  });
});

describe("document · canonical and print reference markup", () => {
  it("uses the explicit doc-header/doc-footer parts in canonical markup", () => {
    expect(HTML).toContain('data-part="doc-header"');
    expect(HTML).toContain('data-part="doc-footer"');
    expect(HTML).not.toContain('data-part="header"');
    expect(HTML).not.toContain('data-part="footer"');
  });

  it("ships one dedicated document fixture with at least two forced breaks (3+ pages)", () => {
    expect(PRINT_HTML).toContain("<!-- @ui:reference document-print -->");
    expect(PRINT_HTML).not.toContain("<!-- @ui:component");

    const documents = extractComponents(PRINT_HTML, "document-print.html").filter(
      (component) => component.name === "document",
    );
    expect(documents).toHaveLength(1);
    expect(documents[0].parts["doc-header"]).toHaveLength(1);
    expect(documents[0].parts["doc-footer"]).toHaveLength(1);

    const breaks = extractComponents(PRINT_HTML, "document-print.html").filter(
      (component) => component.name === "page-break",
    );
    expect(breaks.length).toBeGreaterThanOrEqual(2);
  });

  it("keeps the multi-page fixture at zero faqir audit findings", async () => {
    const manifests = await loadRegistryManifestMap(REGISTRY);
    expect(
      auditHtmlSource({
        source: PRINT_HTML,
        file: "registry/patterns/document/document-print.html",
        manifests,
      }),
    ).toEqual([]);
  });
});

describe("document · manifest contract and renderer support", () => {
  it("is schema-valid and documents the new parts plus print reference", () => {
    expect(validateManifest(MANIFEST)).toEqual([]);
    expect(MANIFEST.version).toBe("1.1.0");
    expect(MANIFEST.slots["doc-header"]?.selector).toBe("[data-part='doc-header']");
    expect(MANIFEST.slots["doc-footer"]?.selector).toBe("[data-part='doc-footer']");
    expect(MANIFEST.files.print_reference).toBe("document-print.html");
  });

  it("records running-element and fixed-fallback renderer paths", () => {
    expect(MANIFEST.renderer_support.prince.mechanism).toContain("running()");
    expect(MANIFEST.renderer_support.weasyprint.mechanism).toContain("running()");
    expect(MANIFEST.renderer_support.chromium.mechanism).toContain("fixed");
    expect(MANIFEST.renderer_support.chromium.notes).toContain("page counters");
  });

  it("records the addition as a non-breaking manifest change", () => {
    const change = MANIFEST.changes?.find((entry) => entry.version === "1.1.0");
    expect(change).toBeDefined();
    expect(change!.breaking).toBe(false);
    expect(change!.note).toContain("doc-header");
    expect(change!.note).toContain("doc-footer");
  });
});
