// Codegen tests for `faqir bindings vue` (task 0.6-12): per-primitive
// snapshots, the manifest-drift guard (regenerating must produce zero diff
// against the committed files — §11.1 made literal), and the structural
// guarantees: every primitive generated, typed props for every variant group,
// zero hand-written per-component code, runtime within its line budget.

import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadPrimitiveIRs } from "../../../src/bindings/ir";
import { loadRecipeBundle } from "../../../src/bindings/recipe-ir";
import { emitVuePackage } from "../../../src/bindings/vue";
import { getRegistryPath } from "../../../src/utils/fs";
import { listRegistryComponents } from "../../../src/utils/components";
import { pascalCase } from "../../../src/bindings/ir";

const PKG = join(import.meta.dir, "..");
const SRC = join(PKG, "src");

const irs = await loadPrimitiveIRs(getRegistryPath());
const recipes = await loadRecipeBundle(getRegistryPath());
const generated = emitVuePackage(irs, recipes);

describe("bindings vue codegen", () => {
  it("generates a component for every registry primitive", () => {
    const primitives = listRegistryComponents(getRegistryPath(), "primitives").sort();
    expect(irs.map((ir) => ir.name)).toEqual(primitives);
    for (const name of primitives) {
      expect(generated.has(`components/${name}.ts`)).toBe(true);
    }
    expect(generated.has("index.ts")).toBe(true);
  });

  it("types every root variant group as a literal union", () => {
    for (const ir of irs) {
      const source = generated.get(`components/${ir.name}.ts`)!;
      for (const v of ir.variants) {
        const typeName = `${ir.componentName}${pascalCase(v.prop)}`;
        expect(source).toContain(`export type ${typeName} = `);
        for (const value of v.values) expect(source).toContain(JSON.stringify(value));
      }
      expect(source).toContain(`export interface ${ir.componentName}Props`);
    }
  });

  it("part-applied states never become root props (stepper, nav)", () => {
    const stepper = irs.find((ir) => ir.name === "stepper")!;
    const nav = irs.find((ir) => ir.name === "nav")!;
    expect(stepper.states).toEqual([]);
    expect(nav.states).toEqual([]);
  });

  it("default states are skipped (switch off, button default)", () => {
    const sw = irs.find((ir) => ir.name === "switch")!;
    expect(sw.states.map((s) => s.prop)).toEqual(["on", "disabled"]);
    const button = irs.find((ir) => ir.name === "button")!;
    expect(button.states.map((s) => s.prop)).toEqual(["loading", "disabled"]);
  });

  it("reserved attr names get the Variant suffix (separator data-style)", () => {
    const sep = irs.find((ir) => ir.name === "separator")!;
    expect(sep.variants.map((v) => v.prop)).toEqual(["variant", "styleVariant"]);
  });

  it("void roots render no slots or default slot (input, separator)", () => {
    for (const name of ["input", "separator", "radio", "checkbox"]) {
      const ir = irs.find((i) => i.name === name)!;
      expect(ir.voidRoot).toBe(true);
      expect(ir.slots).toEqual([]);
      expect(ir.defaultSlot).toBe(false);
    }
  });

  it("snapshot per primitive", () => {
    for (const ir of irs) {
      expect(generated.get(`components/${ir.name}.ts`)!).toMatchSnapshot(`vue:${ir.name}`);
    }
    expect(generated.get("index.ts")!).toMatchSnapshot("vue:index");
  });
});

describe("manifest-drift guard (§11.1: bindings can't drift)", () => {
  it("committed files byte-match a fresh regeneration", () => {
    for (const [rel, content] of generated) {
      const path = join(SRC, rel);
      expect(existsSync(path)).toBe(true);
      expect(readFileSync(path, "utf8")).toBe(content);
    }
  });

  it("no stale generated files linger", () => {
    for (const sub of ["components", "recipes", "controllers"]) {
      const committed = readdirSync(join(SRC, sub)).filter((f) => f.endsWith(".ts"));
      const fresh = [...generated.keys()]
        .filter((k) => k.startsWith(`${sub}/`))
        .map((k) => k.slice(sub.length + 1));
      expect(committed.sort()).toEqual(fresh.sort());
    }
  });
});

describe("zero hand-written per-component code", () => {
  it("every component module is generated and spec-only", () => {
    for (const dir of ["components", "recipes"]) {
      for (const file of readdirSync(join(SRC, dir))) {
        const source = readFileSync(join(SRC, dir, file), "utf8");
        expect(source.startsWith("// AUTO-GENERATED by `faqir bindings vue`")).toBe(true);
        // Spec-only: no render logic in generated modules — the runtime owns it.
        expect(source).not.toContain("import { h");
        expect(source).not.toContain("defineComponent");
      }
    }
  });

  it("every controller module is vendored, never hand-written", () => {
    for (const file of readdirSync(join(SRC, "controllers"))) {
      const source = readFileSync(join(SRC, "controllers", file), "utf8");
      expect(source.startsWith("// AUTO-GENERATED by `faqir bindings vue` — vendored")).toBe(true);
    }
  });

  it("runtimes stay within their ~150-line budgets", () => {
    for (const file of ["runtime.ts", "recipe-runtime.ts"]) {
      const runtime = readFileSync(join(SRC, file), "utf8");
      const total = runtime.trimEnd().split("\n").length;
      console.log(`${file}: ${total} lines`);
      expect(total).toBeLessThanOrEqual(150);
    }
  });
});

describe("recipe codegen (task 0.6-13)", () => {
  it("generates a wrapper + vendored controller for every registry recipe", () => {
    const names = listRegistryComponents(getRegistryPath(), "recipes").sort();
    expect(recipes.irs.map((ir) => ir.name)).toEqual(names);
    for (const name of names) {
      expect(generated.has(`recipes/${name}.ts`)).toBe(true);
      expect(generated.has(`controllers/${name}.ts`)).toBe(true);
    }
  });

  it("every recipe exposes its @ui:provides API minus destroy", () => {
    for (const ir of recipes.irs) {
      expect(ir.methods.length).toBeGreaterThan(0);
      expect(ir.methods).not.toContain("destroy");
    }
    const dialog = recipes.irs.find((ir) => ir.name === "dialog")!;
    expect(dialog.methods).toEqual(["open", "close", "toggle"]);
  });

  it("controller events are scanned, including via cross-recipe imports", () => {
    const byName = Object.fromEntries(recipes.irs.map((ir) => [ir.name, ir.events]));
    expect(byName["dialog"]).toEqual(["cancel", "confirm"]);
    // alert-dialog delegates to dialog wholesale — it re-emits dialog's events.
    expect(byName["alert-dialog"]).toEqual(["cancel", "confirm"]);
    // date-picker embeds calendar; its calendar-change bubbles through.
    expect(byName["date-picker"]).toEqual(["calendar-change", "date-change"]);
    expect(byName["input-otp"]).toEqual(["change", "complete"]); // faqir:mask is listened-to, not emitted
    expect(byName["pagination"]).toEqual(["page-change"]);
    expect(byName["slider"]).toEqual(["change"]);
    expect(byName["table"]).toContain("sort");
    expect(byName["table"]).toContain("selection-change");
  });

  it("template contract attributes survive into the tree (dialog FOUC + a11y)", () => {
    const dialog = generated.get("recipes/dialog.ts")!;
    expect(dialog).toContain('["hidden",true]'); // overlay + panel start hidden — no FOUC
    expect(dialog).toContain('["role",["dialog"]]');
    expect(dialog).toContain('["aria-modal",["true"]]');
    expect(dialog).toContain('[{"p":"id"},"-title"]'); // aria-labelledby wired to the id prop
    expect(dialog).toContain('["data-state",["closed"]]');
  });

  it("part-applied variants land on their part, typed as unions", () => {
    const dialog = recipes.irs.find((ir) => ir.name === "dialog")!;
    const size = dialog.variantProps.find((v) => v.prop === "size")!;
    expect(size.part).toBe("panel");
    expect(size.values).toEqual(["sm", "md", "lg", "full"]);
    const source = generated.get("recipes/dialog.ts")!;
    expect(source).toContain('export type LDialogSize = "sm" | "md" | "lg" | "full";');
    expect(source).toContain('export type LDialogTone = "default" | "danger";');
  });

  it("reserved variant group names get the Variant suffix (tabs style)", () => {
    const tabs = recipes.irs.find((ir) => ir.name === "tabs")!;
    expect(tabs.variantProps.map((v) => v.prop)).toContain("styleVariant");
  });

  it("attribute-position placeholders become boolean props (alert-dialog confirm-required)", () => {
    const alert = recipes.irs.find((ir) => ir.name === "alert-dialog")!;
    expect(alert.boolProps).toEqual(["confirmRequired"]);
    expect(generated.get("recipes/alert-dialog.ts")!).toContain('["data-confirm-required",{"b":"confirmRequired"}]');
  });

  it("l-* directive attributes are stripped (input-otp l-mask)", () => {
    // The description may mention l-mask; the render tree must not carry the attr.
    expect(generated.get("recipes/input-otp.ts")!).not.toContain('["l-mask"');
    expect(JSON.stringify(recipes.irs.find((ir) => ir.name === "input-otp")!.tree)).not.toContain("l-mask");
  });

  it("named slots are the unique manifest parts of the template", () => {
    const dialog = recipes.irs.find((ir) => ir.name === "dialog")!;
    expect(dialog.slots.sort()).toEqual(
      ["trigger", "overlay", "panel", "header", "title", "body", "footer", "close"].sort()
    );
    // Repeated parts (accordion items, tab triggers) are never named slots.
    const tabs = recipes.irs.find((ir) => ir.name === "tabs")!;
    expect(tabs.slots).toEqual(["list"]);
    const accordion = recipes.irs.find((ir) => ir.name === "accordion")!;
    expect(accordion.slots).toEqual([]);
  });

  it("vendored controllers rewrite imports to package-local modules", () => {
    expect(generated.get("controllers/dialog.ts")!).toContain('from "./_core-focus"');
    expect(generated.get("controllers/alert-dialog.ts")!).toContain('from "./dialog"');
    expect(generated.get("controllers/date-picker.ts")!).toContain('from "./calendar"');
    for (const helper of ["focus", "events", "utils"]) {
      expect(generated.has(`controllers/_core-${helper}.ts`)).toBe(true);
    }
  });

  it("snapshot per recipe", () => {
    for (const ir of recipes.irs) {
      expect(generated.get(`recipes/${ir.name}.ts`)!).toMatchSnapshot(`vue-recipe:${ir.name}`);
    }
  });
});
