// Codegen tests for `faqir bindings vue` (task 0.6-12): per-primitive
// snapshots, the manifest-drift guard (regenerating must produce zero diff
// against the committed files — §11.1 made literal), and the structural
// guarantees: every primitive generated, typed props for every variant group,
// zero hand-written per-component code, runtime within its line budget.

import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadPrimitiveIRs } from "../../../src/bindings/ir";
import { emitVuePackage } from "../../../src/bindings/vue";
import { getRegistryPath } from "../../../src/utils/fs";
import { listRegistryComponents } from "../../../src/utils/components";
import { pascalCase } from "../../../src/bindings/ir";

const PKG = join(import.meta.dir, "..");
const SRC = join(PKG, "src");

const irs = await loadPrimitiveIRs(getRegistryPath());
const generated = emitVuePackage(irs);

describe("bindings vue codegen", () => {
  it("generates a component for every registry primitive", () => {
    const primitives = listRegistryComponents(getRegistryPath(), "primitives").sort();
    expect(irs.map((ir) => ir.name)).toEqual(primitives);
    for (const name of primitives) {
      expect(generated.has(`components/${name}.ts`)).toBe(true);
    }
    expect(generated.has("index.ts")).toBe(true);
  });

  it("types every root variant group as a literal union", () => {
    for (const ir of irs) {
      const source = generated.get(`components/${ir.name}.ts`)!;
      for (const v of ir.variants) {
        const typeName = `${ir.componentName}${pascalCase(v.prop)}`;
        expect(source).toContain(`export type ${typeName} = `);
        for (const value of v.values) expect(source).toContain(JSON.stringify(value));
      }
      expect(source).toContain(`export interface ${ir.componentName}Props`);
    }
  });

  it("part-applied states never become root props (stepper, nav)", () => {
    const stepper = irs.find((ir) => ir.name === "stepper")!;
    const nav = irs.find((ir) => ir.name === "nav")!;
    expect(stepper.states).toEqual([]);
    expect(nav.states).toEqual([]);
  });

  it("default states are skipped (switch off, button default)", () => {
    const sw = irs.find((ir) => ir.name === "switch")!;
    expect(sw.states.map((s) => s.prop)).toEqual(["on", "disabled"]);
    const button = irs.find((ir) => ir.name === "button")!;
    expect(button.states.map((s) => s.prop)).toEqual(["loading", "disabled"]);
  });

  it("reserved attr names get the Variant suffix (separator data-style)", () => {
    const sep = irs.find((ir) => ir.name === "separator")!;
    expect(sep.variants.map((v) => v.prop)).toEqual(["variant", "styleVariant"]);
  });

  it("void roots render no slots or default slot (input, separator)", () => {
    for (const name of ["input", "separator", "radio", "checkbox"]) {
      const ir = irs.find((i) => i.name === name)!;
      expect(ir.voidRoot).toBe(true);
      expect(ir.slots).toEqual([]);
      expect(ir.defaultSlot).toBe(false);
    }
  });

  it("snapshot per primitive", () => {
    for (const ir of irs) {
      expect(generated.get(`components/${ir.name}.ts`)!).toMatchSnapshot(`vue:${ir.name}`);
    }
    expect(generated.get("index.ts")!).toMatchSnapshot("vue:index");
  });
});

describe("manifest-drift guard (§11.1: bindings can't drift)", () => {
  it("committed files byte-match a fresh regeneration", () => {
    for (const [rel, content] of generated) {
      const path = join(SRC, rel);
      expect(existsSync(path)).toBe(true);
      expect(readFileSync(path, "utf8")).toBe(content);
    }
  });

  it("no stale generated files linger", () => {
    const committed = readdirSync(join(SRC, "components")).filter((f) => f.endsWith(".ts"));
    const fresh = [...generated.keys()]
      .filter((k) => k.startsWith("components/"))
      .map((k) => k.slice("components/".length));
    expect(committed.sort()).toEqual(fresh.sort());
  });
});

describe("zero hand-written per-component code", () => {
  it("every component module is generated and spec-only", () => {
    for (const file of readdirSync(join(SRC, "components"))) {
      const source = readFileSync(join(SRC, "components", file), "utf8");
      expect(source.startsWith("// AUTO-GENERATED by `faqir bindings vue`")).toBe(true);
      // Spec-only: no render logic in generated modules — the runtime owns it.
      expect(source).not.toContain("import { h");
      expect(source).not.toContain("defineComponent");
    }
  });

  it("runtime stays within its ~150-line budget", () => {
    const runtime = readFileSync(join(SRC, "runtime.ts"), "utf8");
    const total = runtime.trimEnd().split("\n").length;
    console.log(`runtime.ts: ${total} lines`);
    expect(total).toBeLessThanOrEqual(150);
  });
});
