// AUTO-GENERATED by `faqir bindings react` from registry/primitives/badge/badge.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef } from "react";

/** Allowed `variant` values (manifest variant group "visual", attr `data-variant`). */
export type LBadgeVariant = "default" | "primary" | "secondary" | "destructive" | "success" | "warning";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LBadgeSize = "sm" | "md" | "lg";

export interface LBadgeProps extends Omit<ComponentPropsWithoutRef<"span">, "variant" | "size"> {
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LBadgeVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LBadgeSize;
}

/** `badge` — Small status indicator with color variants */
export const LBadge = createFaqirPrimitive<LBadgeProps>({
  name: "badge",
  tag: "span",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["default", "primary", "secondary", "destructive", "success", "warning"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [],
  defaultSlot: true,
}, "LBadge");

export default LBadge;
