// AUTO-GENERATED by `faqir bindings react` from registry/primitives/breadcrumb/breadcrumb.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LBreadcrumbSize = "sm" | "md" | "lg";

export interface LBreadcrumbProps extends Omit<ComponentPropsWithoutRef<"nav">, "size" | "list" | "item" | "separator" | "current"> {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LBreadcrumbSize;
  /** Projected into `<ol data-part="list">`. */
  list?: ReactNode;
  /** Projected into `<a data-part="item">`. */
  item?: ReactNode;
  /** Projected into `<li data-part="separator">`. */
  separator?: ReactNode;
  /** Projected into `<span data-part="current">` (required part — always rendered). */
  current?: ReactNode;
}

/** `breadcrumb` — Breadcrumb trail — a <nav aria-label="Breadcrumb"> with link items, presentational separators, and the current page marked aria-current="page" */
export const LBreadcrumb = createFaqirPrimitive<LBreadcrumbProps>({
  name: "breadcrumb",
  tag: "nav",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "list", tag: "ol", required: false, isVoid: false },
    { name: "item", tag: "a", required: false, isVoid: false },
    { name: "separator", tag: "li", required: false, isVoid: false },
    { name: "current", tag: "span", required: true, isVoid: false },
  ],
  defaultSlot: false,
}, "LBreadcrumb");

export default LBreadcrumb;
