// AUTO-GENERATED by `faqir bindings react` from registry/primitives/callout/callout.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LCalloutVariant = "info" | "warning" | "destructive" | "success" | "muted";

export interface LCalloutProps extends Omit<ComponentPropsWithoutRef<"div">, "variant" | "icon" | "content" | "title" | "dismiss"> {
  /** `data-variant`; omitted when unset (manifest default: "info"). */
  variant?: LCalloutVariant;
  /** Projected into `<span data-part="icon">`. */
  icon?: ReactNode;
  /** Projected into `<div data-part="content">` (required part — always rendered). */
  content?: ReactNode;
  /** Projected into `<strong data-part="title">`. */
  title?: ReactNode;
  /** Projected into `<button data-part="dismiss">`. */
  dismiss?: ReactNode;
}

/** `callout` — Callout box for info notices, warnings, alerts, legal text, and disclaimers */
export const LCallout = createFaqirPrimitive<LCalloutProps>({
  name: "callout",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["info", "warning", "destructive", "success", "muted"] },
  ],
  states: [],
  slots: [
    { name: "icon", tag: "span", required: false, isVoid: false },
    { name: "content", tag: "div", required: true, isVoid: false },
    { name: "title", tag: "strong", required: false, isVoid: false },
    { name: "dismiss", tag: "button", required: false, isVoid: false },
  ],
  defaultSlot: false,
}, "LCallout");

export default LCallout;
