// AUTO-GENERATED by `faqir bindings react` from registry/primitives/description-list/description-list.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LDescriptionListVariant = "vertical" | "horizontal";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LDescriptionListSize = "sm" | "md" | "lg";

export interface LDescriptionListProps extends Omit<ComponentPropsWithoutRef<"dl">, "variant" | "size" | "term" | "details"> {
  /** `data-variant`; omitted when unset (manifest default: "vertical"). */
  variant?: LDescriptionListVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LDescriptionListSize;
  /** Projected into `<dt data-part="term">` (required part — always rendered). */
  term?: ReactNode;
  /** Projected into `<dd data-part="details">` (required part — always rendered). */
  details?: ReactNode;
}

/** `description-list` — Styled description list (dl/dt/dd) for longer descriptive key-value content */
export const LDescriptionList = createFaqirPrimitive<LDescriptionListProps>({
  name: "description-list",
  tag: "dl",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["vertical", "horizontal"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "term", tag: "dt", required: true, isVoid: false },
    { name: "details", tag: "dd", required: true, isVoid: false },
  ],
  defaultSlot: false,
}, "LDescriptionList");

export default LDescriptionList;
