// AUTO-GENERATED by `faqir bindings react` from registry/primitives/empty-state/empty-state.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LEmptyStateSize = "sm";

export interface LEmptyStateProps extends Omit<ComponentPropsWithoutRef<"div">, "size" | "icon" | "title" | "description" | "actions"> {
  /** `data-size`; omitted when unset (manifest default: ""). */
  size?: LEmptyStateSize;
  /** Projected into `<span data-part="icon">`. */
  icon?: ReactNode;
  /** Projected into `<h3 data-part="title">` (required part — always rendered). */
  title?: ReactNode;
  /** Projected into `<p data-part="description">`. */
  description?: ReactNode;
  /** Projected into `<div data-part="actions">`. */
  actions?: ReactNode;
}

/** `empty-state` — Placeholder for empty content sections with icon, title, description, and action slots */
export const LEmptyState = createFaqirPrimitive<LEmptyStateProps>({
  name: "empty-state",
  tag: "div",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm"] },
  ],
  states: [],
  slots: [
    { name: "icon", tag: "span", required: false, isVoid: false },
    { name: "title", tag: "h3", required: true, isVoid: false },
    { name: "description", tag: "p", required: false, isVoid: false },
    { name: "actions", tag: "div", required: false, isVoid: false },
  ],
  defaultSlot: false,
}, "LEmptyState");

export default LEmptyState;
