// AUTO-GENERATED by `faqir bindings react` from registry/primitives/field-group/field-group.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `variant` values (manifest variant group "layout", attr `data-variant`). */
export type LFieldGroupVariant = "vertical" | "horizontal";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LFieldGroupSize = "sm" | "md" | "lg";

export interface LFieldGroupProps extends Omit<ComponentPropsWithoutRef<"div">, "variant" | "size" | "invalid" | "validating" | "valid" | "disabled" | "label" | "required" | "input" | "description" | "error"> {
  /** `data-variant`; omitted when unset (manifest default: "vertical"). */
  variant?: LFieldGroupVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LFieldGroupSize;
  /** Sets `data-state="invalid"`. */
  invalid?: boolean;
  /** Sets `data-state="validating"`. */
  validating?: boolean;
  /** Sets `data-state="valid"`. */
  valid?: boolean;
  /** Sets `data-state="disabled"`. */
  disabled?: boolean;
  /** Projected into `<label data-part="label">` (required part — always rendered). */
  label?: ReactNode;
  /** Projected into `<span data-part="required">`. */
  required?: ReactNode;
  /** Projected into `<div data-part="input">` (required part — always rendered). */
  input?: ReactNode;
  /** Projected into `<p data-part="description">`. */
  description?: ReactNode;
  /** Projected into `<p data-part="error">`. */
  error?: ReactNode;
}

/** `field-group` — Form field wrapper combining label, input slot, description, and error message, with a normalized validation contract (§7.1): states invalid | validating | disabled, a standardized required marker, and CSS-driven error visibility (no JS class toggling) */
export const LFieldGroup = createFaqirPrimitive<LFieldGroupProps>({
  name: "field-group",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["vertical", "horizontal"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [
    { prop: "invalid", attr: "data-state", value: "invalid", kind: "value" },
    { prop: "validating", attr: "data-state", value: "validating", kind: "value" },
    { prop: "valid", attr: "data-state", value: "valid", kind: "value" },
    { prop: "disabled", attr: "data-state", value: "disabled", kind: "value" },
  ],
  slots: [
    { name: "label", tag: "label", required: true, isVoid: false },
    { name: "required", tag: "span", required: false, isVoid: false },
    { name: "input", tag: "div", required: true, isVoid: false },
    { name: "description", tag: "p", required: false, isVoid: false },
    { name: "error", tag: "p", required: false, isVoid: false },
  ],
  defaultSlot: false,
}, "LFieldGroup");

export default LFieldGroup;
