// AUTO-GENERATED by `faqir bindings react` from registry/primitives/grid/grid.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef } from "react";

/** Allowed `cols` values (manifest variant group "cols", attr `data-cols`). */
export type LGridCols = "1" | "2" | "3" | "4" | "6" | "12";

/** Allowed `gap` values (manifest variant group "gap", attr `data-gap`). */
export type LGridGap = "2" | "4" | "6" | "8";

export interface LGridProps extends Omit<ComponentPropsWithoutRef<"div">, "cols" | "gap"> {
  /** `data-cols`; omitted when unset (manifest default: "1"). */
  cols?: LGridCols;
  /** `data-gap`; omitted when unset (manifest default: "4"). */
  gap?: LGridGap;
}

/** `grid` — CSS Grid container with configurable columns and gap */
export const LGrid = createFaqirPrimitive<LGridProps>({
  name: "grid",
  tag: "div",
  variants: [
    { prop: "cols", attr: "data-cols", values: ["1", "2", "3", "4", "6", "12"] },
    { prop: "gap", attr: "data-gap", values: ["2", "4", "6", "8"] },
  ],
  states: [],
  slots: [],
  defaultSlot: true,
}, "LGrid");

export default LGrid;
