// AUTO-GENERATED by `faqir bindings react` from registry/primitives/key-value/key-value.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LKeyValueVariant = "horizontal" | "vertical" | "inline";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LKeyValueSize = "sm" | "md" | "lg";

export interface LKeyValueProps extends Omit<ComponentPropsWithoutRef<"div">, "variant" | "size" | "label" | "value"> {
  /** `data-variant`; omitted when unset (manifest default: "horizontal"). */
  variant?: LKeyValueVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LKeyValueSize;
  /** Projected into `<dt data-part="label">` (required part — always rendered). */
  label?: ReactNode;
  /** Projected into `<dd data-part="value">` (required part — always rendered). */
  value?: ReactNode;
}

/** `key-value` — Labeled data pair for displaying key-value information */
export const LKeyValue = createFaqirPrimitive<LKeyValueProps>({
  name: "key-value",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["horizontal", "vertical", "inline"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "label", tag: "dt", required: true, isVoid: false },
    { name: "value", tag: "dd", required: true, isVoid: false },
  ],
  defaultSlot: false,
}, "LKeyValue");

export default LKeyValue;
