// AUTO-GENERATED by `faqir bindings react` from registry/primitives/label/label.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `variant` values (manifest variant group "visual", attr `data-variant`). */
export type LLabelVariant = "default" | "required";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LLabelSize = "sm" | "md" | "lg";

export interface LLabelProps extends Omit<ComponentPropsWithoutRef<"label">, "variant" | "size" | "disabled" | "indicator"> {
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LLabelVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LLabelSize;
  /** Sets `data-state="disabled"`. */
  disabled?: boolean;
  /** Projected into `<span data-part="indicator">`. */
  indicator?: ReactNode;
}

/** `label` — Form label with optional required/optional indicator */
export const LLabel = createFaqirPrimitive<LLabelProps>({
  name: "label",
  tag: "label",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["default", "required"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [
    { prop: "disabled", attr: "data-state", value: "disabled", kind: "value" },
  ],
  slots: [
    { name: "indicator", tag: "span", required: false, isVoid: false },
  ],
  defaultSlot: true,
}, "LLabel");

export default LLabel;
