// AUTO-GENERATED by `faqir bindings react` from registry/primitives/rating/rating.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime.js";
import type { ComponentPropsWithoutRef } from "react";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LRatingSize = "sm" | "md" | "lg";

export interface LRatingProps extends Omit<ComponentPropsWithoutRef<"span">, "size"> {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LRatingSize;
}

/** `rating` — A read-only five-star score drawn by a single element: a repeated star mask over a gradient filled to value/5, so half stars and exact averages need no extra markup. Sizes with the surrounding text, fills from the line's start edge in either direction, and stays legible in forced colours. */
export const LRating = createFaqirPrimitive<LRatingProps>({
  name: "rating",
  tag: "span",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [],
  defaultSlot: false,
}, "LRating");

export default LRating;
