// AUTO-GENERATED by `faqir bindings react` from registry/primitives/stat/stat.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LStatSize = "sm" | "md" | "lg";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LStatVariant = "default" | "card";

/** Allowed `trend` values (manifest variant group "trend", attr `data-trend`). */
export type LStatTrend = "up" | "down" | "neutral";

export interface LStatProps extends Omit<ComponentPropsWithoutRef<"div">, "size" | "variant" | "trend" | "value" | "label" | "change" | "icon"> {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LStatSize;
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LStatVariant;
  /** `data-trend`; omitted when unset (manifest default: ""). */
  trend?: LStatTrend;
  /** Projected into `<span data-part="value">` (required part — always rendered). */
  value?: ReactNode;
  /** Projected into `<span data-part="label">` (required part — always rendered). */
  label?: ReactNode;
  /** Projected into `<span data-part="change">`. */
  change?: ReactNode;
  /** Projected into `<span data-part="icon">`. */
  icon?: ReactNode;
}

/** `stat` — Large metric display with number, label, and optional change indicator */
export const LStat = createFaqirPrimitive<LStatProps>({
  name: "stat",
  tag: "div",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
    { prop: "variant", attr: "data-variant", values: ["default", "card"] },
    { prop: "trend", attr: "data-trend", values: ["up", "down", "neutral"] },
  ],
  states: [],
  slots: [
    { name: "value", tag: "span", required: true, isVoid: false },
    { name: "label", tag: "span", required: true, isVoid: false },
    { name: "change", tag: "span", required: false, isVoid: false },
    { name: "icon", tag: "span", required: false, isVoid: false },
  ],
  defaultSlot: false,
}, "LStat");

export default LStat;
