// AUTO-GENERATED by `faqir bindings react` from registry/primitives/switcher/switcher.manifest.json.
// Do not edit — regenerate with `faqir bindings react`.

import { createFaqirPrimitive } from "../runtime";
import type { ComponentPropsWithoutRef } from "react";

/** Allowed `threshold` values (manifest variant group "threshold", attr `data-threshold`). */
export type LSwitcherThreshold = "sm" | "md" | "lg" | "xl";

/** Allowed `gap` values (manifest variant group "gap", attr `data-gap`). */
export type LSwitcherGap = "0" | "1" | "2" | "3" | "4" | "6" | "8" | "10" | "12" | "16";

export interface LSwitcherProps extends Omit<ComponentPropsWithoutRef<"div">, "threshold" | "gap"> {
  /** `data-threshold`; omitted when unset (manifest default: "sm"). */
  threshold?: LSwitcherThreshold;
  /** `data-gap`; omitted when unset (manifest default: "4"). */
  gap?: LSwitcherGap;
}

/** `switcher` — A row of equal-width peers that becomes a single column when the switcher itself is narrower than its threshold — driven by a container query on its own inline size, never by the viewport, so the same markup is correct full-bleed, in a sidebar and in a dialog */
export const LSwitcher = createFaqirPrimitive<LSwitcherProps>({
  name: "switcher",
  tag: "div",
  variants: [
    { prop: "threshold", attr: "data-threshold", values: ["sm", "md", "lg", "xl"] },
    { prop: "gap", attr: "data-gap", values: ["0", "1", "2", "3", "4", "6", "8", "10", "12", "16"] },
  ],
  states: [],
  slots: [],
  defaultSlot: true,
}, "LSwitcher");

export default LSwitcher;
