// AUTO-GENERATED by `faqir bindings vue` — vendored verbatim from
// registry/core/events.js (imports rewritten to package-local paths).
// Do not edit — regenerate with `faqir bindings vue`. The registry file is
// the single source of truth; the drift guard keeps this copy in sync.
// @ts-nocheck — registry controllers are plain JS by design (zero build step).
// @ui:core events
// @ui:provides delegate once onOutsideClick

/**
 * Delegate an event to descendants matching a selector.
 * @param {Element} root
 * @param {string} event
 * @param {string} selector
 * @param {Function} handler
 * @returns {Function} cleanup function
 */
export function delegate(root, event, selector, handler) {
  function listener(e) {
    const target = e.target.closest(selector);
    if (target && root.contains(target)) {
      handler(e, target);
    }
  }
  root.addEventListener(event, listener);
  return () => root.removeEventListener(event, listener);
}

/**
 * Listen for an event once, then auto-remove.
 * @param {Element} el
 * @param {string} event
 * @param {Function} handler
 * @returns {Function} cleanup function (cancels if not yet fired)
 */
export function once(el, event, handler) {
  function listener(e) {
    cleanup();
    handler(e);
  }
  function cleanup() {
    el.removeEventListener(event, listener);
  }
  el.addEventListener(event, listener);
  return cleanup;
}

/**
 * Call handler when a click occurs outside the given element.
 * @param {Element} el
 * @param {Function} handler
 * @returns {Function} cleanup function
 */
export function onOutsideClick(el, handler) {
  function listener(e) {
    if (!el.contains(e.target)) {
      handler(e);
    }
  }
  document.addEventListener("pointerdown", listener);
  return () => document.removeEventListener("pointerdown", listener);
}
