import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadManifest } from "../manifest";
import { ensureDir, getRegistryPath } from "./fs";
import { controllerName } from "./components";
import type { FaqirConfig } from "./config";

/**
 * The runtime half of `core/faqir.js` — everything after the `controllers`
 * table: mount on DOM ready, init controllers on added nodes, destroy them on
 * removed ones. Read from the registry's own `core/faqir.js` (shipped in the
 * npm package next to the CLI) so the file `faqir add` writes into a project
 * can never drift from the one the registry tests exercise. It once did: the
 * registry copy learned to tear down removed controllers and this template
 * kept the added-only observer.
 */
export function faqirInitRuntime(registryPath: string = getRegistryPath()): string {
  const source = readFileSync(join(registryPath, "core", "faqir.js"), "utf8");
  const start = source.indexOf("\nconst controllers = {");
  const end = start < 0 ? -1 : source.indexOf("\n};\n", start);
  if (end < 0) {
    throw new Error("registry/core/faqir.js has no `const controllers = { … };` table to split at");
  }
  return source.slice(end + "\n};\n".length);
}

/**
 * The factory a recipe controller actually exports — read from the installed
 * source the same way scripts/build-core.mjs reads it, because the name is not
 * derivable from the recipe name: `toast` exports `createToastContainer`,
 * `input-otp` `createInputOTP`, `qr-code` `createQRCode`. Deriving it imported
 * names that do not exist, which is a SyntaxError that takes the whole
 * auto-init module down. Falls back to the derived name if the file is absent.
 */
function factoryName(outputDir: string, recipe: string): string {
  const file = join(outputDir, "recipes", recipe, `${recipe}.js`);
  if (existsSync(file)) {
    const m = readFileSync(file, "utf8").match(/export\s+function\s+([A-Za-z0-9_$]+)\s*\(/);
    if (m) return m[1];
  }
  return controllerName(recipe);
}

export async function regenerateFaqirInit(
  config: { installed: { recipes: string[] } },
  outputDir: string
): Promise<void> {
  const coreDir = join(outputDir, "core");
  if (!existsSync(coreDir)) return;

  const recipes = config.installed.recipes;
  if (recipes.length === 0) return;

  const factories = recipes.map((r) => factoryName(outputDir, r));

  const imports = recipes
    .map((r, i) => `import { ${factories[i]} } from "../recipes/${r}/${r}.js";`)
    .join("\n");

  const entries = recipes
    .map((r, i) => `  ${JSON.stringify(r)}: ${factories[i]},`)
    .join("\n");

  const content = `// @ui:core faqir
// @ui:provides init controllers
// Auto-generated by \`faqir add\`. Do not edit manually.

${imports}

const controllers = {
${entries}
};
${faqirInitRuntime()}`;

  await Bun.write(join(coreDir, "faqir.js"), content);
}

export async function regenerateContext(
  config: { installed: { primitives: string[]; recipes: string[]; patterns: string[] }; theme: string },
  outputDir: string,
  cwd: string
): Promise<void> {
  const components: Record<string, unknown> = {};

  for (const layer of ["primitives", "recipes", "patterns"] as const) {
    for (const name of config.installed[layer]) {
      const manifestPath = join(outputDir, layer, name, `${name}.manifest.json`);
      if (!existsSync(manifestPath)) continue;

      const manifest = await loadManifest(manifestPath);

      const entry: Record<string, unknown> = {
        kind: manifest.kind,
      };

      if (manifest.aliases && manifest.aliases.length > 0) {
        entry.aliases = manifest.aliases;
      }

      if (manifest.variants) {
        const variants: Record<string, string[]> = {};
        for (const [key, v] of Object.entries(manifest.variants)) {
          variants[key] = v.values;
        }
        entry.variants = variants;
      }

      if (manifest.slots && Object.keys(manifest.slots).length > 0) {
        entry.slots = Object.keys(manifest.slots);
      }

      if (manifest.states && Object.keys(manifest.states).length > 0) {
        entry.states = Object.keys(manifest.states);
      }

      if (manifest.templates?.html) {
        entry.template = manifest.templates.html;
      }

      if (manifest.safe_transforms?.length > 0) {
        entry.safe_transforms = manifest.safe_transforms;
      }

      if (manifest.files?.js) {
        entry.controller = manifest.files.js;
      }

      components[name] = entry;
    }
  }

  const context = {
    meta: {
      framework: "faqir",
      version: "1.0.0",
      theme: config.theme,
      generated_at: new Date().toISOString(),
      component_count: {
        primitives: config.installed.primitives.length,
        recipes: config.installed.recipes.length,
        patterns: config.installed.patterns.length,
      },
    },
    protocol: {
      identity: "data-ui",
      part: "data-part",
      state: "data-state",
      variant: "data-variant",
      size: "data-size",
      css_target: "[data-ui='name']",
      state_css: "[data-state='value']",
      theme_attr: "data-theme on <html>",
    },
    components,
    rules: {
      use_data_state_not_classes: true,
      always_aria_label_on_icon_buttons: true,
      always_aria_labelledby_on_dialog_panel: true,
      semantic_html_over_div_soup: true,
      tokens_only_no_hardcoded_values: true,
    },
  };

  const faqirDir = join(cwd, ".faqir");
  ensureDir(faqirDir);
  await Bun.write(join(faqirDir, "context.json"), JSON.stringify(context, null, 2) + "\n");
}
