// Framework assets — the token layer and base styles a project was given by
// `faqir init`, kept current by `faqir upgrade` (1.1 release blocker).
//
// `init` copies `registry/tokens` and `registry/base` into the output directory
// ONCE. Components are refreshed by `add`/`upgrade`; until 1.1 nothing ever
// refreshed these. 1.1 components read ~54 custom properties 1.0's token layer
// does not define (`--switch-width`, `--border-width`, `--focus-ring-*`,
// `--panel-bg`, …), so a 1.0 project that upgraded its components rendered
// them against undefined tokens — a switch with no width, a dialog with no
// fill, a keyboard focus with no ring — while `doctor` said healthy.
//
// ── What is framework-owned ─────────────────────────────────────────────────
// Exactly what `init` wrote from the registry, minus the theme:
//
//   • `tokens/index.css` + `tokens/imports.css` (the default, concatenated
//     layout), or every file of `registry/tokens` (`--tokens-split`);
//   • `base/{reset,prose,rhythm,motion-presets}.css`.
//
// `tokens/theme.css` is the USER's — a copy of a theme they chose and then
// edit — and so is anything else they put under `tokens/` (a custom
// `theme-acme.css`, a `fonts.css`). None of it is ever read or written here.
//
// ── How a file is brought up to date ────────────────────────────────────────
// The same three-way merge `upgrade` runs on a component (`mergeFile`), over:
//
//   • base   — the bytes the project was given: `.faqir/pristine/framework/`,
//              recorded on every clean sync (and by `init`, from 1.1). A 1.0 or
//              older project has no record, but if its file hashes to one some
//              release shipped (`RELEASED_FRAMEWORK_HASHES`), it was never
//              edited and IS its own base.
//   • ours   — the project's file.
//   • theirs — the registry's, built the way `init` builds it.
//
// A token file with neither — edited before any baseline existed — cannot be
// merged honestly: there is no telling the user's edits from the old defaults.
// It gets the one change that is safe without that knowledge: the declarations
// the new token layer makes that the file does not, appended at zero
// specificity so they can never outrank anything already there. Every var() a
// component reads then resolves; every value the user chose stays. A base file
// in that state is left alone and reported.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { FaqirConfig } from "./config";
import { TOKEN_FILES_ORDERED } from "./bundler";
import { mergeFile, type FileMergeStatus } from "./merge";
import { RELEASED_FRAMEWORK_HASHES } from "./framework-history";
import { parseBlocks, type CssBlock } from "../theme/scope";

/** Schema id of `.faqir/pristine/framework/framework.json`. */
export const FRAMEWORK_PRISTINE_SCHEMA = "faqir-framework-pristine@1";

/** The banner `faqir init` opens the concatenated token layer with. */
export const COMBINED_TOKENS_HEADER = "/* Faqir Design Tokens — generated by faqir init */\n\n";

/** The base stylesheets `faqir init` copies, in bundle order. */
export const BASE_FILES = ["reset.css", "prose.css", "rhythm.css", "motion-presets.css"] as const;

/** One framework-owned file: its path under the output dir, and the registry's bytes. */
export interface FrameworkAsset {
  /** POSIX path relative to the output directory, e.g. `tokens/index.css`. */
  path: string;
  content: string;
}

/**
 * The concatenated token layer `faqir init` writes to `tokens/index.css` when
 * the tokens are not split: every token file in cascade order, `@import` lines
 * dropped. Byte-identical to init's output — it is the "theirs" side of the
 * merge, so any difference would read as an upstream change.
 */
export function combinedTokens(registryPath: string): string {
  let combined = COMBINED_TOKENS_HEADER;
  for (const file of TOKEN_FILES_ORDERED) {
    const path = join(registryPath, "tokens", file);
    if (!existsSync(path)) continue;
    combined +=
      readFileSync(path, "utf8")
        .split("\n")
        .filter((line) => !line.startsWith("@import"))
        .join("\n") + "\n";
  }
  return combined;
}

/** Every framework-owned file for a project laid out as `config` says, sorted by path. */
export function frameworkAssets(registryPath: string, config: Pick<FaqirConfig, "tokens_split">): FrameworkAsset[] {
  const assets: FrameworkAsset[] = [];
  const tokensDir = join(registryPath, "tokens");
  // A registry without a token layer (a test fixture, a components-only remote
  // mirror) has nothing to say about the project's — which is not the same as
  // saying "empty", so nothing is planned rather than an empty file.
  if (!existsSync(join(tokensDir, "index.css"))) {
    // fall through to the base styles
  } else if (config.tokens_split) {
    for (const file of readdirSync(tokensDir).sort()) {
      assets.push({ path: `tokens/${file}`, content: readFileSync(join(tokensDir, file), "utf8") });
    }
  } else {
    assets.push({ path: "tokens/index.css", content: combinedTokens(registryPath) });
    assets.push({ path: "tokens/imports.css", content: readFileSync(join(tokensDir, "index.css"), "utf8") });
  }
  for (const file of BASE_FILES) {
    const path = join(registryPath, "base", file);
    if (existsSync(path)) assets.push({ path: `base/${file}`, content: readFileSync(path, "utf8") });
  }
  return assets.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

// ── The baseline store ──────────────────────────────────────────────────────

interface FrameworkIndex {
  schema: string;
  /** path → sha256 of the bytes recorded under `files/<path>`. */
  files: Record<string, string>;
}

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function frameworkStoreRoot(cwd: string): string {
  return join(cwd, ".faqir", "pristine", "framework");
}

function readIndex(cwd: string): FrameworkIndex {
  const path = join(frameworkStoreRoot(cwd), "framework.json");
  try {
    const data = JSON.parse(readFileSync(path, "utf8"));
    if (data?.schema === FRAMEWORK_PRISTINE_SCHEMA && data.files && typeof data.files === "object") {
      return { schema: data.schema, files: data.files };
    }
  } catch {
    // Missing or corrupt: no baseline, exactly as for the component store.
  }
  return { schema: FRAMEWORK_PRISTINE_SCHEMA, files: {} };
}

/** The recorded baseline of each framework file, when its bytes still match their hash. */
export function readFrameworkBaseline(cwd: string): Map<string, string> {
  const out = new Map<string, string>();
  const root = frameworkStoreRoot(cwd);
  for (const [path, hash] of Object.entries(readIndex(cwd).files)) {
    const file = join(root, "files", ...path.split("/"));
    if (!existsSync(file)) continue;
    const text = readFileSync(file, "utf8");
    if (sha256(text) === hash) out.set(path, text);
  }
  return out;
}

/** Record (or replace) the baseline of the given files. */
export function saveFrameworkBaseline(cwd: string, assets: FrameworkAsset[]): void {
  if (assets.length === 0) return;
  const root = frameworkStoreRoot(cwd);
  const index = readIndex(cwd);
  for (const asset of assets) {
    const file = join(root, "files", ...asset.path.split("/"));
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, asset.content);
    index.files[asset.path] = sha256(asset.content);
  }
  const sorted = Object.fromEntries(Object.entries(index.files).sort(([a], [b]) => (a < b ? -1 : 1)));
  mkdirSync(root, { recursive: true });
  writeFileSync(join(root, "framework.json"), JSON.stringify({ schema: FRAMEWORK_PRISTINE_SCHEMA, files: sorted }, null, 2) + "\n");
}

/**
 * Record the registry's framework files as the project's baseline — what
 * `faqir init` should call right after it writes them, so a 1.1+ project never
 * depends on {@link RELEASED_FRAMEWORK_HASHES}.
 */
export function snapshotFrameworkBaseline(cwd: string, registryPath: string, config: Pick<FaqirConfig, "tokens_split">): void {
  saveFrameworkBaseline(cwd, frameworkAssets(registryPath, config));
}

/**
 * Did some release write exactly these bytes? The concatenated token layer is
 * compared without its first-line banner, which the 1.0 Node bundle wrote with
 * its em dash mangled.
 */
export function isReleasedFrameworkFile(path: string, content: string): boolean {
  const known = RELEASED_FRAMEWORK_HASHES[path];
  if (!known) return false;
  const body =
    path === "tokens/index.css" ? content.replace(/^\/\* (Faqir|Loom) Design Tokens [^\n]*\*\/\n/, "") : content;
  return known.includes(sha256(body));
}

// ── The additive merge (no baseline) ────────────────────────────────────────

interface Declaration {
  prop: string;
  text: string;
}

/** Split a block body into declarations at top-level `;`, respecting strings and parens. */
function splitDeclarations(body: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let quote: string | null = null;
  let start = 0;
  for (let i = 0; i < body.length; i++) {
    const c = body[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'") quote = c;
    else if (c === "(") depth++;
    else if (c === ")") depth--;
    else if (c === ";" && depth === 0) {
      out.push(body.slice(start, i));
      start = i + 1;
    }
  }
  out.push(body.slice(start));
  return out.map((d) => d.trim()).filter(Boolean);
}

/** A rule's custom-property declarations, keyed by its chain of preludes. */
interface CustomRule {
  chain: string[];
  decls: Declaration[];
}

function customRules(css: string): CustomRule[] {
  // Comments blanked with spaces so every offset parseBlocks returns still
  // indexes the same text.
  const source = css.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "));
  const out: CustomRule[] = [];
  const walk = (blocks: CssBlock[], chain: string[]) => {
    for (const block of blocks) {
      const prelude = unwrapWhere(block.prelude.trim().replace(/\s+/g, " "));
      if (block.children.length > 0) {
        walk(block.children, [...chain, prelude]);
        continue;
      }
      const decls = splitDeclarations(source.slice(block.braceAt + 1, block.closeAt))
        .map((text) => ({ prop: /^(--[\w-]+)\s*:/.exec(text)?.[1] ?? "", text }))
        .filter((d) => d.prop);
      if (decls.length > 0) out.push({ chain: [...chain, prelude], decls });
    }
  };
  walk(parseBlocks(source), []);
  return out;
}

/**
 * `:root` → `:where(:root)`, so an appended default never outranks what the
 * file (or a theme) already says. Two kinds of prelude keep their own weight:
 * an at-rule, which has none, and `[data-density]`, whose whole design is to
 * outrank `:root` at equal specificity by coming later.
 */
function zeroSpecificity(prelude: string): string {
  return prelude.startsWith("@") || prelude.startsWith("[data-density") ? prelude : `:where(${prelude})`;
}

/** The inverse, so a file that already carries an appended block is not appended to twice. */
function unwrapWhere(prelude: string): string {
  return /^:where\((.*)\)$/.exec(prelude)?.[1] ?? prelude;
}

/**
 * `ours` plus every custom-property declaration `theirs` makes that `ours`
 * does not make on the same selector — appended under `:where()`, so each is a
 * default that anything the file (or a theme, or density) already declares
 * outranks. Returns `ours` unchanged when nothing is missing.
 */
export function appendMissingDeclarations(ours: string, theirs: string, label: string): { content: string; added: string[] } {
  const have = new Set<string>();
  for (const rule of customRules(ours)) for (const d of rule.decls) have.add(`${rule.chain.join(" > ")}|${d.prop}`);

  const added: string[] = [];
  const blocks: string[] = [];
  for (const rule of customRules(theirs)) {
    const missing = rule.decls.filter((d) => !have.has(`${rule.chain.join(" > ")}|${d.prop}`));
    if (missing.length === 0) continue;
    for (const d of missing) {
      have.add(`${rule.chain.join(" > ")}|${d.prop}`);
      if (!added.includes(d.prop)) added.push(d.prop);
    }
    const render = (chain: string[], depth: number): string => {
      const indent = "  ".repeat(depth);
      const inner =
        chain.length === 1
          ? missing.map((d) => `${indent}  ${d.text};`).join("\n")
          : render(chain.slice(1), depth + 1);
      return `${indent}${zeroSpecificity(chain[0])} {\n${inner}\n${indent}}`;
    };
    blocks.push(render(rule.chain, 0));
  }
  if (blocks.length === 0) return { content: ours, added };

  const banner =
    `/* ── Added by \`faqir upgrade\` (${label}) ──\n` +
    `   Declarations this version of the token layer makes that this file did not.\n` +
    `   This file was edited before the upgrade kept a baseline, so it was not\n` +
    `   merged; everything above is exactly as it was. The rules below are\n` +
    `   :where()-wrapped — zero specificity — so none of them outranks a value\n` +
    `   above. To take the new token layer wholesale instead, delete this file and\n` +
    `   run \`faqir upgrade\` again. */\n`;
  return { content: `${ours}${ours.endsWith("\n") ? "" : "\n"}\n${banner}${blocks.join("\n\n")}\n`, added };
}

// ── The sync ────────────────────────────────────────────────────────────────

export type FrameworkFileStatus = FileMergeStatus | "appended" | "skipped";

export interface FrameworkFileReport {
  path: string;
  status: FrameworkFileStatus;
  conflicts: number;
  note?: string;
}

export interface FrameworkReport {
  files: FrameworkFileReport[];
  conflictedFiles: string[];
  /** True when a file was (or, in a dry run, would be) written or removed. */
  changed: boolean;
}

export interface SyncOptions {
  dryRun?: boolean;
  /** The version the registry is at — names the merge's "theirs" side. */
  version?: string;
}

/**
 * Bring every framework-owned file under `outputDir` up to the registry's.
 * Plans everything before writing anything, so a dry run is a faithful
 * preview. The theme is never touched.
 */
export function syncFramework(
  cwd: string,
  outputDir: string,
  registryPath: string,
  config: Pick<FaqirConfig, "tokens_split">,
  options: SyncOptions = {},
): FrameworkReport {
  const version = options.version ?? "registry";
  const baseline = readFrameworkBaseline(cwd);
  const files: FrameworkFileReport[] = [];
  const writes: Array<{ path: string; content: string | null }> = [];
  const record: FrameworkAsset[] = [];

  for (const asset of frameworkAssets(registryPath, config)) {
    const dest = join(outputDir, ...asset.path.split("/"));
    const ours = existsSync(dest) ? readFileSync(dest, "utf8") : null;
    const recorded = baseline.get(asset.path) ?? null;
    const base = recorded ?? (ours !== null && isReleasedFrameworkFile(asset.path, ours) ? ours : null);

    if (base === null && ours !== null && ours !== asset.content) {
      // Edited, and nothing to tell the edits from the old defaults.
      if (asset.path.startsWith("tokens/") && asset.path.endsWith(".css")) {
        const { content, added } = appendMissingDeclarations(ours, asset.content, version);
        if (added.length > 0) {
          writes.push({ path: asset.path, content });
          files.push({
            path: asset.path,
            status: "appended",
            conflicts: 0,
            note: `edited before a baseline existed — kept, with ${added.length} missing declaration(s) appended`,
          });
        } else {
          files.push({ path: asset.path, status: "unchanged", conflicts: 0, note: "edited; already declares every token" });
        }
      } else {
        files.push({
          path: asset.path,
          status: "skipped",
          conflicts: 0,
          note: "edited before a baseline existed — left as is; compare it with the registry's copy by hand",
        });
      }
      continue;
    }

    const outcome = mergeFile(
      { path: asset.path, base, ours, theirs: asset.content },
      { oursLabel: "ours", baseLabel: "base (installed)", theirsLabel: `theirs (${version})` },
    );
    files.push({ path: asset.path, status: outcome.status, conflicts: outcome.conflicts, note: outcome.note });
    if (outcome.action === "write") writes.push({ path: asset.path, content: outcome.content ?? "" });
    else if (outcome.action === "delete") writes.push({ path: asset.path, content: null });
    // The baseline advances to the registry's bytes whatever the outcome —
    // the user's edits live in their copy (or its conflict markers), exactly
    // as for a component.
    record.push(asset);
  }

  if (!options.dryRun) {
    for (const write of writes) {
      const dest = join(outputDir, ...write.path.split("/"));
      if (write.content === null) {
        rmSync(dest, { force: true });
      } else {
        mkdirSync(dirname(dest), { recursive: true });
        writeFileSync(dest, write.content);
      }
    }
    saveFrameworkBaseline(cwd, record);
  }

  const conflictedFiles = files.filter((f) => f.status === "conflict").map((f) => f.path);
  return { files, conflictedFiles, changed: writes.length > 0 };
}

// ── Coverage: does the token layer define what the components read? ────────

/**
 * Every custom property `css` reads that nothing defines and nothing catches.
 *
 * A `var(--x, fallback)` whose `--x` is undefined renders its fallback, so the
 * fallback is checked in its place; one whose `--x` IS defined never renders
 * its fallback, so that is skipped. Unlike the audit's regex extractor this
 * follows nested fallbacks, which is where 1.1 put its role tokens
 * (`var(--input-font, var(--font-ui))`).
 */
export function unresolvedReferences(css: string, defined: ReadonlySet<string>): string[] {
  const source = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const out = new Set<string>();
  const visit = (start: number, end: number): void => {
    let i = start;
    while (i < end) {
      const at = source.indexOf("var(", i);
      if (at === -1 || at >= end) return;
      if (at > 0 && /[\w-]/.test(source[at - 1])) {
        i = at + 4;
        continue;
      }
      const name = /^\s*(--[\w-]+)/.exec(source.slice(at + 4, end))?.[1];
      // The matching `)`, and the first top-level `,` before it.
      let depth = 0;
      let close = -1;
      let comma = -1;
      for (let j = at + 3; j < end; j++) {
        const c = source[j];
        if (c === "(") depth++;
        else if (c === ")" && --depth === 0) {
          close = j;
          break;
        } else if (c === "," && depth === 1 && comma < 0) comma = j;
      }
      if (close < 0) return;
      if (name && !defined.has(name)) {
        if (comma < 0) out.add(name);
        else visit(comma + 1, close);
      }
      i = close + 1;
    }
  };
  visit(0, source.length);
  return [...out].sort();
}

/** Every custom property declared anywhere in `css`. */
export function declaredProperties(css: string): Set<string> {
  const out = new Set<string>();
  for (const m of css.replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/(--[\w-]+)\s*:/g)) out.add(m[1]);
  return out;
}

/**
 * The custom properties a project's token layer, theme and fonts define —
 * every stylesheet directly under `tokens/`, plus `fonts.css`.
 */
export function projectDefinedTokens(outputDir: string): Set<string> {
  const defined = new Set<string>();
  const tokensDir = join(outputDir, "tokens");
  const sheets = existsSync(tokensDir)
    ? readdirSync(tokensDir).filter((f) => f.endsWith(".css")).map((f) => join(tokensDir, f))
    : [];
  sheets.push(join(outputDir, "fonts.css"));
  for (const sheet of sheets) {
    if (existsSync(sheet)) for (const prop of declaredProperties(readFileSync(sheet, "utf8"))) defined.add(prop);
  }
  return defined;
}

export interface MissingToken {
  token: string;
  /** Output-dir-relative stylesheets that read it. */
  readBy: string[];
}

/**
 * The tokens the given stylesheets (output-dir-relative paths) read that the
 * project's token layer does not define. A stylesheet's own declarations — a
 * component knob on its root — count as defined for that stylesheet.
 */
export function missingTokens(outputDir: string, stylesheets: string[]): MissingToken[] {
  const defined = projectDefinedTokens(outputDir);
  const readBy = new Map<string, string[]>();
  for (const rel of stylesheets) {
    const path = join(outputDir, ...rel.split("/"));
    if (!existsSync(path)) continue;
    const css = readFileSync(path, "utf8");
    const local = new Set([...defined, ...declaredProperties(css)]);
    for (const token of unresolvedReferences(css, local)) readBy.set(token, [...(readBy.get(token) ?? []), rel]);
  }
  return [...readBy.entries()]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([token, by]) => ({ token, readBy: by }));
}

/** Output-dir-relative stylesheet of every installed component, plus the base styles. */
export function installedStylesheets(config: Pick<FaqirConfig, "installed">, outputDir: string): string[] {
  const out: string[] = [];
  for (const layer of ["primitives", "recipes", "patterns"] as const) {
    for (const name of config.installed[layer]) out.push(`${layer}/${name}/${name}.css`);
  }
  for (const file of BASE_FILES) if (existsSync(join(outputDir, "base", file))) out.push(`base/${file}`);
  return out;
}
