// Icon subsetting (task 0.4-05 · §B4).
//
// The `icon` primitive ships a full `icons.css` (~46 KB, 120 Lucide glyphs) plus
// a machine-enumerable `icon.manifest.json`. `faqir add icons --only …` trims
// those to just the glyphs a project uses. Everything here is a pure function of
// the shipped registry artifacts (the CLI package does NOT ship the SVG sources
// or the build script), so subsetting works from the installed CLI alone.
//
// The full `icons.css` is deterministically generated by scripts/build-icons.mjs
// with this exact shape:
//
//   /* @ui:component icon */                    ┐
//   /* @ui:tokens */ /* … */                    │ header banner
//   /* Generated … */                           │
//   /* Icons: Lucide (ISC) · … */               ┘
//
//   /* ── Base ── */
//   [data-ui="icon"] { … }                      ← base rule (mask/currentColor/1em)
//
//   /* ── Glyphs (120) ── */
//   [data-icon="activity"] { --icon: url("…"); } ← one line per glyph
//   …
//
// We split on the "Glyphs" marker: everything before it (header + base rule) is
// preserved verbatim, and we re-emit only the requested glyph lines, so a subset
// sheet is byte-for-byte the full sheet with unused glyph rules removed.

import { suggestClosest } from "./suggest";

const GLYPHS_MARKER = "/* ── Glyphs";
const BASE_MARKER = "/* ── Base ── */";
const BASE_SELECTOR = '[data-ui="icon"]';
const GLYPH_LINE_RE = /^\[data-icon="([^"]+)"\]\s*\{/;

// Lean header for a CLI-emitted subset sheet. Keeps the `@ui:*` tooling markers
// and the required Lucide/ISC attribution (with the LICENSE.lucide pointer) but
// drops the verbose "generated by scripts/build-icons.mjs" banner — a few
// hundred bytes that matter when the whole point is a small sheet.
const SUBSET_HEADER = [
  "/* @ui:component icon */",
  "/* @ui:tokens */ /* none — icons inherit color (currentColor) and size (1em) from context */",
  "/* Icon subset generated by `faqir add icons`. Icons: Lucide (ISC) · attribution: LICENSE.lucide */",
].join("\n");

export interface ParsedIconsCss {
  /** The base rule block (the "Base" comment marker plus the `[data-ui="icon"]` rule), verbatim. */
  base: string;
  /** name → the full `[data-icon="…"] { --icon: url("…"); }` rule line, verbatim. */
  glyphs: Map<string, string>;
}

/**
 * Split a generated `icons.css` into its base-rule block and a name → rule map.
 * Handles both the verbose full sheet and a previously-emitted subset sheet
 * (only the header differs; the base marker + glyph lines are identical). Throws
 * if the sheet lacks the generated structure, so a hand-mangled file fails
 * loudly rather than silently producing an empty subset.
 */
export function parseIconsCss(css: string): ParsedIconsCss {
  const glyphsIdx = css.indexOf(GLYPHS_MARKER);
  if (glyphsIdx === -1) {
    throw new Error(`icons.css is missing the "${GLYPHS_MARKER} …" section — is it a generated icon sheet?`);
  }

  const baseIdx = css.indexOf(BASE_MARKER);
  const baseStart = baseIdx !== -1 ? baseIdx : css.indexOf(BASE_SELECTOR);
  if (baseStart === -1 || baseStart >= glyphsIdx) {
    throw new Error(`icons.css is missing the [data-ui="icon"] base rule — is it a generated icon sheet?`);
  }
  const base = css.slice(baseStart, glyphsIdx).trimEnd();

  const glyphs = new Map<string, string>();
  for (const raw of css.slice(glyphsIdx).split("\n")) {
    const line = raw.replace(/\r$/, "");
    const match = line.match(GLYPH_LINE_RE);
    if (match) glyphs.set(match[1], line);
  }

  if (glyphs.size === 0) {
    throw new Error(`icons.css contains no [data-icon="…"] rules — is it a generated icon sheet?`);
  }
  return { base, glyphs };
}

/** Every glyph name present in a generated `icons.css`, sorted. */
export function iconNamesFromCss(css: string): string[] {
  return [...parseIconsCss(css).glyphs.keys()].sort();
}

/** Sorted, de-duplicated copy of `names`. */
function normalizeNames(names: string[]): string[] {
  return [...new Set(names)].sort();
}

/**
 * Emit a trimmed `icons.css` holding only `names` (plus the base rule + header),
 * reusing the full sheet's glyph rules verbatim. `names` are sorted and
 * de-duplicated; every name must exist in `fullCss` (validate first with
 * {@link validateIconNames}). Output matches the generated sheet's format, so a
 * subset re-parses cleanly (enabling merge-on-re-run) and audits identically.
 */
export function subsetIconsCss(fullCss: string, names: string[]): string {
  const { base, glyphs } = parseIconsCss(fullCss);
  const wanted = normalizeNames(names);

  const missing = wanted.filter((n) => !glyphs.has(n));
  if (missing.length > 0) {
    throw new Error(`subsetIconsCss: unknown icon name(s): ${missing.join(", ")}`);
  }

  const glyphLines = wanted.map((n) => glyphs.get(n)!);
  const glyphSection = [`${GLYPHS_MARKER} (${wanted.length}) ── */`, ...glyphLines].join("\n");
  return `${SUBSET_HEADER}\n\n${base}\n\n${glyphSection}\n`;
}

/**
 * Trim a parsed `icon.manifest.json` to `names`: rewrite the enumerated icon
 * name lists (`variants.icon.values`, `props.name.values`) and `icon_set.count`,
 * and re-point any `default` that fell outside the subset to the first kept name
 * so the manifest invariant `values.includes(default)` still holds. Operates on
 * a deep clone — the input object is not mutated.
 */
export function subsetIconManifest(fullManifest: Record<string, any>, names: string[]): Record<string, any> {
  const wanted = normalizeNames(names);
  if (wanted.length === 0) throw new Error("subsetIconManifest: at least one icon name is required");

  const manifest = structuredClone(fullManifest);
  const keepDefault = (current: unknown): string =>
    typeof current === "string" && wanted.includes(current) ? current : wanted[0];

  if (manifest.variants?.icon) {
    manifest.variants.icon.values = [...wanted];
    manifest.variants.icon.default = keepDefault(manifest.variants.icon.default);
  }
  if (manifest.props?.name) {
    manifest.props.name.values = [...wanted];
    manifest.props.name.default = keepDefault(manifest.props.name.default);
  }
  if (manifest.icon_set) {
    manifest.icon_set.count = wanted.length;
  }
  return manifest;
}

/** Provenance fields read off the full manifest's `icon_set` for the reference page. */
export interface IconSetInfo {
  license?: string;
}

/**
 * Reference page for a subset install: the requested glyphs as labeled
 * `[data-ui="icon"]` cells, colored by `currentColor`. Mirrors the registry
 * reference page's audit-clean markup (rem/token values only, no hardcoded px or
 * colors) so `faqir audit` stays quiet. `names` are sorted for stable output.
 */
export function buildSubsetReferenceHtml(names: string[], iconSet: IconSetInfo = {}): string {
  const wanted = normalizeNames(names);
  const license = iconSet.license ?? "ISC";
  const variantsComment = `<!-- @ui:variants icon=${wanted.join("|")} -->`;
  const cells = wanted
    .map(
      (n) =>
        `  <figure style="display:flex; flex-direction:column; align-items:center; gap:0.5rem; margin:0; padding:0.75rem; text-align:center">\n` +
        `    <span data-ui="icon" data-icon="${n}" role="img" aria-label="${n}" style="font-size:1.5rem"></span>\n` +
        `    <figcaption style="font-size:0.75rem; color:var(--color-fg-muted)">${n}</figcaption>\n` +
        `  </figure>`,
    )
    .join("\n");

  return (
    `<!-- @ui:component icon -->\n` +
    `<!-- @ui:kind primitive -->\n` +
    `<!-- @ui:slots -->\n` +
    `${variantsComment}\n` +
    `<!-- Generated by \`faqir add icons\` — a subset of ${wanted.length} icon(s). -->\n` +
    `<!-- Every glyph is a CSS mask colored by currentColor; set color/font-size on an ancestor to restyle. -->\n\n` +
    `<section aria-label="Faqir icon set" style="color:var(--color-fg)">\n` +
    `  <p style="font-size:0.875rem; color:var(--color-fg-muted)">${wanted.length} icons · Lucide (${license}) · rendered from CSS alone · colored by currentColor</p>\n` +
    `  <div style="display:grid; grid-template-columns:repeat(auto-fill, minmax(6rem, 1fr)); gap:0.5rem">\n` +
    `${cells}\n` +
    `  </div>\n` +
    `</section>\n`
  );
}

export interface UnknownIcon {
  name: string;
  /** Nearest catalog name within edit distance 3, or null when nothing is close. */
  suggestion: string | null;
}

export interface IconNameValidation {
  /** Requested names that exist in the catalog (sorted, de-duplicated). */
  valid: string[];
  /** Requested names not in the catalog, each with a nearest-match hint. */
  unknown: UnknownIcon[];
}

/**
 * Partition requested icon names against the available catalog. Unknown names
 * carry a nearest-match suggestion (reusing the CLI's shared typo-suggestion
 * util) so callers can say "did you mean check?".
 */
export function validateIconNames(requested: string[], catalog: Iterable<string>): IconNameValidation {
  const catalogArr = [...catalog];
  const catalogSet = new Set(catalogArr);
  const valid: string[] = [];
  const unknown: UnknownIcon[] = [];

  for (const name of normalizeNames(requested)) {
    if (catalogSet.has(name)) {
      valid.push(name);
    } else {
      unknown.push({ name, suggestion: suggestClosest(name, catalogArr, 3) });
    }
  }
  return { valid, unknown };
}
