import { readdir } from "node:fs/promises";

import type { LoomConfig } from "./config";
import { ensureDir, fileExists, readTextFile, writeTextFile } from "./fs";
import { resolvePackagePath, resolveRegistryPath } from "./paths";

export const TOKEN_FILES = [
  "palette.css",
  "semantic.css",
  "aliases.css",
  "spacing.css",
  "typography.css",
  "effects.css",
  "motion.css",
] as const;

const THEME_TOKEN_LINES = [
  "--color-bg",
  "--color-bg-subtle",
  "--color-bg-muted",
  "--color-bg-elevated",
  "--color-fg",
  "--color-fg-muted",
  "--color-fg-subtle",
  "--color-link",
  "--color-primary",
  "--color-primary-hover",
  "--color-primary-active",
  "--color-primary-fg",
  "--color-primary-subtle",
  "--color-secondary",
  "--color-secondary-hover",
  "--color-secondary-active",
  "--color-secondary-fg",
  "--color-destructive",
  "--color-destructive-hover",
  "--color-destructive-fg",
  "--color-destructive-subtle",
  "--color-success",
  "--color-success-subtle",
  "--color-warning",
  "--color-warning-subtle",
  "--color-border",
  "--color-border-strong",
  "--color-ring",
  "--color-overlay",
  "--shadow-xs",
  "--shadow-sm",
  "--shadow-md",
  "--shadow-lg",
  "--shadow-xl",
  "--button-radius",
  "--input-radius",
  "--card-radius",
  "--dialog-radius",
  "--surface-radius",
] as const;

export type ThemeRecord = {
  name: string;
  source: "built-in" | "project";
};

export async function listThemeRecords(projectRoot?: string, config?: LoomConfig): Promise<ThemeRecord[]> {
  const builtIn = await listBuiltInThemeNames();
  const records = builtIn.map((name) => ({ name, source: "built-in" as const }));

  if (!projectRoot || !config) {
    return records;
  }

  const projectNames = await listProjectThemeNames(projectRoot, config);

  for (const name of projectNames) {
    const existingIndex = records.findIndex((record) => record.name === name);

    if (existingIndex >= 0) {
      records[existingIndex] = { name, source: "project" };
      continue;
    }

    records.push({ name, source: "project" });
  }

  return records.sort((left, right) => left.name.localeCompare(right.name));
}

export async function resolveThemeCss(
  projectRoot: string,
  config: LoomConfig,
  themeName: string,
): Promise<string> {
  const projectThemePath = getProjectThemePath(projectRoot, config, themeName);

  if (await fileExists(projectThemePath)) {
    return await readTextFile(projectThemePath);
  }

  const registryThemePath = resolveRegistryPath("themes", `${themeName}.css`);

  if (await fileExists(registryThemePath)) {
    return await readTextFile(registryThemePath);
  }

  throw new Error(`Unknown theme: ${themeName}`);
}

export async function syncProjectTokens(projectRoot: string, config: LoomConfig): Promise<void> {
  const outputRoot = resolvePackagePath(projectRoot, config.output_dir);
  const tokensDir = resolvePackagePath(outputRoot, "tokens");
  const tokenContents = await Promise.all(
    TOKEN_FILES.map(async (fileName) => ({
      fileName,
      content: await readTextFile(resolveRegistryPath("tokens", fileName)),
    })),
  );
  const themeCss = await resolveThemeCss(projectRoot, config, config.theme);

  if (config.tokens_split) {
    for (const tokenFile of tokenContents) {
      await writeTextFile(resolvePackagePath(tokensDir, tokenFile.fileName), tokenFile.content);
    }

    await writeTextFile(resolvePackagePath(tokensDir, "index.css"), buildSplitTokenIndex());
    await writeTextFile(resolvePackagePath(tokensDir, "theme.css"), themeCss);
    return;
  }

  await writeTextFile(resolvePackagePath(tokensDir, "index.css"), buildBundledTokens(tokenContents, themeCss));
}

export async function writeProjectThemeTemplate(
  projectRoot: string,
  config: LoomConfig,
  themeName: string,
): Promise<string> {
  const path = getProjectThemePath(projectRoot, config, themeName);
  await ensureDir(resolvePackagePath(projectRoot, config.output_dir, "themes"));
  await writeTextFile(path, buildThemeTemplate(themeName));
  return path;
}

export function getProjectThemePath(projectRoot: string, config: LoomConfig, themeName: string): string {
  return resolvePackagePath(projectRoot, config.output_dir, "themes", `${themeName}.css`);
}

function buildSplitTokenIndex(): string {
  return [
    "/* Generated by loom init */",
    ...TOKEN_FILES.map((fileName) => `@import "./${fileName}";`),
    '@import "./theme.css";',
    "",
  ].join("\n");
}

function buildBundledTokens(
  tokenContents: Array<{ fileName: string; content: string }>,
  themeCss: string,
): string {
  return [
    "/* Generated by loom init */",
    ...tokenContents.map(({ fileName, content }) => `${banner(fileName)}\n${content}`),
    `${banner("theme.css")}\n${themeCss}`,
    "",
  ].join("\n\n");
}

function buildThemeTemplate(themeName: string): string {
  return [
    `/* @ui:component theme-${themeName} */`,
    "",
    ":root {",
    "  color-scheme: light;",
    ...THEME_TOKEN_LINES.map((token) => `  /* ${token}: ; */`),
    "}",
    "",
  ].join("\n");
}

async function listBuiltInThemeNames(): Promise<string[]> {
  const entries = await readdir(resolveRegistryPath("themes"), { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".css"))
    .map((entry) => entry.name.replace(/\.css$/, ""))
    .sort((left, right) => left.localeCompare(right));
}

async function listProjectThemeNames(projectRoot: string, config: LoomConfig): Promise<string[]> {
  const themesDir = resolvePackagePath(projectRoot, config.output_dir, "themes");

  if (!(await fileExists(themesDir))) {
    return [];
  }

  const entries = await readdir(themesDir, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".css"))
    .map((entry) => entry.name.replace(/\.css$/, ""))
    .sort((left, right) => left.localeCompare(right));
}

function banner(fileName: string): string {
  return `/* Source: ${fileName} */`;
}
