// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/backdrop/backdrop.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime.js";

/** Allowed `variant` values (manifest variant group "scene", attr `data-variant`). */
export type LBackdropVariant = "aurora" | "spotlight" | "grid" | "dots" | "beams";

/** Allowed `intensity` values (manifest variant group "intensity", attr `data-intensity`). */
export type LBackdropIntensity = "subtle" | "normal" | "vivid";

export interface LBackdropProps {
  /** `data-variant`; omitted when unset (manifest default: "aurora"). */
  variant?: LBackdropVariant;
  /** `data-intensity`; omitted when unset (manifest default: "normal"). */
  intensity?: LBackdropIntensity;
  /** Keep the light and stop the movement. Use it for a second backdrop on the same screen, or wherever motion would compete with the content. */
  static?: boolean;
}

/** `backdrop` — Ambient animated light behind a section — aurora, spotlight, grid, dots or beams — painted by the wrapper's own pseudo-elements, so there is no decorative element to hide and nothing to position. Colours come from the theme's accent, info and success; pure CSS, still under reduced motion, gone in forced colours and print. */
export const LBackdrop = defineFaqirPrimitive<LBackdropProps>({
  name: "backdrop",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["aurora", "spotlight", "grid", "dots", "beams"] },
    { prop: "intensity", attr: "data-intensity", values: ["subtle", "normal", "vivid"] },
  ],
  states: [
    { prop: "static", attr: "data-static", value: null, kind: "presence" },
  ],
  slots: [],
  defaultSlot: true,
});

export default LBackdrop;
