// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/badge/badge.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime.js";

/** Allowed `variant` values (manifest variant group "visual", attr `data-variant`). */
export type LBadgeVariant = "default" | "primary" | "secondary" | "destructive" | "success" | "warning";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LBadgeSize = "sm" | "md" | "lg";

export interface LBadgeProps {
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LBadgeVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LBadgeSize;
  /** A breathing dot before the text, in the variant colour — a status that is happening now (Live, Online, Recording). */
  live?: boolean;
}

/** `badge` — Small status indicator with color variants */
export const LBadge = defineFaqirPrimitive<LBadgeProps>({
  name: "badge",
  tag: "span",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["default", "primary", "secondary", "destructive", "success", "warning"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [
    { prop: "live", attr: "data-live", value: null, kind: "presence" },
  ],
  slots: [],
  defaultSlot: true,
});

export default LBadge;
