// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/breadcrumb/breadcrumb.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LBreadcrumbSize = "sm" | "md" | "lg";

export interface LBreadcrumbProps {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LBreadcrumbSize;
}

/** `breadcrumb` — Breadcrumb trail — a <nav aria-label="Breadcrumb"> with link items, presentational separators, and the current page marked aria-current="page" */
export const LBreadcrumb = defineFaqirPrimitive<LBreadcrumbProps>({
  name: "breadcrumb",
  tag: "nav",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "list", tag: "ol", required: false, isVoid: false },
    { name: "item", tag: "a", required: false, isVoid: false },
    { name: "separator", tag: "li", required: false, isVoid: false },
    { name: "current", tag: "span", required: true, isVoid: false },
  ],
  defaultSlot: false,
});

export default LBreadcrumb;
