// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/callout/callout.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LCalloutVariant = "info" | "warning" | "destructive" | "success" | "muted";

export interface LCalloutProps {
  /** `data-variant`; omitted when unset (manifest default: "info"). */
  variant?: LCalloutVariant;
}

/** `callout` — Callout box for info notices, warnings, alerts, legal text, and disclaimers */
export const LCallout = defineFaqirPrimitive<LCalloutProps>({
  name: "callout",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["info", "warning", "destructive", "success", "muted"] },
  ],
  states: [],
  slots: [
    { name: "icon", tag: "span", required: false, isVoid: false },
    { name: "content", tag: "div", required: true, isVoid: false },
    { name: "title", tag: "strong", required: false, isVoid: false },
    { name: "dismiss", tag: "button", required: false, isVoid: false },
  ],
  defaultSlot: false,
});

export default LCallout;
