// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/chip/chip.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "visual", attr `data-variant`). */
export type LChipVariant = "default" | "primary" | "outline" | "destructive";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LChipSize = "sm" | "md" | "lg";

export interface LChipProps {
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LChipVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LChipSize;
}

/** `chip` — Tag/chip with a label and an optional dismiss button */
export const LChip = defineFaqirPrimitive<LChipProps>({
  name: "chip",
  tag: "span",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["default", "primary", "outline", "destructive"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "label", tag: "span", required: true, isVoid: false },
    { name: "dismiss", tag: "button", required: false, isVoid: false },
  ],
  defaultSlot: false,
});

export default LChip;
