// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/kbd/kbd.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

export interface LKbdProps {
}

/** `kbd` — Inline keyboard shortcut key indicator */
export const LKbd = defineFaqirPrimitive<LKbdProps>({
  name: "kbd",
  tag: "kbd",
  variants: [],
  states: [],
  slots: [],
  defaultSlot: true,
});

export default LKbd;
