// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/key-value/key-value.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LKeyValueVariant = "horizontal" | "vertical" | "inline";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LKeyValueSize = "sm" | "md" | "lg";

export interface LKeyValueProps {
  /** `data-variant`; omitted when unset (manifest default: "horizontal"). */
  variant?: LKeyValueVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LKeyValueSize;
}

/** `key-value` — Labeled data pair for displaying key-value information */
export const LKeyValue = defineFaqirPrimitive<LKeyValueProps>({
  name: "key-value",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["horizontal", "vertical", "inline"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "label", tag: "dt", required: true, isVoid: false },
    { name: "value", tag: "dd", required: true, isVoid: false },
  ],
  defaultSlot: false,
});

export default LKeyValue;
