// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/progress/progress.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LProgressVariant = "default" | "success" | "warning" | "destructive";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LProgressSize = "sm" | "md" | "lg";

export interface LProgressProps {
  /** `data-variant`; omitted when unset (manifest default: "default"). */
  variant?: LProgressVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LProgressSize;
}

/** `progress` — Progress bar with animated fill, color variants, and optional label */
export const LProgress = defineFaqirPrimitive<LProgressProps>({
  name: "progress",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["default", "success", "warning", "destructive"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "track", tag: "div", required: true, isVoid: false },
    { name: "fill", tag: "div", required: true, isVoid: false },
    { name: "label", tag: "span", required: false, isVoid: false },
  ],
  defaultSlot: false,
});

export default LProgress;
