// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/reveal/reveal.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime.js";

/** Allowed `variant` values (manifest variant group "effect", attr `data-variant`). */
export type LRevealVariant = "fade" | "rise" | "fall" | "slide-start" | "slide-end" | "zoom" | "blur";

/** Allowed `trigger` values (manifest variant group "trigger", attr `data-trigger`). */
export type LRevealTrigger = "load" | "scroll";

export interface LRevealProps {
  /** `data-variant`; omitted when unset (manifest default: "rise"). */
  variant?: LRevealVariant;
  /** `data-trigger`; omitted when unset (manifest default: "load"). */
  trigger?: LRevealTrigger;
  /** Sets `data-state="hidden"`. */
  hidden?: boolean;
  /** Sets `data-state="shown"`. */
  shown?: boolean;
  /** Move the entrance from the root to its direct children: each child arrives --motion-stagger after the sibling before it. Twelve steps are counted; children past the twelfth arrive with it. */
  stagger?: boolean;
}

/** `reveal` — Entrance choreography for any content: seven effects, three triggers (on load, scrubbed by scroll, or released by a state), and a staggered mode that brings a group's children in one after another. Pure CSS — a view timeline where supported, a load entrance where not — and every distance, duration and easing is a motion token a theme can re-point. */
export const LReveal = defineFaqirPrimitive<LRevealProps>({
  name: "reveal",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["fade", "rise", "fall", "slide-start", "slide-end", "zoom", "blur"] },
    { prop: "trigger", attr: "data-trigger", values: ["load", "scroll"] },
  ],
  states: [
    { prop: "hidden", attr: "data-state", value: "hidden", kind: "value" },
    { prop: "shown", attr: "data-state", value: "shown", kind: "value" },
    { prop: "stagger", attr: "data-stagger", value: null, kind: "presence" },
  ],
  slots: [],
  defaultSlot: true,
});

export default LReveal;
