// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/skeleton/skeleton.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "shape", attr `data-variant`). */
export type LSkeletonVariant = "text" | "circle" | "rect";

export interface LSkeletonProps {
  /** `data-variant`; omitted when unset (manifest default: "text"). */
  variant?: LSkeletonVariant;
}

/** `skeleton` — Loading placeholder with text/circle/rect variants and a shimmer animation that respects prefers-reduced-motion */
export const LSkeleton = defineFaqirPrimitive<LSkeletonProps>({
  name: "skeleton",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["text", "circle", "rect"] },
  ],
  states: [],
  slots: [],
  defaultSlot: true,
});

export default LSkeleton;
