// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/spinner/spinner.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LSpinnerSize = "sm" | "md" | "lg" | "xl";

export interface LSpinnerProps {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LSpinnerSize;
}

/** `spinner` — Circular loading spinner with multiple sizes */
export const LSpinner = defineFaqirPrimitive<LSpinnerProps>({
  name: "spinner",
  tag: "div",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg", "xl"] },
  ],
  states: [],
  slots: [],
  defaultSlot: false,
});

export default LSpinner;
