// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/stack/stack.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "direction", attr `data-variant`). */
export type LStackVariant = "vertical" | "horizontal";

/** Allowed `gap` values (manifest variant group "gap", attr `data-gap`). */
export type LStackGap = "0" | "1" | "2" | "3" | "4" | "6" | "8";

/** Allowed `align` values (manifest variant group "align", attr `data-align`). */
export type LStackAlign = "start" | "center" | "end" | "stretch";

export interface LStackProps {
  /** `data-variant`; omitted when unset (manifest default: "vertical"). */
  variant?: LStackVariant;
  /** `data-gap`; omitted when unset (manifest default: "0"). */
  gap?: LStackGap;
  /** `data-align`; omitted when unset (manifest default: "stretch"). */
  align?: LStackAlign;
}

/** `stack` — Flexbox layout container for vertical or horizontal stacking with configurable gap and alignment */
export const LStack = defineFaqirPrimitive<LStackProps>({
  name: "stack",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["vertical", "horizontal"] },
    { prop: "gap", attr: "data-gap", values: ["0", "1", "2", "3", "4", "6", "8"] },
    { prop: "align", attr: "data-align", values: ["start", "center", "end", "stretch"] },
  ],
  states: [],
  slots: [],
  defaultSlot: true,
});

export default LStack;
