// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/stepper/stepper.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "variant", attr `data-variant`). */
export type LStepperVariant = "horizontal" | "vertical";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LStepperSize = "sm" | "md" | "lg";

export interface LStepperProps {
  /** `data-variant`; omitted when unset (manifest default: "horizontal"). */
  variant?: LStepperVariant;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LStepperSize;
}

/** `stepper` — Step indicator with numbered circles, connectors, and labels for multi-step flows */
export const LStepper = defineFaqirPrimitive<LStepperProps>({
  name: "stepper",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["horizontal", "vertical"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [],
  slots: [
    { name: "step", tag: "div", required: true, isVoid: false },
    { name: "indicator", tag: "span", required: true, isVoid: false },
    { name: "label", tag: "span", required: false, isVoid: false },
    { name: "connector", tag: "div", required: false, isVoid: false },
  ],
  defaultSlot: false,
});

export default LStepper;
