// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/textarea/textarea.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LTextareaSize = "sm" | "md" | "lg";

export interface LTextareaProps {
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LTextareaSize;
  /** Sets `data-state="error"`. */
  error?: boolean;
  /** Sets the `disabled` attribute. */
  disabled?: boolean;
}

/** `textarea` — Multi-line text input with error, disabled states and size variants */
export const LTextarea = defineFaqirPrimitive<LTextareaProps>({
  name: "textarea",
  tag: "textarea",
  variants: [
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
  ],
  states: [
    { prop: "error", attr: "data-state", value: "error", kind: "value" },
    { prop: "disabled", attr: "disabled", value: null, kind: "presence" },
  ],
  slots: [],
  defaultSlot: true,
});

export default LTextarea;
