// AUTO-GENERATED by `faqir bindings vue` from registry/primitives/watermark/watermark.manifest.json.
// Do not edit — regenerate with `faqir bindings vue`.

import { defineFaqirPrimitive } from "../runtime";

/** Allowed `variant` values (manifest variant group "position", attr `data-variant`). */
export type LWatermarkVariant = "fixed" | "absolute";

/** Allowed `pattern` values (manifest variant group "pattern", attr `data-pattern`). */
export type LWatermarkPattern = "single" | "repeated";

/** Allowed `size` values (manifest variant group "size", attr `data-size`). */
export type LWatermarkSize = "sm" | "md" | "lg";

/** Allowed `orientation` values (manifest variant group "orientation", attr `data-orientation`). */
export type LWatermarkOrientation = "diagonal" | "horizontal";

export interface LWatermarkProps {
  /** `data-variant`; omitted when unset (manifest default: "fixed"). */
  variant?: LWatermarkVariant;
  /** `data-pattern`; omitted when unset (manifest default: "single"). */
  pattern?: LWatermarkPattern;
  /** `data-size`; omitted when unset (manifest default: "md"). */
  size?: LWatermarkSize;
  /** `data-orientation`; omitted when unset (manifest default: "diagonal"). */
  orientation?: LWatermarkOrientation;
}

/** `watermark` — Non-interactive diagonal text overlay with single or repeated print-safe layouts */
export const LWatermark = defineFaqirPrimitive<LWatermarkProps>({
  name: "watermark",
  tag: "div",
  variants: [
    { prop: "variant", attr: "data-variant", values: ["fixed", "absolute"] },
    { prop: "pattern", attr: "data-pattern", values: ["single", "repeated"] },
    { prop: "size", attr: "data-size", values: ["sm", "md", "lg"] },
    { prop: "orientation", attr: "data-orientation", values: ["diagonal", "horizontal"] },
  ],
  states: [],
  slots: [
    { name: "mark", tag: "span", required: true, isVoid: false },
  ],
  defaultSlot: false,
});

export default LWatermark;
