// AUTO-GENERATED by `faqir bindings react` from registry/recipes/alert-dialog/alert-dialog.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createAlertDialog } from "../controllers/alert-dialog";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LAlertDialogSize = "sm" | "md";

/** Allowed `tone` values (manifest variant group "tone", attr `data-variant` on panel). */
export type LAlertDialogTone = "default" | "destructive";

export interface LAlertDialogProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "cancelText" | "confirmText" | "description" | "title" | "confirmRequired" | "size" | "tone" | "trigger" | "overlay" | "panel" | "header" | "body" | "footer" | "cancel" | "confirm" | "onCancel" | "onConfirm"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Cancel"). */
  cancelText?: string;
  /** Template text/attr substitution (default: "Confirm"). */
  confirmText?: string;
  /** Toggles the template's bare data attribute. */
  confirmRequired?: boolean;
  /** `data-size` on panel; omitted when unset (manifest default: "sm"). */
  size?: LAlertDialogSize;
  /** `data-variant` on panel; omitted when unset (manifest default: "destructive"). */
  tone?: LAlertDialogTone;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="overlay"]` element. */
  overlay?: ReactNode;
  /** Content projected into the `[data-part="panel"]` element. */
  panel?: ReactNode;
  /** Content projected into the `[data-part="header"]` element. */
  header?: ReactNode;
  /** Content projected into the `[data-part="title"]` element. Text fallback when unset (default: ""). */
  title?: ReactNode;
  /** Content projected into the `[data-part="description"]` element. Text fallback when unset (default: ""). */
  description?: ReactNode;
  /** Content projected into the `[data-part="body"]` element. */
  body?: ReactNode;
  /** Content projected into the `[data-part="footer"]` element. */
  footer?: ReactNode;
  /** Content projected into the `[data-part="cancel"]` element. */
  cancel?: ReactNode;
  /** Content projected into the `[data-part="confirm"]` element. */
  confirm?: ReactNode;
  /** `faqir:cancel` → `(detail, event)`. */
  onCancel?: FaqirEventHandler;
  /** `faqir:confirm` → `(detail, event)`. */
  onConfirm?: FaqirEventHandler;
}

/** `alert-dialog` — Interruptive confirmation dialog (role=alertdialog) for destructive or irreversible actions Emits: `onCancel`, `onConfirm` (payload: `(detail, event)`). Exposes via ref: `open()`, `close()`, `toggle()`. */
export const LAlertDialog = createFaqirRecipe<LAlertDialogProps>({
  name: "alert-dialog",
  create: createAlertDialog,
  methods: ["open", "close", "toggle"],
  events: ["cancel", "confirm"],
  slots: ["trigger", "overlay", "panel", "header", "title", "description", "body", "footer", "cancel", "confirm"],
  stringProps: [{ prop: "cancelText", default: "Cancel" }, { prop: "confirmText", default: "Confirm" }, { prop: "description", default: "" }, { prop: "title", default: "" }],
  boolProps: ["confirmRequired"],
  variantProps: [
    { prop: "size", values: ["sm", "md"] },
    { prop: "tone", values: ["default", "destructive"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["alert-dialog"]],["data-state",["closed"]],["id",[{"p":"id"}]],["data-confirm-required",{"b":"confirmRequired"}]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]]],"children":[],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["alertdialog"]],["aria-modal",["true"]],["aria-labelledby",[{"p":"id"},"-title"]],["aria-describedby",[{"p":"id"},"-desc"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"h2","attrs":[["id",[{"p":"id"},"-title"]],["data-part",["title"]]],"children":[{"p":"title"}],"slot":"title"}],"slot":"header"},{"tag":"div","attrs":[["data-part",["body"]]],"children":[{"tag":"p","attrs":[["id",[{"p":"id"},"-desc"]],["data-part",["description"]]],"children":[{"p":"description"}],"slot":"description"}],"slot":"body"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[{"tag":"button","attrs":[["data-ui",["button"]],["data-part",["cancel"]],["data-variant",["outline"]]],"children":[{"p":"cancelText"}],"slot":"cancel"},{"tag":"button","attrs":[["data-ui",["button"]],["data-part",["confirm"]],["data-variant",["destructive"]]],"children":[{"p":"confirmText"}],"slot":"confirm"}],"slot":"footer"}],"slot":"panel","dyn":[["tone","data-variant"],["size","data-size"]]}]} as unknown as RecipeNode,
}, "LAlertDialog");

export default LAlertDialog;
