// AUTO-GENERATED by `faqir bindings react` from registry/recipes/calendar/calendar.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createCalendar } from "../controllers/calendar";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LCalendarSize = "sm" | "md" | "lg";

export interface LCalendarProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "size" | "header" | "nav-prev" | "nav-next" | "month-label" | "grid" | "grid-body" | "onCalendarChange"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LCalendarSize;
  /** Content projected into the `[data-part="header"]` element. */
  header?: ReactNode;
  /** Content projected into the `[data-part="nav-prev"]` element. */
  "nav-prev"?: ReactNode;
  /** Content projected into the `[data-part="nav-next"]` element. */
  "nav-next"?: ReactNode;
  /** Content projected into the `[data-part="month-label"]` element. */
  "month-label"?: ReactNode;
  /** Content projected into the `[data-part="grid"]` element. */
  grid?: ReactNode;
  /** Content projected into the `[data-part="grid-body"]` element. */
  "grid-body"?: ReactNode;
  /** `faqir:calendar-change` → `(detail, event)`. */
  onCalendarChange?: FaqirEventHandler;
}

/** `calendar` — Standalone month-grid calendar with roving-tabindex keyboard navigation, min/max/disabled dates, and single or range selection — extracted from date-picker so availability grids and range pickers can use it directly Emits: `onCalendarChange` (payload: `(detail, event)`). Exposes via ref: `getValue()`, `setValue()`, `clear()`, `navigate()`, `selectDate()`, `focusDate()`, `setMin()`, `setMax()`, `setDisabledDates()`. */
export const LCalendar = createFaqirRecipe<LCalendarProps>({
  name: "calendar",
  create: createCalendar,
  methods: ["getValue", "setValue", "clear", "navigate", "selectDate", "focusDate", "setMin", "setMax", "setDisabledDates"],
  events: ["calendar-change"],
  slots: ["header", "nav-prev", "nav-next", "month-label", "grid", "grid-body"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["calendar"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"button","attrs":[["data-part",["nav-prev"]],["type",["button"]],["aria-label",["Previous month"]]],"children":["‹"],"slot":"nav-prev"},{"tag":"span","attrs":[["data-part",["month-label"]]],"children":[],"slot":"month-label"},{"tag":"button","attrs":[["data-part",["nav-next"]],["type",["button"]],["aria-label",["Next month"]]],"children":["›"],"slot":"nav-next"}],"slot":"header"},{"tag":"table","attrs":[["data-part",["grid"]],["role",["grid"]],["aria-label",["Calendar"]]],"children":[{"tag":"thead","attrs":[],"children":[{"tag":"tr","attrs":[],"children":[{"tag":"th","attrs":[],"children":["Su"]},{"tag":"th","attrs":[],"children":["Mo"]},{"tag":"th","attrs":[],"children":["Tu"]},{"tag":"th","attrs":[],"children":["We"]},{"tag":"th","attrs":[],"children":["Th"]},{"tag":"th","attrs":[],"children":["Fr"]},{"tag":"th","attrs":[],"children":["Sa"]}]}]},{"tag":"tbody","attrs":[["data-part",["grid-body"]]],"children":[],"slot":"grid-body"}],"slot":"grid"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LCalendar");

export default LCalendar;
