// AUTO-GENERATED by `faqir bindings react` from registry/recipes/carousel/carousel.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createCarousel } from "../controllers/carousel";

export interface LCarouselProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "viewport" | "controls" | "prev" | "next" | "dots" | "status" | "onChange"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Content projected into the `[data-part="viewport"]` element. */
  viewport?: ReactNode;
  /** Content projected into the `[data-part="controls"]` element. */
  controls?: ReactNode;
  /** Content projected into the `[data-part="prev"]` element. */
  prev?: ReactNode;
  /** Content projected into the `[data-part="next"]` element. */
  next?: ReactNode;
  /** Content projected into the `[data-part="dots"]` element. */
  dots?: ReactNode;
  /** Content projected into the `[data-part="status"]` element. */
  status?: ReactNode;
  /** `faqir:change` → `(detail, event)`. */
  onChange?: FaqirEventHandler;
}

/** `carousel` — Horizontally scrolling slide strip built on CSS scroll-snap, progressively enhanced with prev/next buttons, dot indicators and a polite live region Emits: `onChange` (payload: `(detail, event)`). Exposes via ref: `next()`, `prev()`, `goTo()`, `getIndex()`, `getCount()`. */
export const LCarousel = createFaqirRecipe<LCarouselProps>({
  name: "carousel",
  create: createCarousel,
  methods: ["next", "prev", "goTo", "getIndex", "getCount"],
  events: ["change"],
  slots: ["viewport", "controls", "prev", "next", "dots", "status"],
  stringProps: [],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["carousel"]],["role",["group"]],["aria-roledescription",["carousel"]]],"children":[{"tag":"div","attrs":[["data-part",["viewport"]],["tabindex",["0"]],["role",["group"]],["aria-label",["Slides"]]],"children":[{"tag":"div","attrs":[["data-part",["slide"]],["role",["group"]],["aria-roledescription",["slide"]],["aria-label",["1 of 2"]]],"children":[]},{"tag":"div","attrs":[["data-part",["slide"]],["role",["group"]],["aria-roledescription",["slide"]],["aria-label",["2 of 2"]]],"children":[]}],"slot":"viewport"},{"tag":"div","attrs":[["data-part",["controls"]],["hidden",true]],"children":[{"tag":"button","attrs":[["data-part",["prev"]],["type",["button"]],["aria-label",["Previous slide"]]],"children":["«"],"slot":"prev"},{"tag":"button","attrs":[["data-part",["next"]],["type",["button"]],["aria-label",["Next slide"]]],"children":["»"],"slot":"next"}],"slot":"controls"},{"tag":"div","attrs":[["data-part",["dots"]],["role",["group"]],["aria-label",["Choose slide"]],["hidden",true]],"children":[{"tag":"button","attrs":[["data-part",["dot"]],["type",["button"]],["aria-label",["Slide 1"]]],"children":[]},{"tag":"button","attrs":[["data-part",["dot"]],["type",["button"]],["aria-label",["Slide 2"]]],"children":[]}],"slot":"dots"},{"tag":"p","attrs":[["data-part",["status"]],["role",["status"]],["aria-live",["polite"]]],"children":[],"slot":"status"}]} as unknown as RecipeNode,
}, "LCarousel");

export default LCarousel;
