// AUTO-GENERATED by `faqir bindings react` from registry/recipes/combobox/combobox.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createCombobox } from "../controllers/combobox";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LComboboxSize = "sm" | "md" | "lg";

export interface LComboboxProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "placeholder" | "size" | "input" | "listbox" | "empty"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LComboboxSize;
  /** Content projected into the `[data-part="input"]` element. */
  input?: ReactNode;
  /** Content projected into the `[data-part="listbox"]` element. */
  listbox?: ReactNode;
  /** Content projected into the `[data-part="empty"]` element. */
  empty?: ReactNode;
}

/** `combobox` — Autocomplete input with filtered dropdown list for type-ahead search Exposes via ref: `open()`, `close()`, `filter()`, `selectOption()`, `getValue()`, `setValue()`. */
export const LCombobox = createFaqirRecipe<LComboboxProps>({
  name: "combobox",
  create: createCombobox,
  methods: ["open", "close", "filter", "selectOption", "getValue", "setValue"],
  events: [],
  slots: ["input", "listbox", "empty"],
  stringProps: [{ prop: "placeholder", default: "" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["combobox"]],["data-state",["closed"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-autocomplete",["list"]],["aria-controls",[{"p":"id"},"-listbox"]],["placeholder",[{"p":"placeholder"}]]],"children":[],"slot":"input"},{"tag":"ul","attrs":[["data-part",["listbox"]],["role",["listbox"]],["id",[{"p":"id"},"-listbox"]],["hidden",true]],"children":[{"tag":"li","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]]],"children":[]},{"tag":"li","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]]],"children":[]},{"tag":"li","attrs":[["data-part",["empty"]],["hidden",true]],"children":["No results found"],"slot":"empty"}],"slot":"listbox"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LCombobox");

export default LCombobox;
