// AUTO-GENERATED by `faqir bindings react` from registry/recipes/date-picker/date-picker.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createDatePicker } from "../controllers/date-picker";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LDatePickerSize = "sm" | "md" | "lg";

export interface LDatePickerProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "size" | "trigger" | "input" | "icon" | "calendar" | "onCalendarChange" | "onDateChange"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LDatePickerSize;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="input"]` element. */
  input?: ReactNode;
  /** Content projected into the `[data-part="icon"]` element. */
  icon?: ReactNode;
  /** Content projected into the `[data-part="calendar"]` element. */
  calendar?: ReactNode;
  /** `faqir:calendar-change` → `(detail, event)`. */
  onCalendarChange?: FaqirEventHandler;
  /** `faqir:date-change` → `(detail, event)`. */
  onDateChange?: FaqirEventHandler;
}

/** `date-picker` — Date input with calendar dropdown for date selection — the month grid is the nested `calendar` recipe Emits: `onCalendarChange`, `onDateChange` (payload: `(detail, event)`). Exposes via ref: `open()`, `close()`, `getValue()`, `setValue()`, `navigate()`, `selectDate()`. */
export const LDatePicker = createFaqirRecipe<LDatePickerProps>({
  name: "date-picker",
  create: createDatePicker,
  methods: ["open", "close", "getValue", "setValue", "navigate", "selectDate"],
  events: ["calendar-change", "date-change"],
  slots: ["trigger", "input", "icon", "calendar"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["date-picker"]],["data-state",["closed"]]],"children":[{"tag":"div","attrs":[["data-part",["trigger"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["placeholder",["Select a date"]],["readonly",true],["aria-haspopup",["dialog"]],["aria-expanded",["false"]],["aria-label",["Choose date"]]],"children":[],"slot":"input"},{"tag":"span","attrs":[["data-part",["icon"]],["aria-hidden",["true"]]],"children":["📅"],"slot":"icon"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["calendar"]],["role",["dialog"]],["aria-label",["Date picker"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-ui",["calendar"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"button","attrs":[["data-part",["nav-prev"]],["type",["button"]],["aria-label",["Previous month"]]],"children":["‹"]},{"tag":"span","attrs":[["data-part",["month-label"]]],"children":[]},{"tag":"button","attrs":[["data-part",["nav-next"]],["type",["button"]],["aria-label",["Next month"]]],"children":["›"]}]},{"tag":"table","attrs":[["data-part",["grid"]],["role",["grid"]],["aria-label",["Calendar"]]],"children":[{"tag":"thead","attrs":[],"children":[{"tag":"tr","attrs":[],"children":[{"tag":"th","attrs":[],"children":["Su"]},{"tag":"th","attrs":[],"children":["Mo"]},{"tag":"th","attrs":[],"children":["Tu"]},{"tag":"th","attrs":[],"children":["We"]},{"tag":"th","attrs":[],"children":["Th"]},{"tag":"th","attrs":[],"children":["Fr"]},{"tag":"th","attrs":[],"children":["Sa"]}]}]},{"tag":"tbody","attrs":[["data-part",["grid-body"]]],"children":[]}]}]}],"slot":"calendar"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LDatePicker");

export default LDatePicker;
