// AUTO-GENERATED by `faqir bindings react` from registry/recipes/drawer/drawer.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createDrawer } from "../controllers/drawer";

/** Allowed `side` values (manifest variant group "side", attr `data-variant` on panel). */
export type LDrawerSide = "left" | "right";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LDrawerSize = "sm" | "md" | "lg" | "full";

export interface LDrawerProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "title" | "triggerText" | "side" | "size" | "trigger" | "overlay" | "panel" | "header" | "body" | "footer" | "close"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Open"). */
  triggerText?: string;
  /** `data-variant` on panel; omitted when unset (manifest default: "left"). */
  side?: LDrawerSide;
  /** `data-size` on panel; omitted when unset (manifest default: "md"). */
  size?: LDrawerSize;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="overlay"]` element. */
  overlay?: ReactNode;
  /** Content projected into the `[data-part="panel"]` element. */
  panel?: ReactNode;
  /** Content projected into the `[data-part="header"]` element. */
  header?: ReactNode;
  /** Content projected into the `[data-part="title"]` element. Text fallback when unset (default: ""). */
  title?: ReactNode;
  /** Content projected into the `[data-part="body"]` element. */
  body?: ReactNode;
  /** Content projected into the `[data-part="footer"]` element. */
  footer?: ReactNode;
  /** Content projected into the `[data-part="close"]` element. */
  close?: ReactNode;
}

/** `drawer` — Side panel that slides in from screen edge with overlay backdrop Exposes via ref: `open()`, `close()`, `toggle()`. */
export const LDrawer = createFaqirRecipe<LDrawerProps>({
  name: "drawer",
  create: createDrawer,
  methods: ["open", "close", "toggle"],
  events: [],
  slots: ["trigger", "overlay", "panel", "header", "title", "body", "footer", "close"],
  stringProps: [{ prop: "title", default: "" }, { prop: "triggerText", default: "Open" }],
  boolProps: [],
  variantProps: [
    { prop: "side", values: ["left", "right"] },
    { prop: "size", values: ["sm", "md", "lg", "full"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["drawer"]],["data-state",["closed"]],["id",[{"p":"id"}]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["dialog"]],["aria-modal",["true"]],["aria-labelledby",[{"p":"id"},"-title"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"h2","attrs":[["id",[{"p":"id"},"-title"]],["data-part",["title"]]],"children":[{"p":"title"}],"slot":"title"},{"tag":"button","attrs":[["data-part",["close"]],["aria-label",["Close drawer"]]],"children":["✕"],"slot":"close"}],"slot":"header"},{"tag":"div","attrs":[["data-part",["body"]]],"children":[],"slot":"body"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[],"slot":"footer"}],"slot":"panel","dyn":[["side","data-variant"],["size","data-size"]]}]} as unknown as RecipeNode,
}, "LDrawer");

export default LDrawer;
