// AUTO-GENERATED by `faqir bindings react` from registry/recipes/dropdown/dropdown.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createDropdown } from "../controllers/dropdown";

/** Allowed `align` values (manifest variant group "align", attr `data-variant` on menu). */
export type LDropdownAlign = "start" | "end";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LDropdownSize = "sm" | "md" | "lg";

export interface LDropdownProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "triggerText" | "align" | "size" | "trigger" | "menu" | "separator"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Menu"). */
  triggerText?: string;
  /** `data-variant` on menu; omitted when unset (manifest default: "start"). */
  align?: LDropdownAlign;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LDropdownSize;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="menu"]` element. */
  menu?: ReactNode;
  /** Content projected into the `[data-part="separator"]` element. */
  separator?: ReactNode;
}

/** `dropdown` — Dropdown menu with keyboard navigation and click-outside-to-close Exposes via ref: `open()`, `close()`, `toggle()`. */
export const LDropdown = createFaqirRecipe<LDropdownProps>({
  name: "dropdown",
  create: createDropdown,
  methods: ["open", "close", "toggle"],
  events: [],
  slots: ["trigger", "menu", "separator"],
  stringProps: [{ prop: "triggerText", default: "Menu" }],
  boolProps: [],
  variantProps: [
    { prop: "align", values: ["start", "end"] },
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["dropdown"]],["data-state",["closed"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["aria-haspopup",["true"]],["aria-expanded",["false"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["menu"]],["role",["menu"]],["hidden",true]],"children":[{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]},{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]},{"tag":"hr","attrs":[["data-part",["separator"]]],"children":[],"slot":"separator"},{"tag":"button","attrs":[["data-part",["item"]],["role",["menuitem"]]],"children":[]}],"slot":"menu","dyn":[["align","data-variant"]]}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LDropdown");

export default LDropdown;
