// AUTO-GENERATED by `faqir bindings react` from registry/recipes/file-upload/file-upload.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createFileUpload } from "../controllers/file-upload";

export interface LFileUploadProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "accept" | "maxSize" | "dropzone" | "input" | "prompt" | "description" | "list" | "empty" | "status" | "onFileReject" | "onFileRemove" | "onFiles"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "image/png,image/jpeg"). */
  accept?: string;
  /** Template text/attr substitution (default: "5242880"). */
  maxSize?: string;
  /** Content projected into the `[data-part="dropzone"]` element. */
  dropzone?: ReactNode;
  /** Content projected into the `[data-part="input"]` element. */
  input?: ReactNode;
  /** Content projected into the `[data-part="prompt"]` element. */
  prompt?: ReactNode;
  /** Content projected into the `[data-part="description"]` element. */
  description?: ReactNode;
  /** Content projected into the `[data-part="list"]` element. */
  list?: ReactNode;
  /** Content projected into the `[data-part="empty"]` element. */
  empty?: ReactNode;
  /** Content projected into the `[data-part="status"]` element. */
  status?: ReactNode;
  /** `faqir:file-reject` → `(detail, event)`. */
  onFileReject?: FaqirEventHandler;
  /** `faqir:file-remove` → `(detail, event)`. */
  onFileRemove?: FaqirEventHandler;
  /** `faqir:files` → `(detail, event)`. */
  onFiles?: FaqirEventHandler;
}

/** `file-upload` — Native file selection plus drag-and-drop, local accept/size validation, removable file list, and event-only app upload handoff Emits: `onFileReject`, `onFileRemove`, `onFiles` (payload: `(detail, event)`). Exposes via ref: `getFiles()`, `open()`, `remove()`, `clear()`. */
export const LFileUpload = createFaqirRecipe<LFileUploadProps>({
  name: "file-upload",
  create: createFileUpload,
  methods: ["getFiles", "open", "remove", "clear"],
  events: ["file-reject", "file-remove", "files"],
  slots: ["dropzone", "input", "prompt", "description", "list", "empty", "status"],
  stringProps: [{ prop: "accept", default: "image/png,image/jpeg" }, { prop: "maxSize", default: "5242880" }],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["file-upload"]],["data-state",["idle"]],["data-max-size",[{"p":"maxSize"}]]],"children":[{"tag":"label","attrs":[["data-part",["dropzone"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["file"]],["accept",[{"p":"accept"}]],["multiple",true],["aria-describedby",[{"p":"id"},"-help"]]],"children":[],"slot":"input"},{"tag":"span","attrs":[["data-part",["prompt"]]],"children":["Choose files or drag them here"],"slot":"prompt"},{"tag":"span","attrs":[["data-part",["description"]],["id",[{"p":"id"},"-help"]]],"children":["Accepted file types and maximum size."],"slot":"description"}],"slot":"dropzone"},{"tag":"ul","attrs":[["data-part",["list"]],["aria-label",["Selected files"]]],"children":[{"tag":"li","attrs":[["data-part",["empty"]]],"children":["No files selected"],"slot":"empty"}],"slot":"list"},{"tag":"span","attrs":[["data-part",["status"]],["role",["status"]],["aria-live",["polite"]]],"children":[],"slot":"status"}]} as unknown as RecipeNode,
}, "LFileUpload");

export default LFileUpload;
