// AUTO-GENERATED by `faqir bindings react` from registry/recipes/pagination/pagination.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createPagination } from "../controllers/pagination";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LPaginationSize = "sm" | "md" | "lg";

export interface LPaginationProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "size" | "nav" | "prev" | "next" | "ellipsis" | "onPageChange"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LPaginationSize;
  /** Content projected into the `[data-part="nav"]` element. */
  nav?: ReactNode;
  /** Content projected into the `[data-part="prev"]` element. */
  prev?: ReactNode;
  /** Content projected into the `[data-part="next"]` element. */
  next?: ReactNode;
  /** Content projected into the `[data-part="ellipsis"]` element. */
  ellipsis?: ReactNode;
  /** `faqir:page-change` → `(detail, event)`. */
  onPageChange?: FaqirEventHandler;
}

/** `pagination` — Page navigation with numbered controls, previous/next, and ellipsis Emits: `onPageChange` (payload: `(detail, event)`). Exposes via ref: `setPage()`, `getPage()`, `setTotal()`, `render()`. */
export const LPagination = createFaqirRecipe<LPaginationProps>({
  name: "pagination",
  create: createPagination,
  methods: ["setPage", "getPage", "setTotal", "render"],
  events: ["page-change"],
  slots: ["nav", "prev", "next", "ellipsis"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["pagination"]]],"children":[{"tag":"nav","attrs":[["data-part",["nav"]],["role",["navigation"]],["aria-label",["Pagination"]]],"children":[{"tag":"button","attrs":[["data-part",["prev"]],["aria-label",["Previous page"]]],"children":["« Prev"],"slot":"prev"},{"tag":"button","attrs":[["data-part",["page"]],["data-page",["1"]],["data-state",["active"]],["aria-current",["page"]]],"children":["1"]},{"tag":"button","attrs":[["data-part",["page"]],["data-page",["2"]]],"children":["2"]},{"tag":"span","attrs":[["data-part",["ellipsis"]]],"children":["…"],"slot":"ellipsis"},{"tag":"button","attrs":[["data-part",["page"]]],"children":[]},{"tag":"button","attrs":[["data-part",["next"]],["aria-label",["Next page"]]],"children":["Next »"],"slot":"next"}],"slot":"nav"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LPagination");

export default LPagination;
