// AUTO-GENERATED by `faqir bindings react` from registry/recipes/popover/popover.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createPopover } from "../controllers/popover";

/** Allowed `align` values (manifest variant group "align", attr `data-align` on content). */
export type LPopoverAlign = "start" | "center" | "end";

/** Allowed `position` values (manifest variant group "position", attr `data-variant` on content). */
export type LPopoverPosition = "top" | "bottom" | "left" | "right";

export interface LPopoverProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "triggerText" | "align" | "position" | "trigger" | "content" | "close"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Open"). */
  triggerText?: string;
  /** `data-align` on content; omitted when unset (manifest default: "start"). */
  align?: LPopoverAlign;
  /** `data-variant` on content; omitted when unset (manifest default: "bottom"). */
  position?: LPopoverPosition;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="content"]` element. */
  content?: ReactNode;
  /** Content projected into the `[data-part="close"]` element. */
  close?: ReactNode;
}

/** `popover` — Content popup anchored to a trigger element with click toggle Exposes via ref: `open()`, `close()`, `toggle()`. */
export const LPopover = createFaqirRecipe<LPopoverProps>({
  name: "popover",
  create: createPopover,
  methods: ["open", "close", "toggle"],
  events: [],
  slots: ["trigger", "content", "close"],
  stringProps: [{ prop: "triggerText", default: "Open" }],
  boolProps: [],
  variantProps: [
    { prop: "align", values: ["start", "center", "end"] },
    { prop: "position", values: ["top", "bottom", "left", "right"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["popover"]],["data-state",["closed"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["aria-haspopup",["true"]],["aria-expanded",["false"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["content"]],["hidden",true]],"children":["\n    \n    ",{"tag":"button","attrs":[["data-part",["close"]],["aria-label",["Close popover"]]],"children":["✕"],"slot":"close"}],"slot":"content","dyn":[["position","data-variant"],["align","data-align"]]}]} as unknown as RecipeNode,
}, "LPopover");

export default LPopover;
