// AUTO-GENERATED by `faqir bindings react` from registry/recipes/select-custom/select-custom.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createSelectCustom } from "../controllers/select-custom";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LSelectCustomSize = "sm" | "md" | "lg";

export interface LSelectCustomProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "placeholder" | "value" | "size" | "trigger" | "listbox"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LSelectCustomSize;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="value"]` element. Text fallback when unset (default: ""). */
  value?: ReactNode;
  /** Content projected into the `[data-part="listbox"]` element. */
  listbox?: ReactNode;
}

/** `select-custom` — Custom styled select dropdown with search filtering and keyboard navigation Exposes via ref: `open()`, `close()`, `toggle()`, `select()`, `getValue()`. */
export const LSelectCustom = createFaqirRecipe<LSelectCustomProps>({
  name: "select-custom",
  create: createSelectCustom,
  methods: ["open", "close", "toggle", "select", "getValue"],
  events: [],
  slots: ["trigger", "value", "listbox"],
  stringProps: [{ prop: "placeholder", default: "" }, { prop: "value", default: "" }],
  boolProps: [],
  variantProps: [
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["select-custom"]],["data-state",["closed"]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-haspopup",["listbox"]],["aria-controls",[{"p":"id"},"-listbox"]]],"children":[{"tag":"span","attrs":[["data-part",["value"]],["data-placeholder",true]],"children":[{"p":"placeholder"}],"slot":"value"},{"tag":"span","attrs":[["data-part",["chevron"]],["aria-hidden",["true"]]],"children":["▾"]}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["listbox"]],["role",["listbox"]],["id",[{"p":"id"},"-listbox"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]],["data-value",[{"p":"value"}]]],"children":[]},{"tag":"div","attrs":[["data-part",["option"]],["role",["option"]],["aria-selected",["false"]],["data-value",[{"p":"value"}]]],"children":[]}],"slot":"listbox"}],"dyn":[["size","data-size"]]} as unknown as RecipeNode,
}, "LSelectCustom");

export default LSelectCustom;
