// AUTO-GENERATED by `faqir bindings react` from registry/recipes/sheet/sheet.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createSheet } from "../controllers/sheet";

/** Allowed `side` values (manifest variant group "side", attr `data-variant` on panel). */
export type LSheetSide = "bottom" | "top" | "left" | "right";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on panel). */
export type LSheetSize = "sm" | "md" | "lg";

export interface LSheetProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "title" | "triggerText" | "side" | "size" | "trigger" | "overlay" | "panel" | "header" | "body" | "close"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: "Open"). */
  triggerText?: string;
  /** `data-variant` on panel; omitted when unset (manifest default: "bottom"). */
  side?: LSheetSide;
  /** `data-size` on panel; omitted when unset (manifest default: "md"). */
  size?: LSheetSize;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="overlay"]` element. */
  overlay?: ReactNode;
  /** Content projected into the `[data-part="panel"]` element. */
  panel?: ReactNode;
  /** Content projected into the `[data-part="header"]` element. */
  header?: ReactNode;
  /** Content projected into the `[data-part="title"]` element. Text fallback when unset (default: ""). */
  title?: ReactNode;
  /** Content projected into the `[data-part="body"]` element. */
  body?: ReactNode;
  /** Content projected into the `[data-part="close"]` element. */
  close?: ReactNode;
}

/** `sheet` — Mobile-friendly bottom or side sheet that slides in from screen edge Exposes via ref: `open()`, `close()`, `toggle()`. */
export const LSheet = createFaqirRecipe<LSheetProps>({
  name: "sheet",
  create: createSheet,
  methods: ["open", "close", "toggle"],
  events: [],
  slots: ["trigger", "overlay", "panel", "header", "title", "body", "close"],
  stringProps: [{ prop: "title", default: "" }, { prop: "triggerText", default: "Open" }],
  boolProps: [],
  variantProps: [
    { prop: "side", values: ["bottom", "top", "left", "right"] },
    { prop: "size", values: ["sm", "md", "lg"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["sheet"]],["data-state",["closed"]],["id",[{"p":"id"}]]],"children":[{"tag":"button","attrs":[["data-part",["trigger"]]],"children":[{"p":"triggerText"}],"slot":"trigger"},{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"div","attrs":[["data-part",["panel"]],["role",["dialog"]],["aria-modal",["true"]],["aria-labelledby",[{"p":"id"},"-title"]],["hidden",true]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"h2","attrs":[["id",[{"p":"id"},"-title"]],["data-part",["title"]]],"children":[{"p":"title"}],"slot":"title"},{"tag":"button","attrs":[["data-part",["close"]],["aria-label",["Close sheet"]]],"children":["✕"],"slot":"close"}],"slot":"header"},{"tag":"div","attrs":[["data-part",["body"]]],"children":[],"slot":"body"}],"slot":"panel","dyn":[["side","data-variant"],["size","data-size"]]}]} as unknown as RecipeNode,
}, "LSheet");

export default LSheet;
