// AUTO-GENERATED by `faqir bindings react` from registry/recipes/sidebar/sidebar.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createSidebar } from "../controllers/sidebar";

export interface LSidebarProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "overlay" | "panel" | "header" | "brand" | "brand-icon" | "brand-label" | "trigger" | "nav" | "item" | "icon" | "label" | "footer"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Content projected into the `[data-part="overlay"]` element. */
  overlay?: ReactNode;
  /** Content projected into the `[data-part="panel"]` element. */
  panel?: ReactNode;
  /** Content projected into the `[data-part="header"]` element. */
  header?: ReactNode;
  /** Content projected into the `[data-part="brand"]` element. */
  brand?: ReactNode;
  /** Content projected into the `[data-part="brand-icon"]` element. */
  "brand-icon"?: ReactNode;
  /** Content projected into the `[data-part="brand-label"]` element. */
  "brand-label"?: ReactNode;
  /** Content projected into the `[data-part="trigger"]` element. */
  trigger?: ReactNode;
  /** Content projected into the `[data-part="nav"]` element. */
  nav?: ReactNode;
  /** Content projected into the `[data-part="item"]` element. */
  item?: ReactNode;
  /** Content projected into the `[data-part="icon"]` element. */
  icon?: ReactNode;
  /** Content projected into the `[data-part="label"]` element. */
  label?: ReactNode;
  /** Content projected into the `[data-part="footer"]` element. */
  footer?: ReactNode;
}

/** `sidebar` — Collapsible application sidebar with three modes — expanded, rail (icons only), and a mobile off-canvas drawer — switched responsively and toggled from the keyboard Exposes via ref: `toggle()`, `expand()`, `collapse()`, `open()`, `close()`, `isMobile()`, `getState()`. */
export const LSidebar = createFaqirRecipe<LSidebarProps>({
  name: "sidebar",
  create: createSidebar,
  methods: ["toggle", "expand", "collapse", "open", "close", "isMobile", "getState"],
  events: [],
  slots: ["overlay", "panel", "header", "brand", "brand-icon", "brand-label", "trigger", "nav", "item", "icon", "label", "footer"],
  stringProps: [],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["sidebar"]],["data-state",["expanded"]],["id",[{"p":"id"}]]],"children":[{"tag":"div","attrs":[["data-part",["overlay"]],["hidden",true]],"children":[],"slot":"overlay"},{"tag":"aside","attrs":[["data-part",["panel"]],["aria-label",["Primary navigation"]]],"children":[{"tag":"div","attrs":[["data-part",["header"]]],"children":[{"tag":"a","attrs":[["data-part",["brand"]],["href",["#"]]],"children":[{"tag":"span","attrs":[["data-part",["brand-icon"]],["aria-hidden",["true"]]],"children":[],"slot":"brand-icon"},{"tag":"span","attrs":[["data-part",["brand-label"]]],"children":[],"slot":"brand-label"}],"slot":"brand"},{"tag":"button","attrs":[["data-part",["trigger"]],["aria-label",["Toggle sidebar"]],["aria-expanded",["true"]],["aria-controls",[{"p":"id"}]]],"children":[],"slot":"trigger"}],"slot":"header"},{"tag":"nav","attrs":[["data-part",["nav"]],["aria-label",["Main"]]],"children":[{"tag":"a","attrs":[["data-part",["item"]],["href",["#"]],["aria-current",["page"]]],"children":[{"tag":"span","attrs":[["data-part",["icon"]],["aria-hidden",["true"]]],"children":[],"slot":"icon"},{"tag":"span","attrs":[["data-part",["label"]]],"children":[],"slot":"label"}],"slot":"item"}],"slot":"nav"},{"tag":"div","attrs":[["data-part",["footer"]]],"children":[],"slot":"footer"}],"slot":"panel"}]} as unknown as RecipeNode,
}, "LSidebar");

export default LSidebar;
