// AUTO-GENERATED by `faqir bindings react` from registry/recipes/table/table.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createTable } from "../controllers/table";

/** Allowed `bordered` values (manifest variant group "bordered", attr `data-variant` on root). */
export type LTableBordered = "true" | "false";

/** Allowed `size` values (manifest variant group "size", attr `data-size` on root). */
export type LTableSize = "sm" | "md" | "lg";

/** Allowed `striped` values (manifest variant group "striped", attr `data-variant` on root). */
export type LTableStriped = "true" | "false";

export interface LTableProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "bordered" | "size" | "striped" | "table" | "thead" | "tbody" | "onCellEdit" | "onColReorder" | "onColResize" | "onColVisibility" | "onEditCancel" | "onEditStart" | "onFilter" | "onGroupToggle" | "onRowExpand" | "onRowReorder" | "onSelectionChange" | "onSort" | "onTreeToggle"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-variant` on root; omitted when unset (manifest default: "false"). */
  bordered?: LTableBordered;
  /** `data-size` on root; omitted when unset (manifest default: "md"). */
  size?: LTableSize;
  /** `data-variant` on root; omitted when unset (manifest default: "false"). */
  striped?: LTableStriped;
  /** Content projected into the `[data-part="table"]` element. */
  table?: ReactNode;
  /** Content projected into the `[data-part="thead"]` element. */
  thead?: ReactNode;
  /** Content projected into the `[data-part="tbody"]` element. */
  tbody?: ReactNode;
  /** `faqir:cell-edit` → `(detail, event)`. */
  onCellEdit?: FaqirEventHandler;
  /** `faqir:col-reorder` → `(detail, event)`. */
  onColReorder?: FaqirEventHandler;
  /** `faqir:col-resize` → `(detail, event)`. */
  onColResize?: FaqirEventHandler;
  /** `faqir:col-visibility` → `(detail, event)`. */
  onColVisibility?: FaqirEventHandler;
  /** `faqir:edit-cancel` → `(detail, event)`. */
  onEditCancel?: FaqirEventHandler;
  /** `faqir:edit-start` → `(detail, event)`. */
  onEditStart?: FaqirEventHandler;
  /** `faqir:filter` → `(detail, event)`. */
  onFilter?: FaqirEventHandler;
  /** `faqir:group-toggle` → `(detail, event)`. */
  onGroupToggle?: FaqirEventHandler;
  /** `faqir:row-expand` → `(detail, event)`. */
  onRowExpand?: FaqirEventHandler;
  /** `faqir:row-reorder` → `(detail, event)`. */
  onRowReorder?: FaqirEventHandler;
  /** `faqir:selection-change` → `(detail, event)`. */
  onSelectionChange?: FaqirEventHandler;
  /** `faqir:sort` → `(detail, event)`. */
  onSort?: FaqirEventHandler;
  /** `faqir:tree-toggle` → `(detail, event)`. */
  onTreeToggle?: FaqirEventHandler;
}

/** `table` — Advanced data table: multi-column type-aware sorting, global + per-column filtering, tree data and collapsible row groups with live aggregates, inline cell editing with Intl number/currency formatting, drag-and-drop row and column reordering, column resize/hide/pin, sticky header/footer/rows, grid keyboard navigation, CSV export, responsive stacked mode, and state persistence — every feature opt-in via data attributes Emits: `onCellEdit`, `onColReorder`, `onColResize`, `onColVisibility`, `onEditCancel`, `onEditStart`, `onFilter`, `onGroupToggle`, `onRowExpand`, `onRowReorder`, `onSelectionChange`, `onSort`, `onTreeToggle` (payload: `(detail, event)`). Exposes via ref: `sort()`, `sortBy()`, `clearSort()`, `selectRow()`, `selectAll()`, `deselectAll()`, `getSelected()`, `getSelectedData()`, `setFilter()`, `setColumnFilter()`, `clearFilters()`, `toggleGroup()`, `toggleRow()`, `toggleDetail()`, `expandAll()`, `collapseAll()`, `startEdit()`, `commitEdit()`, `cancelEdit()`, `moveRow()`, `moveColumn()`, `hideColumn()`, `showColumn()`, `toggleColumn()`, `setColumnWidth()`, `exportCsv()`, `getData()`, `getState()`, `setState()`, `refresh()`. */
export const LTable = createFaqirRecipe<LTableProps>({
  name: "table",
  create: createTable,
  methods: ["sort", "sortBy", "clearSort", "selectRow", "selectAll", "deselectAll", "getSelected", "getSelectedData", "setFilter", "setColumnFilter", "clearFilters", "toggleGroup", "toggleRow", "toggleDetail", "expandAll", "collapseAll", "startEdit", "commitEdit", "cancelEdit", "moveRow", "moveColumn", "hideColumn", "showColumn", "toggleColumn", "setColumnWidth", "exportCsv", "getData", "getState", "setState", "refresh"],
  events: ["cell-edit", "col-reorder", "col-resize", "col-visibility", "edit-cancel", "edit-start", "filter", "group-toggle", "row-expand", "row-reorder", "selection-change", "sort", "tree-toggle"],
  slots: ["table", "thead", "tbody"],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "bordered", values: ["true", "false"] },
    { prop: "size", values: ["sm", "md", "lg"] },
    { prop: "striped", values: ["true", "false"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["table"]]],"children":[{"tag":"table","attrs":[["data-part",["table"]]],"children":[{"tag":"thead","attrs":[["data-part",["thead"]]],"children":[{"tag":"tr","attrs":[["data-part",["tr"]]],"children":[{"tag":"th","attrs":[["data-part",["th"]],["scope",["col"]]],"children":[{"tag":"input","attrs":[["data-part",["checkbox"]],["type",["checkbox"]],["aria-label",["Select all rows"]]],"children":[]}]},{"tag":"th","attrs":[["data-part",["th"]],["scope",["col"]],["data-sortable",true],["aria-sort",["none"]]],"children":[]},{"tag":"th","attrs":[["data-part",["th"]],["scope",["col"]],["data-sortable",true],["aria-sort",["none"]]],"children":[]}]}],"slot":"thead"},{"tag":"tbody","attrs":[["data-part",["tbody"]]],"children":[{"tag":"tr","attrs":[["data-part",["tr"]]],"children":[{"tag":"td","attrs":[["data-part",["td"]]],"children":[{"tag":"input","attrs":[["data-part",["checkbox"]],["type",["checkbox"]],["aria-label",["Select row"]]],"children":[]}]},{"tag":"td","attrs":[["data-part",["td"]]],"children":[]},{"tag":"td","attrs":[["data-part",["td"]]],"children":[]}]}],"slot":"tbody"}],"slot":"table"}],"dyn":[["size","data-size"],["striped","data-variant"],["bordered","data-variant"]]} as unknown as RecipeNode,
}, "LTable");

export default LTable;
