// AUTO-GENERATED by `faqir bindings react` from registry/recipes/tag-input/tag-input.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createTagInput } from "../controllers/tag-input";

export interface LTagInputProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "placeholder" | "taglist" | "input" | "value"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** Template text/attr substitution (default: ""). */
  placeholder?: string;
  /** Content projected into the `[data-part="taglist"]` element. */
  taglist?: ReactNode;
  /** Content projected into the `[data-part="input"]` element. */
  input?: ReactNode;
  /** Content projected into the `[data-part="value"]` element. */
  value?: ReactNode;
}

/** `tag-input` — Multi-value input composing the chip primitive and combobox listbox behaviour — type + Enter to add tags, Backspace to remove the last, dismiss buttons per tag, optional filtered suggestions, and a configurable duplicates policy Exposes via ref: `getValue()`, `setValue()`, `addTag()`, `removeTag()`, `clear()`. */
export const LTagInput = createFaqirRecipe<LTagInputProps>({
  name: "tag-input",
  create: createTagInput,
  methods: ["getValue", "setValue", "addTag", "removeTag", "clear"],
  events: [],
  slots: ["taglist", "input", "value"],
  stringProps: [{ prop: "placeholder", default: "" }],
  boolProps: [],
  variantProps: [
  ],
  tree: {"tag":"div","attrs":[["data-ui",["tag-input"]],["data-state",["closed"]]],"children":[{"tag":"span","attrs":[["data-part",["taglist"]],["role",["list"]]],"children":[{"tag":"input","attrs":[["data-part",["input"]],["type",["text"]],["role",["combobox"]],["aria-expanded",["false"]],["aria-autocomplete",["list"]],["placeholder",[{"p":"placeholder"}]]],"children":[],"slot":"input"}],"slot":"taglist"},{"tag":"input","attrs":[["data-part",["value"]],["type",["hidden"]]],"children":[],"slot":"value"}]} as unknown as RecipeNode,
}, "LTagInput");

export default LTagInput;
