// AUTO-GENERATED by `faqir bindings react` from registry/recipes/toggle-group/toggle-group.manifest.json
// and the recipe controller. Do not edit — regenerate with `faqir bindings react`.

"use client";

import { createFaqirRecipe } from "../recipe-runtime.js";
import type { FaqirEventHandler, RecipeNode } from "../recipe-runtime.js";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { createToggleGroup } from "../controllers/toggle-group.js";

/** Allowed `mode` values (manifest variant group "mode", attr `data-mode` on root). */
export type LToggleGroupMode = "single" | "multi";

/** Allowed `styleVariant` values (manifest variant group "style", attr `data-variant` on root). */
export type LToggleGroupStyleVariant = "default" | "segmented";

export interface LToggleGroupProps extends Omit<ComponentPropsWithoutRef<"div">, "id" | "mode" | "styleVariant" | "onChange"> {
  /** Root/ARIA id base; auto-generated per instance when unset. */
  id?: string;
  /** `data-mode` on root; omitted when unset (manifest default: "single"). */
  mode?: LToggleGroupMode;
  /** `data-variant` on root; omitted when unset (manifest default: "default"). */
  styleVariant?: LToggleGroupStyleVariant;
  /** `faqir:change` → `(detail, event)`. */
  onChange?: FaqirEventHandler;
}

/** `toggle-group` — Single- or multi-select group of toggle buttons over native radio/checkbox controls, with roving-tabindex keyboard navigation and native l-model binding. A segmented style turns a single-select group into one track with a sliding thumb — the monthly/yearly switch of a pricing page — in pure CSS. Emits: `onChange` (payload: `(detail, event)`). Exposes via ref: `getValue()`, `setValue()`, `toggle()`. */
export const LToggleGroup = createFaqirRecipe<LToggleGroupProps>({
  name: "toggle-group",
  create: createToggleGroup,
  methods: ["getValue", "setValue", "toggle"],
  events: ["change"],
  slots: [],
  stringProps: [],
  boolProps: [],
  variantProps: [
    { prop: "mode", values: ["single", "multi"] },
    { prop: "styleVariant", values: ["default", "segmented"] },
  ],
  tree: {"tag":"div","attrs":[["data-ui",["toggle-group"]],["role",["radiogroup"]]],"children":[{"tag":"label","attrs":[["data-part",["item"]],["data-state",["off"]]],"children":[{"tag":"input","attrs":[["data-part",["control"]],["type",["radio"]],["name",[{"p":"id"}]]],"children":[]},{"tag":"span","attrs":[["data-part",["label"]]],"children":[]}]},{"tag":"label","attrs":[["data-part",["item"]],["data-state",["off"]]],"children":[{"tag":"input","attrs":[["data-part",["control"]],["type",["radio"]],["name",[{"p":"id"}]]],"children":[]},{"tag":"span","attrs":[["data-part",["label"]]],"children":[]}]}],"dyn":[["mode","data-mode"],["styleVariant","data-variant"]]} as unknown as RecipeNode,
}, "LToggleGroup");

export default LToggleGroup;
