// Documentation-site generator (task 0.7-13, FAQIR-PLAN §13).
//
// The docs site is a Faqir project with **no build step at runtime**: every page
// is plain HTML written at authoring time, styled by one registry stylesheet,
// and served by any static file server. Everything that describes a component —
// anatomy, variants, states, a11y, tokens, templates, transforms, composition —
// is DERIVED from that component's manifest, so adding a component to the
// registry adds its page (and its nav entry, and its live example) with zero
// edits to `site/`.
//
// Output shape (all paths relative to the output directory):
//
//   index.html                        home (authored fragment + registry stats)
//   components/index.html             every component, grouped by layer
//   components/<layer>/<name>.html    one page per component
//   tokens/index.html                 token reference, grouped by token file
//   examples/<layer>/<name>.html      one standalone live example per component
//   styles/faqir.css                  tokens + base + theme + every component CSS
//   scripts/faqir-core.js             the registry engine (example pages only)
//
// Two page *classes*, deliberately held to different gates (see docs/docs-site.md):
//
//   • **Site pages** (home, index, component, token) are authored by this
//     generator out of registry components and tokens only. They must be 100%
//     `faqir audit`-clean at every severity and axe-clean — that is the proof the
//     framework can build its own documentation.
//   • **Example pages** wrap a registry reference fragment VERBATIM. That markup
//     is the registry's, not the site's: it is gated where it lives (the registry
//     self-audit's document rules and the a11y matrix of task 0.4-24). Re-running
//     the per-component rules over it here would only duplicate that gate — the
//     reference pages are deliberately partial demos (a card showing just its
//     header, a dialog demoed without a live controller), which those rules flag
//     by design.
//
// Zero dependencies and **node:fs only** — no Bun APIs — so the same module runs
// under `bun test`, under the Playwright (Node) runner, and from
// `scripts/build-docs.mjs`. Output is deterministic: no timestamps, sorted
// traversal, so regeneration is byte-identical (asserted by the idempotence test).

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Manifest } from "../manifest";

const HERE = dirname(fileURLToPath(import.meta.url));
/** Repository root — `src/generator/` is two levels down. */
export const PACKAGE_ROOT = join(HERE, "..", "..");

/** Stable, grep-able marker proving a page came out of this generator. */
export const DOCS_GENERATION_MARKER = "GENERATED by faqir · manifest-derived docs site";

/** Registry directories that ship documentable components. */
export const LAYERS = ["primitives", "recipes", "patterns"] as const;
export type Layer = (typeof LAYERS)[number];

/** Human labels for the layer headings and nav groups. */
const LAYER_LABEL: Record<Layer, string> = {
  primitives: "Primitives",
  recipes: "Recipes",
  patterns: "Patterns",
};

const LAYER_BLURB: Record<Layer, string> = {
  primitives: "Single-element building blocks. Pure CSS, no JavaScript, no dependencies.",
  recipes: "Composed components with a small controller for behaviour that CSS cannot express.",
  patterns: "Whole-page compositions of primitives and recipes — copy, then edit.",
};

/**
 * Token load order — authoritative, mirrors `registry/tokens/index.css` and the
 * concatenation `faqir init` performs. `index.css` itself is excluded (it is only
 * `@import` statements) and `density.css` declares into `[data-density]` scopes
 * rather than `:root`, so it ships in the stylesheet but contributes no entries
 * to the token reference.
 */
const TOKEN_FILES = [
  "palette",
  "spacing",
  "typography",
  "effects",
  "motion",
  "semantic",
  "aliases",
  "document",
  "doc-aliases",
  "density",
] as const;

/** Base stylesheets, in cascade order. */
const BASE_FILES = ["reset", "prose", "motion-presets"] as const;

/** Prose labels for the token groups on the token-reference page. */
const TOKEN_GROUP_LABEL: Record<string, string> = {
  palette: "Palette",
  spacing: "Spacing",
  typography: "Typography",
  effects: "Effects",
  motion: "Motion",
  semantic: "Semantic colours",
  aliases: "Component aliases",
  document: "Document & print",
  "doc-aliases": "Document aliases",
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DocsComponent {
  /** Canonical component name (from the manifest). */
  name: string;
  /** Registry layer directory the component lives in. */
  layer: Layer;
  /** The component's manifest. */
  manifest: Manifest;
  /** Absolute path to the reference `.html` fragment (may not exist). */
  referencePath: string;
  /** Site-relative path of this component's documentation page. */
  pagePath: string;
  /** Site-relative path of this component's standalone live example page. */
  examplePath: string;
}

export interface SiteFile {
  /** Path relative to the output directory, using `/` separators. */
  path: string;
  content: string;
}

export interface DocsSiteOptions {
  /** Registry root to document. Defaults to `<package>/registry`. */
  registryRoot?: string;
  /** Authored site sources (`site.config.json`, `content/`). Defaults to `<package>/site`. */
  siteRoot?: string;
  /** Theme stylesheet baked into the site bundle. Defaults to the site config's theme. */
  theme?: string;
}

export interface SiteConfig {
  title: string;
  tagline: string;
  description: string;
  theme: string;
  footer: string;
}

const DEFAULT_SITE_CONFIG: SiteConfig = {
  title: "Faqir UI",
  tagline: "The agent-native UI framework",
  description: "Manifest-driven, zero-dependency UI components documented from their own manifests.",
  theme: "default",
  footer: "Faqir UI — every page on this site is generated from the registry manifests.",
};

// ---------------------------------------------------------------------------
// Small HTML helpers
// ---------------------------------------------------------------------------

/** Escape text for HTML body content. */
export function esc(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Escape a value for a double-quoted attribute. */
export function escAttr(value: string): string {
  return esc(value).replace(/"/g, "&quot;");
}

/** `data-part="x"` → a filesystem/anchor-safe slug. */
function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

/**
 * A relative URL from one site page to another site path. Both arguments are
 * site-relative (`components/primitives/button.html`), so the whole site is
 * position-independent: it works at a domain root, in a sub-directory, or from
 * `file://` — which is what "served with any static server" means in practice.
 */
export function relUrl(fromPagePath: string, toPath: string): string {
  const depth = fromPagePath.split("/").length - 1;
  return depth === 0 ? toPath : "../".repeat(depth) + toPath;
}

// ---------------------------------------------------------------------------
// Registry reading (node:fs only)
// ---------------------------------------------------------------------------

function readText(path: string): string {
  return readFileSync(path, "utf8");
}

/** Every `.css` file under a directory tree, sorted for deterministic output. */
function walkCss(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walkCss(full, out);
    else if (entry.endsWith(".css")) out.push(full);
  }
  return out;
}

/**
 * Every documentable component in a registry, sorted by (layer order, name).
 * The manifest is the source of truth — a directory without one is not a
 * component and is skipped, which is what keeps `registry/tokens/density.html`
 * and the theme previews out of the site.
 */
export function discoverDocsComponents(registryRoot: string): DocsComponent[] {
  const found: DocsComponent[] = [];
  for (const layer of LAYERS) {
    const base = join(registryRoot, layer);
    if (!existsSync(base)) continue;
    for (const entry of readdirSync(base).sort()) {
      const dir = join(base, entry);
      if (!statSync(dir).isDirectory()) continue;
      const manifestPath = join(dir, `${entry}.manifest.json`);
      if (!existsSync(manifestPath)) continue;
      const manifest = JSON.parse(readText(manifestPath)) as Manifest;
      const name = manifest.name ?? entry;
      found.push({
        name,
        layer,
        manifest,
        referencePath: join(dir, manifest.files?.html ?? `${entry}.html`),
        pagePath: `components/${layer}/${name}.html`,
        examplePath: `examples/${layer}/${name}.html`,
      });
    }
  }
  return found;
}

// ---------------------------------------------------------------------------
// Reference fragments
// ---------------------------------------------------------------------------

/**
 * A deterministic 96×96 grey placeholder. Reference fragments point `<img>` at
 * `example.com` URLs; a static docs site must never reach the network, so every
 * non-`data:` source is swapped for this inline SVG. Identical to the swap the
 * visual/a11y harness performs, for the same reason.
 */
const IMG_PLACEHOLDER =
  "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20width='96'%20height='96'%3E%3Crect%20width='96'%20height='96'%20fill='%23c7c7c7'/%3E%3C/svg%3E";

/** Strip `@ui:*` authoring comments and neutralise external image sources. */
export function sanitizeReferenceFragment(html: string): string {
  return html
    .replace(/<!--\s*@ui:[^]*?-->/g, "")
    .replace(/(\bsrc\s*=\s*)(["'])(?!\s*data:)[^"']*\2/gi, `$1$2${IMG_PLACEHOLDER}$2`)
    .trim();
}

/** Does a fragment declare its own `main` landmark (patterns often do)? */
function hasOwnMain(fragment: string): boolean {
  return /<main[\s>]/i.test(fragment) || /role\s*=\s*["']main["']/i.test(fragment);
}

/**
 * Does a fragment contain dialog-class markup? The framework's `landmark` rule
 * requires overlays to sit outside the main content flow, so such a fragment is
 * mounted as a sibling of `<main>` rather than inside it.
 */
function hasDialog(fragment: string): boolean {
  return (
    /<dialog[\s>]/i.test(fragment) ||
    /data-ui\s*=\s*["']dialog["']/i.test(fragment) ||
    /role\s*=\s*["'](?:dialog|alertdialog)["']/i.test(fragment)
  );
}

// ---------------------------------------------------------------------------
// Token reference
// ---------------------------------------------------------------------------

export interface TokenEntry {
  /** Token name without the leading `--`. */
  name: string;
  /** Declared value, verbatim. */
  value: string;
  /** Token file the canonical declaration came from. */
  group: string;
}

const ROOT_BLOCK_RE = /:root\s*\{([^}]*)\}/g;
const DECL_RE = /--([a-z0-9-]+)\s*:\s*([^;]+);/gi;

/**
 * Every `:root` custom property the registry declares, in cascade order,
 * first-declaration-wins. Only `:root` blocks are read: a `[data-theme="dark"]`
 * or `[data-density]` block re-declares tokens for a scope, and the reference
 * documents the token, not each of its scoped values.
 */
export function parseTokenReference(registryRoot: string): TokenEntry[] {
  const seen = new Map<string, TokenEntry>();
  for (const file of TOKEN_FILES) {
    const path = join(registryRoot, "tokens", `${file}.css`);
    if (!existsSync(path)) continue;
    const css = readText(path).replace(/\/\*[^]*?\*\//g, "");
    for (const block of css.matchAll(ROOT_BLOCK_RE)) {
      for (const decl of block[1].matchAll(DECL_RE)) {
        const name = decl[1];
        if (seen.has(name)) continue;
        seen.set(name, { name, value: decl[2].trim(), group: file });
      }
    }
  }
  return [...seen.values()];
}

/** Is this token's value paintable — i.e. worth a colour swatch? */
function isColorToken(entry: TokenEntry): boolean {
  return (
    /^(?:oklch|rgb|hsl|color-mix)\(/i.test(entry.value) ||
    /^#[0-9a-f]{3,8}$/i.test(entry.value) ||
    (/^var\(--color-/i.test(entry.value) && !/shadow/i.test(entry.name))
  );
}

/** Anchor id for a token on the token-reference page. */
export function tokenAnchor(name: string): string {
  return `token-${slug(name)}`;
}

// ---------------------------------------------------------------------------
// Page shell
// ---------------------------------------------------------------------------

interface ShellInput {
  /** Site-relative path of the page being rendered (drives every relative URL). */
  pagePath: string;
  title: string;
  description: string;
  /** Main-content HTML, already escaped/assembled. */
  body: string;
  config: SiteConfig;
  components: DocsComponent[];
  /** Nav entry that should carry `aria-current="page"`. */
  current: string;
}

/**
 * The navigation shell every site page shares: the `dashboard-shell` pattern,
 * with the sidebar listing every component grouped by layer. It is generated
 * from the same component list the pages are, so a new component appears in the
 * nav of all 80-odd pages without a site edit.
 *
 * The sidebar deliberately carries **no** `data-state`. Below dashboard-shell's
 * 768px breakpoint the pattern turns it into an off-canvas drawer that only
 * `data-state="expanded"` slides in, so pinning it open would park the whole
 * component list on top of the content on a phone. Left at its default it is a
 * column on desktop and steps aside on mobile, where the header nav and the
 * component index carry navigation (the site ships no JavaScript of its own, so
 * there is no drawer toggle to offer).
 */
function renderShell(input: ShellInput): string {
  const { pagePath, config, components, current } = input;
  const u = (to: string) => escAttr(relUrl(pagePath, to));
  const currentAttr = (key: string) => (key === current ? ' aria-current="page"' : "");

  const groups = LAYERS.map((layer) => ({
    layer,
    items: components.filter((c) => c.layer === layer),
  })).filter((g) => g.items.length > 0);

  const navGroups = groups
    .map(
      (g) =>
        `        <h2 data-ui="text" data-size="xs" data-variant="subtle" data-weight="semibold">${esc(
          LAYER_LABEL[g.layer],
        )}</h2>\n` +
        g.items
          .map(
            (c) =>
              `        <a data-part="nav-item" href="${u(c.pagePath)}"${currentAttr(
                c.pagePath,
              )}>${esc(c.name)}</a>`,
          )
          .join("\n"),
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en" data-theme="auto">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escAttr(input.title)}</title>
<meta name="description" content="${escAttr(input.description)}">
<link rel="stylesheet" href="${u("styles/faqir.css")}">
<!-- ${DOCS_GENERATION_MARKER} · regenerate with \`bun run build:docs\` · do not edit by hand -->
</head>
<body>
<div data-ui="dashboard-shell">

  <aside data-part="sidebar">
    <a data-part="logo" href="${u("index.html")}"><span>${esc(config.title)}</span></a>
    <hr data-ui="separator">
    <nav data-part="nav" role="navigation" aria-label="Documentation">
      <a data-part="nav-item" href="${u("index.html")}"${currentAttr("index.html")}>Overview</a>
      <a data-part="nav-item" href="${u("components/index.html")}"${currentAttr(
        "components/index.html",
      )}>All components</a>
      <a data-part="nav-item" href="${u("tokens/index.html")}"${currentAttr(
        "tokens/index.html",
      )}>Design tokens</a>
      <hr data-ui="separator">
${navGroups}
    </nav>
  </aside>

  <header data-part="header" role="banner">
    <a data-ui="link" href="${u("index.html")}"><strong>${esc(config.title)}</strong></a>
    <nav data-ui="nav" aria-label="Site sections">
      <a data-part="link" href="${u("components/index.html")}">Components</a>
      <a data-part="link" href="${u("tokens/index.html")}">Tokens</a>
    </nav>
  </header>

  <main data-part="content" role="main">
    <article data-ui="prose" style="max-width: 72rem;">
${input.body}
    </article>
  </main>

  <footer data-part="footer">
    <span>${esc(config.footer)}</span>
  </footer>

</div>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Manifest-derived sections
// ---------------------------------------------------------------------------

/** A `<table>` with a header row, or an italic note when there is nothing to show. */
function table(headers: string[], rows: string[][], emptyNote: string): string {
  if (rows.length === 0) return `      <p><em>${esc(emptyNote)}</em></p>`;
  const head = headers.map((h) => `<th scope="col">${esc(h)}</th>`).join("");
  const body = rows
    .map((r) => `        <tr>${r.map((cell) => `<td>${cell}</td>`).join("")}</tr>`)
    .join("\n");
  return `      <table>\n        <thead><tr>${head}</tr></thead>\n        <tbody>\n${body}\n        </tbody>\n      </table>`;
}

function code(value: string): string {
  return `<code>${esc(value)}</code>`;
}

/**
 * A monospaced link. Deliberately NOT `<a><code>…</code></a>`: prose gives
 * `code` a `--color-bg-muted` plate and no colour of its own, so a code element
 * inside a link renders `--color-primary` on `--color-bg-muted` — 4.41:1 in the
 * default dark scheme, just under AA (caught by the site's own axe gate). The
 * `text` primitive's `mono` variant supplies the typeface and nothing else, so
 * the link keeps its own colour on the page background.
 */
function monoLink(href: string, label: string): string {
  return (
    `<a data-ui="link" href="${escAttr(href)}">` +
    `<span data-ui="text" data-variant="mono">${esc(label)}</span></a>`
  );
}

/**
 * The anatomy tree: the root element followed by every named slot, annotated
 * with its tag hint and required-ness. Same shape the generated skill renders,
 * so an agent reading the docs and an agent reading the skill see one anatomy.
 */
export function renderAnatomyTree(m: Manifest): string {
  const lines: string[] = [];
  const content = m.anatomy?.content_model ? `  ·  content: ${m.anatomy.content_model}` : "";
  lines.push(`${m.anatomy?.selector ?? ""}  ·  <${m.anatomy?.tag ?? "div"}>${content}`);
  const slots = Object.entries(m.slots ?? {});
  slots.forEach(([, slot], i) => {
    const branch = i === slots.length - 1 ? "└─" : "├─";
    const tag = slot.tag_hint ? ` <${slot.tag_hint}>` : "";
    const req = slot.required ? "required" : "optional";
    lines.push(`${branch} ${slot.selector}${tag}  ${req}`);
  });
  return `      <pre tabindex="0"><code>${esc(lines.join("\n"))}</code></pre>`;
}

function renderSlotTable(m: Manifest): string {
  const rows = Object.entries(m.slots ?? {}).map(([name, slot]) => [
    code(name),
    code(slot.selector),
    slot.tag_hint ? code(`<${slot.tag_hint}>`) : "—",
    slot.required ? "required" : "optional",
    esc(slot.description ?? ""),
  ]);
  return table(
    ["Slot", "Selector", "Tag hint", "Required", "Description"],
    rows,
    "This component has no named slots — its content model is its anatomy.",
  );
}

function renderVariantTable(m: Manifest): string {
  const rows = Object.entries(m.variants ?? {}).map(([name, v]) => [
    esc(name),
    code(v.attr),
    v.values.map((value) => code(`${v.attr}="${value}"`)).join(" "),
    code(v.default),
    code(v.applied_to ?? "root"),
  ]);
  return table(
    ["Variant", "Attribute", "Values", "Default", "Applied to"],
    rows,
    "This component has no variants.",
  );
}

function renderStateTable(m: Manifest): string {
  const rows = Object.entries(m.states ?? {}).map(([name, s]) => [
    esc(name),
    s.attr ? code(s.attr) : "—",
    s.default ? "yes" : "no",
    code(s.applied_to ?? "root"),
    esc(s.description ?? ""),
  ]);
  return table(
    ["State", "Attribute", "Default", "Applied to", "Description"],
    rows,
    "This component declares no states.",
  );
}

function renderA11yTable(m: Manifest): string {
  const a = m.a11y ?? {};
  const rows: string[][] = [];
  if (a.role) rows.push(["Role", code(a.role)]);
  if (a["aria-modal"]) rows.push(["Modal", code('aria-modal="true"')]);
  if (a.focus_trap) rows.push(["Focus trap", "yes — focus is confined while open"]);
  if (a.escape_closes) rows.push(["Escape", "closes the component"]);
  if (a.return_focus) rows.push(["Return focus", esc(a.return_focus)]);
  if (a.required_attrs?.length) {
    rows.push(["Required ARIA", a.required_attrs.map((x) => code(x)).join("<br>")]);
  }
  for (const [key, action] of Object.entries(a.keyboard ?? {})) {
    rows.push([code(key), esc(action)]);
  }
  return table(
    ["Requirement", "Contract"],
    rows,
    "No component-specific accessibility contract — standard semantics apply.",
  );
}

function renderTokenList(m: Manifest, tokens: Map<string, TokenEntry>, pagePath: string): string {
  const used = m.tokens_used ?? [];
  if (used.length === 0) return `      <p><em>This component declares no design tokens.</em></p>`;
  const items = used
    .map((name) => {
      if (!tokens.has(name)) return `<li>${code(`--${name}`)}</li>`;
      const href = `${relUrl(pagePath, "tokens/index.html")}#${tokenAnchor(name)}`;
      return `<li>${monoLink(href, `--${name}`)}</li>`;
    })
    .join("\n        ");
  return `      <ul>\n        ${items}\n      </ul>`;
}

function renderTemplates(m: Manifest): string {
  const entries = Object.entries(m.templates ?? {});
  if (entries.length === 0) return `      <p><em>No canonical template recorded.</em></p>`;
  return entries
    .map(
      ([key, tpl]) =>
        `      <h3>${esc(key)}</h3>\n      <pre tabindex="0"><code>${esc(String(tpl))}</code></pre>`,
    )
    .join("\n");
}

function renderTransforms(m: Manifest): string {
  const safe = m.safe_transforms ?? [];
  const unsafe = m.unsafe_transforms ?? [];
  const parts: string[] = [];
  parts.push(`      <h3>Safe transforms</h3>`);
  parts.push(
    safe.length
      ? `      <ul>\n        ${safe.map((t) => `<li>${code(t)}</li>`).join("\n        ")}\n      </ul>`
      : `      <p><em>None recorded.</em></p>`,
  );
  parts.push(`      <h3>Never do this</h3>`);
  parts.push(
    unsafe.length
      ? `      <ul>\n        ${unsafe.map((t) => `<li>${code(t)}</li>`).join("\n        ")}\n      </ul>`
      : `      <p><em>None recorded.</em></p>`,
  );
  return parts.join("\n");
}

function renderComposition(
  m: Manifest,
  byName: Map<string, DocsComponent>,
  pagePath: string,
): string {
  const link = (name: string): string => {
    const target = byName.get(name);
    if (!target) return code(name);
    return monoLink(relUrl(pagePath, target.pagePath), name);
  };
  const contains = m.composition?.contains ?? [];
  const usedIn = m.composition?.used_in ?? [];
  const rows: string[][] = [
    ["Composes", contains.length ? contains.map(link).join(", ") : "—"],
    ["Used in", usedIn.length ? usedIn.map(link).join(", ") : "—"],
  ];
  return table(["Relationship", "Components"], rows, "No composition recorded.");
}

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

function section(id: string, heading: string, body: string): string {
  return `      <h2 id="${escAttr(id)}">${esc(heading)}</h2>\n${body}`;
}

function metaBadges(c: DocsComponent): string {
  const m = c.manifest;
  const badge = (variant: string, text: string) =>
    `<span data-ui="badge" data-variant="${escAttr(variant)}">${esc(text)}</span>`;
  const kindVariant = m.kind === "primitive" ? "primary" : m.kind === "recipe" ? "secondary" : "success";
  return (
    `      <p>${badge(kindVariant, m.kind)} ${badge("default", m.category ?? "uncategorised")} ` +
    `${badge("default", `v${m.version ?? "1.0.0"}`)}${
      m.files?.js ? ` ${badge("warning", m.files.js)}` : ""
    }</p>`
  );
}

/** One component's documentation page — every section derived from its manifest. */
function renderComponentPage(
  c: DocsComponent,
  ctx: {
    config: SiteConfig;
    components: DocsComponent[];
    byName: Map<string, DocsComponent>;
    tokens: Map<string, TokenEntry>;
    hasExample: boolean;
  },
): SiteFile {
  const m = c.manifest;
  const exampleUrl = escAttr(relUrl(c.pagePath, c.examplePath));

  const live = ctx.hasExample
    ? `      <p>The frame below is this component's registry reference page — the canonical, ` +
      `authored demonstration of its variants and states, rendered live with the site's own stylesheet. ` +
      `<a data-ui="link" href="${exampleUrl}">Open it on its own page</a>.</p>\n` +
      `      <iframe src="${exampleUrl}" title="${escAttr(
        `${c.name} live example`,
      )}" loading="lazy" style="inline-size: 100%; block-size: 24rem; resize: vertical; border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-bg);"></iframe>`
    : `      <p><em>No reference page ships with this component.</em></p>`;

  const body = [
    `      <h1>${esc(c.name)}</h1>`,
    metaBadges(c),
    `      <p>${esc(m.description ?? "")}</p>`,
    m.aliases?.length
      ? `      <p>Also available as ${m.aliases.map((a) => code(a)).join(", ")}.</p>`
      : "",
    section("live-example", "Live example", live),
    section("anatomy", "Anatomy", renderAnatomyTree(m) + "\n" + renderSlotTable(m)),
    section("variants", "Variant matrix", renderVariantTable(m)),
    section("states", "States", renderStateTable(m)),
    section("accessibility", "Accessibility", renderA11yTable(m)),
    section("tokens", "Design tokens", renderTokenList(m, ctx.tokens, c.pagePath)),
    section("templates", "Templates", renderTemplates(m)),
    section("transforms", "Transforms", renderTransforms(m)),
    section("composition", "Composition", renderComposition(m, ctx.byName, c.pagePath)),
  ]
    .filter(Boolean)
    .join("\n");

  return {
    path: c.pagePath,
    content: renderShell({
      pagePath: c.pagePath,
      title: `${c.name} · ${ctx.config.title}`,
      description: m.description ?? `${c.name} — a Faqir ${m.kind}.`,
      body,
      config: ctx.config,
      components: ctx.components,
      current: c.pagePath,
    }),
  };
}

/** The component index: every component as a card, grouped by layer. */
function renderComponentIndex(ctx: {
  config: SiteConfig;
  components: DocsComponent[];
}): SiteFile {
  const pagePath = "components/index.html";
  const parts: string[] = [
    `      <h1>Components</h1>`,
    `      <p>${esc(
      `${ctx.components.length} components, every one documented from its own manifest.`,
    )}</p>`,
  ];

  for (const layer of LAYERS) {
    const items = ctx.components.filter((c) => c.layer === layer);
    if (items.length === 0) continue;
    parts.push(`      <h2 id="${layer}">${esc(LAYER_LABEL[layer])} (${items.length})</h2>`);
    parts.push(`      <p>${esc(LAYER_BLURB[layer])}</p>`);
    parts.push(`      <div data-ui="grid" data-cols="3" data-gap="4">`);
    for (const c of items) {
      const href = escAttr(relUrl(pagePath, c.pagePath));
      parts.push(
        `        <div data-ui="card">\n` +
          `          <div data-part="header">\n` +
          `            <h3 data-part="title"><a data-ui="link" href="${href}">${esc(c.name)}</a></h3>\n` +
          `            <p data-part="description">${esc(c.manifest.category ?? "")}</p>\n` +
          `          </div>\n` +
          `          <div data-part="body">${esc(c.manifest.description ?? "")}</div>\n` +
          `        </div>`,
      );
    }
    parts.push(`      </div>`);
  }

  return {
    path: pagePath,
    content: renderShell({
      pagePath,
      title: `Components · ${ctx.config.title}`,
      description: `Every component in the Faqir registry, grouped by layer.`,
      body: parts.join("\n"),
      config: ctx.config,
      components: ctx.components,
      current: pagePath,
    }),
  };
}

/** The token reference: every `:root` custom property the registry declares. */
function renderTokenPage(ctx: {
  config: SiteConfig;
  components: DocsComponent[];
  tokenList: TokenEntry[];
}): SiteFile {
  const pagePath = "tokens/index.html";
  const parts: string[] = [
    `      <h1>Design tokens</h1>`,
    `      <p>${esc(
      `${ctx.tokenList.length} custom properties. Every component styles itself from these — ` +
        `a theme re-declares them, and the whole registry restyles.`,
    )}</p>`,
  ];

  const groups = [...new Set(ctx.tokenList.map((t) => t.group))];
  for (const group of groups) {
    const entries = ctx.tokenList.filter((t) => t.group === group);
    parts.push(
      `      <h2 id="${escAttr(`group-${slug(group)}`)}">${esc(
        TOKEN_GROUP_LABEL[group] ?? group,
      )} (${entries.length})</h2>`,
    );
    const rows = entries.map((t) => {
      const swatch = isColorToken(t)
        ? `<span style="display: inline-block; inline-size: 1.25rem; block-size: 1.25rem; vertical-align: middle; border: 1px solid var(--color-border); border-radius: var(--radius-sm); background: var(--${t.name});"></span>`
        : "—";
      return [
        `<code id="${escAttr(tokenAnchor(t.name))}">--${esc(t.name)}</code>`,
        code(t.value),
        swatch,
      ];
    });
    parts.push(table(["Token", "Value", "Sample"], rows, "No tokens in this group."));
  }

  return {
    path: pagePath,
    content: renderShell({
      pagePath,
      title: `Design tokens · ${ctx.config.title}`,
      description: "Every design token the Faqir registry declares, with its default value.",
      body: parts.join("\n"),
      config: ctx.config,
      components: ctx.components,
      current: pagePath,
    }),
  };
}

/** The home page: the authored fragment, followed by generated registry stats. */
function renderHomePage(ctx: {
  config: SiteConfig;
  components: DocsComponent[];
  authored: string;
  tokenCount: number;
  themeCount: number;
}): SiteFile {
  const pagePath = "index.html";
  const counts = LAYERS.map((layer) => ({
    layer,
    n: ctx.components.filter((c) => c.layer === layer).length,
  })).filter((g) => g.n > 0);

  const stats =
    `      <h2 id="registry">The registry at a glance</h2>\n` +
    `      <div data-ui="grid" data-cols="3" data-gap="4">\n` +
    counts
      .map(
        (g) =>
          `        <div data-ui="card">\n` +
          `          <div data-part="header">\n` +
          `            <h3 data-part="title"><a data-ui="link" href="${escAttr(
            `components/index.html#${g.layer}`,
          )}">${esc(LAYER_LABEL[g.layer])}</a></h3>\n` +
          `            <p data-part="description">${esc(String(g.n))} components</p>\n` +
          `          </div>\n` +
          `          <div data-part="body">${esc(LAYER_BLURB[g.layer])}</div>\n` +
          `        </div>`,
      )
      .join("\n") +
    `\n      </div>\n` +
    `      <p>Backed by <a data-ui="link" href="tokens/index.html">${esc(
      String(ctx.tokenCount),
    )} design tokens</a> and ${esc(String(ctx.themeCount))} themes. ` +
    `Every page you are reading was generated from the same manifests an agent reads.</p>`;

  const body = [ctx.authored, stats].filter(Boolean).join("\n");

  return {
    path: pagePath,
    content: renderShell({
      pagePath,
      title: `${ctx.config.title} · ${ctx.config.tagline}`,
      description: ctx.config.description,
      body,
      config: ctx.config,
      components: ctx.components,
      current: pagePath,
    }),
  };
}

/**
 * A standalone live-example page: the component's registry reference fragment,
 * verbatim, in a minimal document that links the site stylesheet and loads the
 * registry engine so recipe controllers actually run.
 *
 * Landmark placement is decided from the fragment itself, never from a
 * per-component list: a fragment that declares its own `main` is mounted as-is,
 * a fragment carrying dialog-class markup is mounted beside `<main>` (overlays
 * belong outside the content flow), and everything else is wrapped in `<main>`.
 */
function renderExamplePage(c: DocsComponent, config: SiteConfig): SiteFile | null {
  if (!existsSync(c.referencePath)) return null;
  const fragment = sanitizeReferenceFragment(readText(c.referencePath));
  const u = (to: string) => escAttr(relUrl(c.examplePath, to));

  let mounted: string;
  if (hasOwnMain(fragment)) {
    mounted = fragment;
  } else if (hasDialog(fragment)) {
    mounted =
      `<main>\n<p>Live reference example: <code>${esc(c.name)}</code>. ` +
      `Overlay markup is mounted outside the main landmark, where it belongs.</p>\n</main>\n${fragment}`;
  } else {
    mounted = `<main>\n${fragment}\n</main>`;
  }

  return {
    path: c.examplePath,
    content: `<!DOCTYPE html>
<html lang="en" data-theme="auto">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escAttr(`${c.name} example · ${config.title}`)}</title>
<link rel="stylesheet" href="${u("styles/faqir.css")}">
<script src="${u("scripts/faqir-core.js")}" defer></script>
<!-- ${DOCS_GENERATION_MARKER} · verbatim registry reference markup for ${escAttr(c.name)} -->
</head>
<body>
${mounted}
</body>
</html>
`,
  };
}

// ---------------------------------------------------------------------------
// Stylesheet
// ---------------------------------------------------------------------------

/**
 * The site stylesheet: tokens, base, theme, then every component stylesheet —
 * the same cascade order `faqir init` installs. One file, one `<link>`, so a
 * page works from any directory depth and any static host.
 */
export function buildSiteStylesheet(registryRoot: string, theme: string): string {
  const parts: string[] = [`/* ${DOCS_GENERATION_MARKER} — do not edit by hand */`];

  parts.push("/* ── tokens ── */");
  for (const name of TOKEN_FILES) {
    const path = join(registryRoot, "tokens", `${name}.css`);
    if (!existsSync(path)) continue;
    parts.push(
      readText(path)
        .split("\n")
        .filter((line) => !line.startsWith("@import"))
        .join("\n"),
    );
  }

  parts.push("/* ── base ── */");
  for (const name of BASE_FILES) {
    const path = join(registryRoot, "base", `${name}.css`);
    if (existsSync(path)) parts.push(readText(path));
  }

  const themePath = join(registryRoot, "themes", `${theme}.css`);
  if (existsSync(themePath)) {
    parts.push(`/* ── theme: ${theme} ── */`);
    parts.push(readText(themePath));
  }

  parts.push("/* ── components ── */");
  for (const layer of LAYERS) {
    const base = join(registryRoot, layer);
    if (!existsSync(base)) continue;
    for (const file of walkCss(base)) parts.push(readText(file));
  }

  return parts.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/** Read `site/site.config.json`, falling back to the built-in defaults. */
export function readSiteConfig(siteRoot: string): SiteConfig {
  const path = join(siteRoot, "site.config.json");
  if (!existsSync(path)) return { ...DEFAULT_SITE_CONFIG };
  return { ...DEFAULT_SITE_CONFIG, ...(JSON.parse(readText(path)) as Partial<SiteConfig>) };
}

/**
 * Build the whole docs site in memory. Pure with respect to the output: it reads
 * the registry and the authored `site/` sources and returns every file, so tests
 * can assert on the site without touching a directory, and `build:docs` is a thin
 * "write these files" wrapper.
 */
export function buildDocsSite(options: DocsSiteOptions = {}): SiteFile[] {
  const registryRoot = options.registryRoot ?? join(PACKAGE_ROOT, "registry");
  const siteRoot = options.siteRoot ?? join(PACKAGE_ROOT, "site");
  const config = readSiteConfig(siteRoot);
  const theme = options.theme ?? config.theme;

  const components = discoverDocsComponents(registryRoot);
  // A name can exist in two layers (`empty-state` is both a primitive and a
  // pattern), so page paths are layer-scoped and this lookup — used only to link
  // `composition.contains`/`used_in`, which name a component without its layer —
  // resolves to the first match in layer order (primitive wins).
  const byName = new Map<string, DocsComponent>();
  for (const c of components) if (!byName.has(c.name)) byName.set(c.name, c);
  const tokenList = parseTokenReference(registryRoot);
  const tokens = new Map(tokenList.map((t) => [t.name, t]));

  const themesDir = join(registryRoot, "themes");
  const themeCount = existsSync(themesDir)
    ? readdirSync(themesDir).filter((f) => f.endsWith(".css") && !f.endsWith(".preview.css")).length
    : 0;

  const files: SiteFile[] = [];

  // Example pages first — a component page links its example, and only emits the
  // frame when one was actually produced.
  const examples = new Map<string, SiteFile>();
  for (const c of components) {
    const example = renderExamplePage(c, config);
    if (example) examples.set(c.examplePath, example);
  }

  const authoredHome = join(siteRoot, "content", "home.html");
  files.push(
    renderHomePage({
      config,
      components,
      authored: existsSync(authoredHome) ? readText(authoredHome).trim() : "",
      tokenCount: tokenList.length,
      themeCount,
    }),
  );
  files.push(renderComponentIndex({ config, components }));
  files.push(renderTokenPage({ config, components, tokenList }));

  for (const c of components) {
    files.push(
      renderComponentPage(c, {
        config,
        components,
        byName,
        tokens,
        hasExample: examples.has(c.examplePath),
      }),
    );
  }
  files.push(...examples.values());

  files.push({ path: "styles/faqir.css", content: buildSiteStylesheet(registryRoot, theme) });

  const corePath = join(registryRoot, "core", "faqir-core.js");
  if (existsSync(corePath)) {
    files.push({ path: "scripts/faqir-core.js", content: readText(corePath) });
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

/** Site-relative path prefix under which pages carry verbatim registry markup. */
export const EXAMPLE_PREFIX = "examples/";

/** True for the pages this generator authors end-to-end (the audit/axe gate set). */
export function isSitePage(path: string): boolean {
  return path.endsWith(".html") && !path.startsWith(EXAMPLE_PREFIX);
}

/** True for the pages that wrap a registry reference fragment verbatim. */
export function isExamplePage(path: string): boolean {
  return path.endsWith(".html") && path.startsWith(EXAMPLE_PREFIX);
}
