// Manifest-derived Claude Code skill generator (task 0.5-07, FAQIR-PLAN §8.2).
//
// Replaces the old static SKILL.md template. Every per-component section —
// anatomy tree, variant table, safe/unsafe transforms — plus the canonical
// compositions are DERIVED from manifests, so the shipped `faqir-creator` skill
// is regenerated from this same pipeline (dogfood) and never hand-maintained.
//
// Two entry points share one set of renderers:
//   • generateSkill(cwd)          → a project's self-contained .faqir/SKILL.md,
//                                    scoped to its installed component set.
//   • generateShippedSkillFiles() → the registry-wide .claude/skills/faqir-creator
//                                    skill (SKILL.md + per-layer references),
//                                    covering every component in registry/.
//
// Output carries a grep-able generation header and no timestamps, so
// regeneration is byte-idempotent (gated by `bun run check:skill`).

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { readConfig } from "../utils/config";
import { ensureDir, getPackageRoot, getRegistryPath } from "../utils/fs";
import { loadManifest, type Manifest } from "../manifest";
import { BREAKPOINTS, BREAKPOINT_LIST, TIERS, responsiveAttribute } from "../utils/breakpoints";
import {
  ARCHETYPES,
  LAYOUT_MECHANISMS,
  LAYOUT_PRIMITIVES,
  LAYOUT_RULES,
  MEASURE_TOKENS,
  RHYTHM_TOKENS,
  SPACING_BANDS,
  grammarLine,
  rhythmLine,
  spacingLadderLine,
} from "../utils/layout";
import { TOKEN_MODIFIERS } from "../protocol";
import { COMMAND_CATEGORIES, commandsInCategory } from "../command-registry";
import { DOCUMENT_SCAFFOLD_NAMES, SCAFFOLDS } from "../scaffolds/registry";
import type { ThemeManifest } from "../theme-manifest";
import { getSchemaVersion, loadManifestSchema } from "../utils/schema";
import { loadPluginMetadata, type PluginMetadata } from "./plugins";

/** Stable, grep-able marker proving a file came out of this generator. */
export const SKILL_GENERATION_MARKER = "GENERATED by faqir · manifest-derived skill";

const LAYERS = ["primitives", "recipes", "patterns"] as const;
type Layer = (typeof LAYERS)[number];

/**
 * The generation header stamped into every generated file. No timestamp — the
 * only variable is `schema_version`, so identical inputs produce identical bytes.
 */
function generationHeader(schemaVersion: string): string {
  return (
    `<!-- ${SKILL_GENERATION_MARKER} · schema_version ${schemaVersion} · ` +
    `regenerate with \`bun run gen:skill\` · do not edit by hand -->`
  );
}

/** Turn `date-picker` into `createDatePicker` (recipe controller factory). */
function factoryName(recipe: string): string {
  return "create" + recipe.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
}

// ---------------------------------------------------------------------------
// Per-component renderers (manifest-derived)
// ---------------------------------------------------------------------------

/**
 * Render a component's anatomy tree: the root element followed by its named
 * slots, each annotated with its tag hint, required-ness, and description.
 * Derived entirely from `anatomy` + `slots`.
 */
function renderAnatomyTree(m: Manifest): string[] {
  const lines: string[] = ["```text"];
  const content = m.anatomy.content_model ? ` · content: ${m.anatomy.content_model}` : "";
  lines.push(`${m.anatomy.selector}  ·  <${m.anatomy.tag}>${content}`);

  const slots = Object.entries(m.slots ?? {});
  slots.forEach(([name, slot], i) => {
    const branch = i === slots.length - 1 ? "└─" : "├─";
    const tag = slot.tag_hint ? `<${slot.tag_hint}>` : "";
    const req = slot.required ? "required" : "optional";
    const desc = slot.description ? `  — ${slot.description}` : "";
    // name is informational; the real contract is the selector.
    lines.push(`${branch} ${slot.selector}  ${tag}  ${req}${desc}`.replace(/\s+$/g, ""));
  });

  lines.push("```");
  return lines;
}

/**
 * Render a markdown variant table from `variants` (empty → a single note).
 *
 * A component declaring a responsive group (task 0.8-02) gains a Responsive
 * column plus one grammar line below the table, so an agent reading the skill
 * learns `data-cols-md="6"` from the manifest rather than from prose someone
 * remembered to write. Emitted only when a group declares it — the column is
 * absent, not dashed, everywhere else.
 */
function renderVariantTable(m: Manifest): string[] {
  const entries = Object.entries(m.variants ?? {});
  if (entries.length === 0) return ["_No variants._"];

  const responsiveGroups = entries.filter(([, v]) => v.responsive === true);
  const responsive = responsiveGroups.length > 0;
  const lines: string[] = responsive
    ? [
        "| Variant | Values | Default | Attribute | Applied to | Responsive |",
        "|---------|--------|---------|-----------|------------|------------|",
      ]
    : [
        "| Variant | Values | Default | Attribute | Applied to |",
        "|---------|--------|---------|-----------|------------|",
      ];
  for (const [name, v] of entries) {
    const values = v.values.map((x) => `\`${x}\``).join(", ");
    const row = `| ${name} | ${values} | \`${v.default}\` | \`${v.attr}\` | ${v.applied_to ?? "root"} |`;
    if (!responsive) {
      lines.push(row);
      continue;
    }
    const tiers =
      v.responsive === true ? TIERS.map((t) => `\`${responsiveAttribute(v.attr, t)}\``).join(", ") : "—";
    lines.push(`${row} ${tiers} |`);
  }
  if (responsive) {
    const example = responsiveGroups[0][1];
    lines.push("");
    lines.push(
      `- **Responsive:** the marked groups accept \`<attr>-<tier>\` for the canon tiers ` +
        `${TIERS.map((t) => `\`${t}\` (${BREAKPOINTS[t].rem}rem)`).join(", ")} — ` +
        `\`${responsiveAttribute(example.attr, "md")}="${example.values[example.values.length - 1]}"\` ` +
        `applies that value from \`md\` up. Mobile-first: the unsuffixed attribute is the base.`,
    );
  }
  return lines;
}

/** Render the safe / unsafe transform lists. */
function renderTransforms(m: Manifest): string[] {
  const lines: string[] = [];
  if (m.safe_transforms?.length) {
    lines.push(`- **Safe transforms:** ${m.safe_transforms.map((t) => `\`${t}\``).join(", ")}`);
  }
  if (m.unsafe_transforms?.length) {
    lines.push(`- **Unsafe (never do):** ${m.unsafe_transforms.map((t) => `\`${t}\``).join(", ")}`);
  }
  return lines;
}

/** One-line accessibility summary derived from `a11y`. */
function renderA11y(m: Manifest): string[] {
  const a = m.a11y;
  if (!a) return [];
  const parts: string[] = [];
  if (a.role) parts.push(`role=${a.role}`);
  if (a["aria-modal"]) parts.push("aria-modal");
  if (a.focus_trap) parts.push("focus-trap");
  if (a.escape_closes) parts.push("escape-closes");
  if (a.return_focus) parts.push(`return-focus→${a.return_focus}`);
  const keys = a.keyboard ? Object.keys(a.keyboard) : [];
  if (keys.length) parts.push(`keys: ${keys.join(", ")}`);
  if (parts.length === 0 && (!a.required_attrs || a.required_attrs.length === 0)) return [];
  const lines: string[] = [];
  if (parts.length) lines.push(`- **A11y:** ${parts.join(" · ")}`);
  if (a.required_attrs?.length) {
    lines.push(`- **Required ARIA:** ${a.required_attrs.map((x) => `\`${x}\``).join("; ")}`);
  }
  return lines;
}

/** The canonical HTML template for a component (first of `html`, else first key). */
function primaryTemplate(m: Manifest): string | undefined {
  const t = m.templates ?? {};
  if (typeof t.html === "string") return t.html;
  const first = Object.values(t)[0];
  return typeof first === "string" ? first : undefined;
}

/**
 * A full per-component reference section: heading, meta line, description,
 * canonical template, anatomy tree, variant table, transforms, and a11y.
 * `headingLevel` lets the caller nest it (### in references, #### inline).
 */
export function renderComponentSection(m: Manifest, headingLevel = 3): string[] {
  const h = "#".repeat(headingLevel);
  const lines: string[] = [];
  lines.push(`${h} ${m.name}`);
  lines.push("");
  const meta = [`kind: ${m.kind}`];
  if (m.category) meta.push(`category: ${m.category}`);
  if (m.aliases?.length) meta.push(`aliases: ${m.aliases.join(", ")}`);
  if (m.files?.js) meta.push(`controller: ${factoryName(m.name)}()`);
  lines.push(`_${meta.join(" · ")}_`);
  lines.push("");
  if (m.description) {
    lines.push(m.description);
    lines.push("");
  }

  const tpl = primaryTemplate(m);
  if (tpl) {
    lines.push("```html");
    lines.push(tpl);
    lines.push("```");
    lines.push("");
  }

  lines.push("**Anatomy**");
  lines.push("");
  lines.push(...renderAnatomyTree(m));
  lines.push("");

  lines.push("**Variants**");
  lines.push("");
  lines.push(...renderVariantTable(m));
  lines.push("");

  const transforms = renderTransforms(m);
  const a11y = renderA11y(m);
  if (transforms.length || a11y.length) {
    lines.push(...transforms);
    lines.push(...a11y);
    lines.push("");
  }

  return lines;
}

/**
 * Render up to `limit` canonical compositions from pattern manifests. A pattern
 * IS a canonical composition — its template wires primitives/recipes together
 * and `composition.contains` names them. Deterministic: patterns sorted by name.
 */
function renderCompositions(patterns: Manifest[], limit = 3): string[] {
  const chosen = [...patterns].sort((a, b) => a.name.localeCompare(b.name)).slice(0, limit);
  if (chosen.length === 0) return [];

  const lines: string[] = ["## Canonical Compositions", ""];
  lines.push(
    "Real component compositions, taken verbatim from pattern manifests. Each shows how primitives and recipes assemble into a working unit.",
  );
  lines.push("");
  for (const p of chosen) {
    lines.push(`### ${p.name}`);
    lines.push("");
    if (p.description) {
      lines.push(p.description);
      lines.push("");
    }
    const uses = p.composition?.contains ?? [];
    if (uses.length) {
      lines.push(`Composes: ${uses.map((u) => `\`${u}\``).join(", ")}`);
      lines.push("");
    }
    const tpl = primaryTemplate(p);
    if (tpl) {
      lines.push("```html");
      lines.push(tpl);
      lines.push("```");
      lines.push("");
    }
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Shared framework sections (constant — the DOM contract, not per-component)
// ---------------------------------------------------------------------------

function renderAttributeProtocol(): string[] {
  return [
    "## The Attribute Protocol",
    "",
    "Every Faqir component uses exactly five data attributes — this is the DOM contract.",
    "",
    "| Attribute | Purpose | Example |",
    "|-----------|---------|---------|",
    "| `data-ui` | Component identity (root) | `data-ui=\"button\"` |",
    "| `data-part` | Named slot within parent | `data-part=\"trigger\"` |",
    "| `data-state` | Runtime state (JS-only) | `data-state=\"open\"` |",
    "| `data-variant` | Visual variant (set once) | `data-variant=\"primary\"` |",
    "| `data-size` | Size variant | `data-size=\"lg\"` |",
    "",
    "CSS targets attributes (`[data-ui=\"button\"]`), state via `[data-state=\"open\"]`, theme via `data-theme` on `<html>`. Every value comes from a `--token`.",
    "",
  ];
}

function renderStrictRules(): string[] {
  return [
    "## Strict Rules",
    "",
    "1. **NEVER** use `class=` attributes. Use `data-ui`/`data-variant`/`data-size`/`data-state`/`data-part`.",
    "2. **NEVER** hardcode colors, spacing, or sizes. Use `var(--token-name)`.",
    "3. **NEVER** use `!important`.",
    "4. **NEVER** use IDs as CSS selectors. IDs are for ARIA relationships only.",
    "5. CSS selectors **MUST** be attribute selectors: `[data-ui=\"button\"]`, not `.btn`.",
    "6. `data-state` is the **ONLY** attribute JS may modify at runtime.",
    "7. Always add the ARIA attributes each manifest requires.",
    "8. Recipes auto-initialize — include `faqir-core.js` and emit the full inner structure.",
    "",
  ];
}

/**
 * The layout system (task 0.8-12): the doctrine, the five primitives, the
 * ladder and the grammar. Authored prose lives in `src/utils/layout.ts` and the
 * numbers in `src/utils/breakpoints.ts` — this renderer only arranges them, so
 * the skill cannot drift from README, `docs/layout.md` or `faqir context`.
 */
function renderLayoutSystem(): string[] {
  const lines: string[] = ["## Layout System", ""];
  lines.push(
    "Page structure is five primitives, one token ladder and one breakpoint canon — never a utility class, never a hand-written `max-width`. Reach for the FIRST mechanism that solves the problem:",
  );
  lines.push("");
  for (const m of LAYOUT_MECHANISMS) lines.push(`${m.step}. **${m.title}.** ${m.summary}`);
  lines.push("");
  lines.push("| Primitive | Mechanism | Reach for it when |");
  lines.push("|-----------|-----------|-------------------|");
  for (const p of LAYOUT_PRIMITIVES) {
    lines.push(`| \`${p.name}\` | ${p.mechanism} | ${p.use} |`);
  }
  lines.push("");
  lines.push("**The ladder** — every responsive threshold in Faqir is one of these four:");
  lines.push("");
  lines.push("| Tier | Min-width | px |");
  lines.push("|------|-----------|----|");
  for (const b of BREAKPOINT_LIST) lines.push(`| \`${b.tier}\` | \`${b.rem}rem\` | ${b.px} |`);
  lines.push("");
  lines.push(`**The grammar** — ${grammarLine()}`);
  lines.push("");
  lines.push("```html");
  lines.push(
    `<div data-ui="grid" data-cols="1" ${responsiveAttribute("cols", "md")}="2" ${responsiveAttribute("cols", "lg")}="4" data-gap="4">`,
  );
  lines.push('  <div data-ui="card"><div data-part="body">One up on a phone, four from 64rem.</div></div>');
  lines.push("</div>");
  lines.push("```");
  lines.push("");
  for (const r of LAYOUT_RULES) lines.push(`- ${r}`);
  lines.push("");
  lines.push(
    `**Measure** (centred column widths): ${MEASURE_TOKENS.map((m) => `\`--${m.token}\` (${m.role})`).join(", ")}.`,
  );
  lines.push(
    `**Rhythm** (page air): ${RHYTHM_TOKENS.map((r) => `\`--${r.token}\` (${r.role})`).join(", ")}.`,
  );
  lines.push("");
  lines.push("**The default rhythm** (FAQIR-SPEC §20) — the one thing that means you do NOT have to wrap a sequence to space it:");
  lines.push("");
  lines.push(rhythmLine());
  lines.push("");
  lines.push(`**Spacing ladder** — ${spacingLadderLine()}.`);
  lines.push("");
  for (const band of SPACING_BANDS) {
    lines.push(`- **${band.label}:** \`--${band.from}\` through \`--${band.to}\` — ${band.use}.`);
  }
  lines.push("");
  lines.push(
    "**Density axis** — `data-density=\"compact\"` tightens the element and its subtree; `data-density=\"comfortable\"` resets a nested subtree. Spacing through `--space-64`, control heights, `--section-gap-sm|md|lg`, and `--content-gutter` remap in the nearest scope. It is pure CSS, not a sixth protocol attribute.",
  );
  lines.push("");
  lines.push(
    `Copy-ready page archetypes — ${ARCHETYPES.map((a) => a.title).join(", ")} — are in \`docs/layout.md\`, and each one is audited on every test run.`,
  );
  lines.push("");
  return lines;
}

function renderDataDriven(): string[] {
  return [
    "## Data-Driven Rendering",
    "",
    "`l-source` (built into `faqir-core.js`) binds any `l-data` element to a REST endpoint:",
    "",
    "```html",
    "<div l-data=\"{ newTitle: '' }\" l-source:tasks=\"/api/tasks\">",
    "  <template l-for=\"task in tasks\"><span l-text=\"task.title\"></span></template>",
    "  <form @submit.prevent=\"$tasks.create({ title: newTitle }).then(() => newTitle = '')\">",
    "    <input data-ui=\"input\" l-model=\"newTitle\">",
    "    <button data-ui=\"button\" data-variant=\"primary\">Add</button>",
    "  </form>",
    "</div>",
    "```",
    "",
    "Auto-injected: `tasks` (array), `tasksLoading`, `tasksError`. Controller: `$tasks.load()`, `.create()`, `.update(id, payload)`, `.remove(id)`, `.refresh()`.",
    "Modifiers: `.lazy`, `.optimistic`, `.poll.5000`, `.key.uuid`.",
    "The legacy `apiSource()` factory (spread into `l-data`, needs `api-source.js` first) injects `items`/`loading`/`submitting`/`error` + `load()`/`create()`/`update()`/`remove()`.",
    "Both are **data layers** — recipe controllers still never call `fetch`.",
    "",
  ];
}

/**
 * The CLI reference, derived command-for-command from `COMMAND_DEFINITIONS`
 * (task 1.0R-05).
 *
 * This list was hand-written and had fallen five commands behind the registry —
 * `doctor`, `variant`, `scaffold`, `dev` and `bindings` were dispatched by the
 * CLI and invisible to the skill. Nothing below is transcribed: the invocation
 * is `faqir <name> <args>` from the registry entry and the gloss is its
 * `skillNote` (or `summary`), grouped by the same categories `faqir help` uses.
 * Registering a command therefore documents it here, and
 * `tests/generator/skill.test.ts` fails if any registered name is missing.
 */
function renderCliReference(): string[] {
  const lines: string[] = ["## CLI Reference", ""];
  for (const category of COMMAND_CATEGORIES) {
    const commands = commandsInCategory(category);
    if (commands.length === 0) continue;
    const invocations = commands.map(
      ([name, def]) => `faqir ${name}${def.args ? ` ${def.args}` : ""}`,
    );
    const width = Math.max(...invocations.map((i) => i.length));
    lines.push(`**${category}**`);
    lines.push("");
    lines.push("```bash");
    commands.forEach(([, def], i) => {
      lines.push(`${invocations[i]!.padEnd(width)}  # ${def.skillNote ?? def.summary}`);
    });
    lines.push("```");
    lines.push("");
  }
  lines.push("Every command accepts `--json` for machine-readable output.");
  lines.push("");
  return lines;
}

/**
 * The scaffold catalogue (task 1.0R-05) — read from `SCAFFOLDS`, so registering
 * a scaffold adds a row with no edit here.
 *
 * The frontmatter promises "page scaffolding" and "building printable documents
 * (invoices, reports, forms)"; before this section the body never named
 * `faqir scaffold`, so an agent asked for an invoice hand-composed one instead
 * of running the generator that is print-tested on every run.
 */
export function renderScaffolds(): string[] {
  const lines: string[] = ["## Scaffolds — Whole Pages and Documents", ""];
  lines.push(
    "`faqir scaffold <name>` writes a complete, audit-clean page composed from maintained registry " +
      "patterns and installs everything it references. **Reach for it before hand-composing a page** — " +
      "an invoice or a report written by hand skips the print tests these carry.",
  );
  lines.push("");
  lines.push("| Scaffold | Produces | Patterns | Default theme |");
  lines.push("|----------|----------|----------|---------------|");
  for (const def of Object.values(SCAFFOLDS)) {
    const patterns = def.patterns.map((p) => `\`${p}\``).join(", ");
    const theme = def.defaultTheme ? `\`${def.defaultTheme}\`` : "project theme";
    lines.push(`| \`${def.name}\` | ${def.description} | ${patterns} | ${theme} |`);
  }
  lines.push("");
  lines.push("```bash");
  lines.push("faqir scaffold invoice --output invoices/2026-04.html   # print-ready document");
  lines.push("faqir scaffold landing-page --theme aurora              # marketing page");
  lines.push("```");
  lines.push("");
  lines.push(
    `Document scaffolds (${DOCUMENT_SCAFFOLD_NAMES.map((n) => `\`${n}\``).join(", ")}) default to the ` +
      "`document` theme and mark every editable value with a `FAQIR_REPLACE: path.to.value` comment — " +
      "replace the sample that follows each one and leave the `data-ui`/`data-part` attributes intact " +
      "so the page stays auditable. `--no-add` skips auto-installing missing components.",
  );
  lines.push("");
  return lines;
}

/**
 * The shipped theme gallery (task 1.0R-05) — read out of
 * `registry/themes/*.theme.json`, the same manifests `faqir theme list` and the
 * docs gallery use.
 *
 * The skill named `faqir theme set|list|create` without naming a single theme,
 * so "make it dark" had nothing to choose from. `mood` is the agent-selectable
 * axis the manifest exists for; `scheme` says which color schemes ship.
 */
export function renderThemes(registryPath: string): string[] {
  const themesDir = join(registryPath, "themes");
  const manifests: ThemeManifest[] = [];
  if (existsSync(themesDir)) {
    const files = readdirSync(themesDir)
      .filter((f) => f.endsWith(".theme.json"))
      .sort();
    for (const file of files) {
      manifests.push(JSON.parse(readFileSync(join(themesDir, file), "utf8")) as ThemeManifest);
    }
  }
  if (manifests.length === 0) return [];

  const lines: string[] = ["## Themes", ""];
  lines.push(
    `${manifests.length} themes ship with the registry. A theme redefines tokens only — no component ` +
      "markup changes, so switching one never invalidates a page. Pick by **mood**, then " +
      "`faqir theme set <name>`.",
  );
  lines.push("");
  lines.push("| Theme | Mood | Schemes | Dark mode | Pairs with |");
  lines.push("|-------|------|---------|-----------|------------|");
  for (const m of manifests) {
    const pairs = m.pairs_with.length > 0 ? m.pairs_with.map((t) => `\`${t}\``).join(", ") : "—";
    lines.push(
      `| \`${m.name}\` | ${m.mood.join(", ")} | ${m.scheme} | ${m.dark_mode} | ${pairs} |`,
    );
  }
  lines.push("");
  lines.push(
    "`scheme: both` means the theme ships a light and a dark rendering; `dark_mode: native` means it " +
      "carries an explicit dark block, so `data-theme=\"dark\"` on `<html>` is enough. " +
      "`faqir theme create <name>` generates a new contrast-verified theme plus its manifest.",
  );
  lines.push("");
  return lines;
}

/**
 * Every capability the frontmatter advertises, paired with the body section that
 * delivers it (task 1.0R-05).
 *
 * The frontmatter is the routing surface — Claude Code matches on it — so a
 * promise there with no section behind it routes a task to a skill that cannot
 * answer it. Both halves are asserted in `tests/generator/skill.test.ts`: the
 * claim must appear in the description, and the section must appear in the body.
 */
export const FRONTMATTER_CAPABILITIES: { claim: string; section: string }[] = [
  { claim: "page scaffolding", section: "## Scaffolds — Whole Pages and Documents" },
  { claim: "printable documents (invoices, reports, forms)", section: "## Scaffolds — Whole Pages and Documents" },
  { claim: "document/print layout", section: "## Scaffolds — Whole Pages and Documents" },
  { claim: "theme selection", section: "## Themes" },
  { claim: "CLI operations", section: "## CLI Reference" },
  { claim: "generating page layouts using Faqir tokens and primitives", section: "## Layout System" },
  { claim: "data-driven rendering", section: "## Data-Driven Rendering" },
  { claim: "data-ui/data-part/data-variant/data-state attributes", section: "## The Attribute Protocol" },
];

/** Component inventory grouped by layer, derived from the loaded manifests. */
function renderInventory(byLayer: Record<Layer, Manifest[]>): string[] {
  const lines: string[] = ["## Component Inventory", ""];
  const label: Record<Layer, string> = {
    primitives: "Primitives (CSS-only)",
    recipes: "Recipes (CSS + JS controller)",
    patterns: "Patterns (composition, no JS)",
  };
  for (const layer of LAYERS) {
    const names = byLayer[layer].map((m) => m.name).sort();
    if (names.length === 0) continue;
    lines.push(`**${names.length} ${label[layer]}:** ${names.join(", ")}`);
    lines.push("");
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Token reference (task 1.0R-02) — derived from registry/tokens/*.css
//
// `references/tokens.md` was hand-maintained and drifted: it quoted shadow values
// the source had not carried for months, and the surface ramp, the measure ladder
// and `--leading-loose` were missing outright. Nothing below is transcribed — the
// group names, their blurbs, the `── Banner ──` sub-headings, every value and
// every px note are read out of the token sources, and the modifier table is
// `TOKEN_MODIFIERS` verbatim, so `data-density` / `data-motion` / `data-theme`
// are stated once in the codebase and read twice (here and by `SPEC-1.0.md` §4).
// ---------------------------------------------------------------------------

/** One declared custom property, with the banner it sits under. */
interface TokenDeclaration {
  /** Name without the leading `--`. */
  name: string;
  /** Declared value, verbatim, whitespace collapsed. */
  value: string;
  /** Trailing same-line comment, e.g. `16px`. */
  note?: string;
  /** The `── Label ──` banner this declaration follows, if any. */
  section?: string;
}

/** One token file: its `@ui:tokens` group, header blurb and `:root` declarations. */
interface TokenGroup {
  group: string;
  file: string;
  blurb?: string;
  tokens: TokenDeclaration[];
  /** `true` when the file declares into `[data-density]` scopes (density.css). */
  scoped: boolean;
}

/** Drop the internal task/plan references the source comments carry. */
function stripSourceRefs(text: string): string {
  return text.replace(/\s*\((?:task|see)\s[^)]*\)/gi, "").trim();
}

/** Collapse a comment or value onto one line. */
function oneLine(text: string): string {
  return text.trim().replace(/\s+/g, " ");
}

/**
 * A same-length copy with every comment blanked. Brace scanning runs against
 * this, because a `:root` body legitimately contains `}` inside a comment
 * (`document.css` documents `@page { … }` there) and would otherwise truncate.
 */
function maskComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, (c) => " ".repeat(c.length));
}

/**
 * The bodies of every `<selector> { … }` block, sliced out of the ORIGINAL css
 * (comments intact — they carry the sub-headings and px notes) using offsets
 * found on the masked copy. `selector` must contain no capture group.
 */
function blockBodies(css: string, selector: string): string[] {
  const masked = maskComments(css);
  const out: string[] = [];
  for (const m of masked.matchAll(new RegExp(`${selector}\\s*\\{([^{}]*)\\}`, "g"))) {
    const start = (m.index ?? 0) + m[0].indexOf("{") + 1;
    out.push(css.slice(start, start + m[1].length));
  }
  return out;
}

/**
 * Walk a block body in source order, returning every custom property with the
 * banner it follows and its trailing same-line comment. Comments are read, not
 * skipped: they carry the sub-headings and the px equivalents.
 */
function scanDeclarations(body: string): TokenDeclaration[] {
  const out: TokenDeclaration[] = [];
  let section: string | undefined;
  let prevEnd = -1;
  for (const m of body.matchAll(/\/\*([\s\S]*?)\*\/|--([a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    const start = m.index ?? 0;
    if (m[1] !== undefined) {
      const banner = /──\s*([^─]+?)\s*──/.exec(m[1]);
      if (banner) {
        section = stripSourceRefs(oneLine(banner[1]));
      } else if (prevEnd >= 0 && out.length > 0 && !body.slice(prevEnd, start).includes("\n")) {
        // A comment on the same line as the previous declaration annotates it.
        out[out.length - 1].note = oneLine(m[1]);
      }
      continue;
    }
    out.push({ name: m[2], value: oneLine(m[3]), section });
    prevEnd = start + m[0].length;
  }
  return out;
}

/** The `@ui:tokens <group> — <blurb>` header every token file carries. */
function tokenHeader(css: string): { group: string; blurb?: string } | undefined {
  const line = /@ui:tokens\s+(\S+)([^\n]*)/.exec(css);
  if (!line) return undefined;
  const tail = /—\s*(.+?)\s*(?:\*\/)?$/.exec(line[2]);
  return { group: line[1], blurb: tail ? stripSourceRefs(tail[1]) : undefined };
}

/**
 * The token files in cascade order, read out of `tokens/index.css` itself — the
 * order the reference documents is the order the browser resolves.
 */
function tokenFileOrder(tokensDir: string): string[] {
  const index = join(tokensDir, "index.css");
  if (!existsSync(index)) return [];
  return [...readFileSync(index, "utf8").matchAll(/@import\s+['"]\.\/([^'"]+)['"]/g)].map((m) => m[1]);
}

/** Every token file's `:root` declarations, grouped, in cascade order. */
function loadTokenGroups(tokensDir: string): TokenGroup[] {
  const groups: TokenGroup[] = [];
  for (const file of tokenFileOrder(tokensDir)) {
    const path = join(tokensDir, file);
    if (!existsSync(path)) continue;
    const css = readFileSync(path, "utf8");
    const header = tokenHeader(css);
    if (!header) continue;
    groups.push({
      group: header.group,
      file,
      blurb: header.blurb,
      tokens: blockBodies(css, ":root").flatMap(scanDeclarations),
      scoped: /\[data-density="/.test(maskComments(css)),
    });
  }
  return groups;
}

/** The `[data-density="<scope>"]` declarations of a token file, in source order. */
function densityScope(css: string, scope: string): TokenDeclaration[] {
  return blockBodies(css, `\\[data-density="${scope}"\\]`).flatMap(scanDeclarations);
}

/** A markdown cell — token values never contain a backtick, but may contain a pipe. */
function cell(value: string): string {
  return `\`${value.replace(/\|/g, "\\|")}\``;
}

/** One table of declarations. Optional columns appear only when they carry data. */
function renderTokenTable(
  tokens: TokenDeclaration[],
  valueLabel = "Value",
  extra?: { label: string; render: (t: TokenDeclaration) => string },
): string[] {
  const noted = tokens.some((t) => t.note);
  const head = ["Token", valueLabel, ...(extra ? [extra.label] : []), ...(noted ? ["Notes"] : [])];
  const lines = [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`];
  for (const t of tokens) {
    const row = [cell(`--${t.name}`), cell(t.value)];
    if (extra) row.push(extra.render(t));
    if (noted) row.push(t.note ?? "—");
    lines.push(`| ${row.join(" | ")} |`);
  }
  return lines;
}

/** Split declarations into their `── Banner ──` runs, preserving source order. */
function bySection(tokens: TokenDeclaration[]): { section?: string; tokens: TokenDeclaration[] }[] {
  const out: { section?: string; tokens: TokenDeclaration[] }[] = [];
  for (const t of tokens) {
    const last = out[out.length - 1];
    if (last && last.section === t.section) last.tokens.push(t);
    else out.push({ section: t.section, tokens: [t] });
  }
  return out;
}

/** The sanctioned token modifiers, stated once in `src/protocol.ts`. */
function renderTokenModifiers(): string[] {
  const lines: string[] = ["## Sanctioned Token Modifiers", ""];
  lines.push(
    `${TOKEN_MODIFIERS.length} attributes are part of the frozen contract without being protocol ` +
      "attributes: each re-declares design tokens for its subtree, and every descendant inherits the " +
      "result. None names a component, fills a slot, or needs a manifest declaration.",
  );
  lines.push("");
  lines.push("| Attribute | Purpose | Values | Written by | Scope |");
  lines.push("|---|---|---|---|---|");
  for (const m of TOKEN_MODIFIERS) {
    lines.push(
      `| \`${m.attr}\` | ${m.purpose} | ${m.values.map((v) => `\`${v}\``).join(", ")} | ` +
        `${m.owner} | ${m.scope} |`,
    );
  }
  lines.push("");
  return lines;
}

/**
 * The `[data-density]` remap, derived from `density.css` rather than described:
 * a token added to the compact scope appears here without editing this file.
 */
function renderDensityRemap(css: string, group: TokenGroup, rootGroups: TokenGroup[]): string[] {
  const compact = densityScope(css, "compact");
  const comfortable = new Map(densityScope(css, "comfortable").map((t) => [t.name, t.value]));
  if (compact.length === 0) return [];

  const lines: string[] = [];
  lines.push(`## ${group.group}${group.blurb ? ` — ${group.blurb}` : ""}`);
  lines.push("");
  lines.push(`_\`registry/tokens/${group.file}\` · ${compact.length} tokens re-declared per scope_`);
  lines.push("");

  const origin = new Map<string, string>();
  for (const g of rootGroups) for (const t of g.tokens) if (!origin.has(t.name)) origin.set(t.name, g.group);
  const counts = new Map<string, number>();
  const ownTokens: string[] = [];
  for (const t of compact) {
    const from = origin.get(t.name);
    if (from) counts.set(from, (counts.get(from) ?? 0) + 1);
    else ownTokens.push(t.name);
  }
  lines.push(
    `Remapped by source group: ${[...counts].map(([g, n]) => `\`${g}\` (${n})`).join(", ")}` +
      (ownTokens.length
        ? `, plus ${ownTokens.map((n) => `\`--${n}\``).join(", ")} declared only in these scopes.`
        : "."),
  );
  // Where a group is mostly remapped, the handful it leaves alone is the news:
  // `--space-0` is 0 at any density and a 1px hairline is a hairline. Groups the
  // scope barely touches (or never touches) say nothing here.
  const remapped = new Set(compact.map((t) => t.name));
  for (const g of rootGroups) {
    const untouched = g.tokens.filter((t) => !remapped.has(t.name));
    if (untouched.length === 0 || untouched.length >= g.tokens.length - untouched.length) continue;
    lines.push("");
    lines.push(
      `Invariant in \`${g.group}\`: ${untouched.map((t) => `\`--${t.name}\``).join(", ")} — ` +
        "never scaled, at any density.",
    );
  }
  lines.push("");
  for (const run of bySection(compact)) {
    if (run.section) {
      lines.push(`### ${run.section}`);
      lines.push("");
    }
    lines.push(
      ...renderTokenTable(run.tokens, "`compact`", {
        label: "`comfortable`",
        render: (t) => (comfortable.has(t.name) ? cell(comfortable.get(t.name)!) : "—"),
      }),
    );
    lines.push("");
  }
  return lines;
}

/**
 * Build `references/tokens.md` from `<registryRoot>/tokens/*.css`. Exported so a
 * test can point it at a fixture registry and prove the file is derived rather
 * than transcribed.
 */
export function renderTokensReference(registryRoot: string, schemaVersion: string): string {
  const tokensDir = join(registryRoot, "tokens");
  const groups = loadTokenGroups(tokensDir);
  const rootGroups = groups.filter((g) => g.tokens.length > 0);
  const scopedGroups = groups.filter((g) => g.scoped);

  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir Design Tokens Reference");
  lines.push("");
  lines.push(
    "Every token the registry declares, read out of `registry/tokens/*.css` — the values below ARE " +
      "the declarations. Never hardcode a colour, size, duration or shadow: reference one of these " +
      "tokens through `var()`.",
  );
  lines.push("");
  lines.push(
    `Cascade order, as \`tokens/index.css\` imports them: ${groups.map((g) => `\`${g.file}\``).join(" → ")}. ` +
      "First declaration wins, and each heading below is the `@ui:tokens` group name its file carries — " +
      "palette (raw values) feeds semantic (purpose) feeds aliases (per-component).",
  );
  lines.push("");

  lines.push(...renderTokenModifiers());

  const total = rootGroups.reduce((n, g) => n + g.tokens.length, 0);
  lines.push("## Token Groups");
  lines.push("");
  lines.push(`${total} tokens in ${rootGroups.length} groups:`);
  lines.push("");
  for (const g of rootGroups) {
    lines.push(`- \`${g.group}\` (${g.tokens.length})${g.blurb ? ` — ${g.blurb}` : ""}`);
  }
  lines.push("");

  for (const g of rootGroups) {
    lines.push(`## ${g.group}${g.blurb ? ` — ${g.blurb}` : ""}`);
    lines.push("");
    lines.push(`_\`registry/tokens/${g.file}\` · ${g.tokens.length} tokens_`);
    lines.push("");
    for (const run of bySection(g.tokens)) {
      if (run.section) {
        lines.push(`### ${run.section}`);
        lines.push("");
      }
      lines.push(...renderTokenTable(run.tokens));
      lines.push("");
    }
  }

  for (const g of scopedGroups) {
    lines.push(...renderDensityRemap(readFileSync(join(tokensDir, g.file), "utf8"), g, rootGroups));
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

// ---------------------------------------------------------------------------
// Directive reference (task 1.0R-03) — derived from the engine + the plugins
//
// `references/directives.md` was hand-maintained and drifted: `l-transition`,
// `l-teleport`, `l-key`, `data-motion` and every plugin directive were missing,
// while `.ctrl` / `.shift` / `.alt` / `.meta` were documented as event
// modifiers the engine has never implemented. The vocabulary tables below are
// now READ, not remembered:
//
//   • directives, their modifiers and the magics come from the `@ui:directive`
//     / `@ui:modifier` / `@ui:magic` lines the engine declares in §3.0;
//   • the priority ladder, the key aliases and the motion presets come from
//     `PRIORITY`, `KEY_MAP` and `MOTION_PRESETS` — code, read as code;
//   • `data-motion`'s phases come from `TOKEN_MODIFIERS` (`src/protocol.ts`);
//   • the `l-source` controller API comes from the `ctrl` literal itself;
//   • plugin rows come from `loadPluginMetadata()`, so a sixth plugin file
//     documents itself.
//
// The prose sections (global API, worked patterns, devtools) stay hand-written:
// nothing derives them.
// ---------------------------------------------------------------------------

/** One `@ui:directive` line: the engine's public `l-*` surface. */
interface DirectiveDeclaration {
  /** Attribute as authored, e.g. `l-bind:<attr>`. */
  attribute: string;
  /** Base name without the argument, e.g. `l-bind`. */
  name: string;
  shorthand: string;
  placement: string;
  example: string;
  description: string;
}

/** One `@ui:magic` line. `where` is `internal` for engine-only names. */
interface MagicDeclaration {
  name: string;
  where: string;
  description: string;
}

/** One `@ui:modifier` line, attached to the directive it modifies. */
interface ModifierDeclaration {
  directive: string;
  modifier: string;
  description: string;
}

export interface EngineVocabulary {
  directives: DirectiveDeclaration[];
  magics: MagicDeclaration[];
  modifiers: ModifierDeclaration[];
}

/** `internal` in the placement/where column means "named here, not vocabulary". */
const INTERNAL = "internal";

/**
 * Read the engine's declared vocabulary (§3.0 of `src/core-src/engine.js`).
 * Exported so the tripwire test can hold the declarations against what the
 * engine actually implements, in both directions.
 */
export function parseEngineVocabulary(engineSource: string): EngineVocabulary {
  const fields = (line: string) => line.split("|").map((f) => f.trim());
  const directives: DirectiveDeclaration[] = [];
  const magics: MagicDeclaration[] = [];
  const modifiers: ModifierDeclaration[] = [];

  // Exactly one space after `//` — the field legend above the block indents its
  // `@ui:…` tokens further precisely so it is documentation, not a declaration.
  const line = /^\s*\/\/ @ui:(directive|magic|modifier) +([^\n]+?)\s*$/gm;
  for (const [, kind, rest] of engineSource.matchAll(line)) {
    const parts = fields(rest);
    if (kind === "directive") {
      const [attribute, shorthand, placement, example, ...tail] = parts;
      directives.push({
        attribute,
        name: attribute.split(":")[0],
        shorthand,
        placement,
        example,
        description: tail.join(" | "),
      });
    } else if (kind === "magic") {
      const [name, where, ...tail] = parts;
      magics.push({ name, where, description: tail.join(" | ") });
    } else {
      const [head, ...tail] = parts;
      const [directive, modifier] = head.split(/\s+/);
      modifiers.push({ directive, modifier, description: tail.join(" | ") });
    }
  }
  return { directives, magics, modifiers };
}

/**
 * The entries of an object literal the engine declares as
 * `var <NAME> = { … }`, in source order. Used for the three lists that are
 * already code — `PRIORITY`, `KEY_MAP`, `MOTION_PRESETS` — so they are read
 * rather than repeated in a comment.
 */
export function parseEngineMap(engineSource: string, name: string): [string, string][] {
  const body = new RegExp(`var\\s+${name}\\s*=\\s*\\{([^}]*)\\}`).exec(engineSource)?.[1];
  if (!body) return [];
  const out: [string, string][] = [];
  for (const m of body.replace(/\/\/[^\n]*/g, "").matchAll(/'([^']+)'\s*:\s*([^,\n]+)|([A-Za-z_$][\w$]*)\s*:\s*([^,\n]+)/g)) {
    const key = m[1] ?? m[3];
    const value = (m[2] ?? m[4]).trim().replace(/,$/, "");
    out.push([key, value.replace(/^'|'$/g, "")]);
  }
  return out;
}

/**
 * The `l-source` controller API, read off the `ctrl` object literal in §3.5 —
 * the methods and their parameters are the ones the engine defines, so a new
 * one documents itself.
 */
export function parseSourceController(engineSource: string): { name: string; params: string }[] {
  const start = engineSource.indexOf("var ctrl = {");
  if (start < 0) return [];
  const lines = engineSource.slice(start).split("\n");
  const out: { name: string; params: string }[] = [];
  for (const line of lines.slice(1)) {
    if (/^ {4}\};/.test(line)) break;
    const m = /^ {6}([A-Za-z_$][\w$]*)\s*:\s*function\s*\(([^)]*)\)/.exec(line);
    if (m) out.push({ name: m[1], params: m[2].trim() });
  }
  return out;
}

/** A markdown cell: escape the pipes a selector or expression may contain. */
function md(value: string): string {
  return value.replace(/\|/g, "\\|");
}

/** Code cell, unless the source already wrote `—` for "none". */
function codeCell(value: string): string {
  return value === "—" || value === "" ? "—" : `\`${md(value)}\``;
}

/** The directive table, plus the order the engine applies them (PRIORITY). */
function renderDirectiveTable(vocab: EngineVocabulary, engineSource: string): string[] {
  const lines: string[] = ["## Directives", ""];
  const isPublic = (d: DirectiveDeclaration) => d.placement !== INTERNAL;
  const shown = vocab.directives.filter(isPublic);
  lines.push(
    `${shown.length} directives. Every one is an attribute — there is no template syntax to learn, ` +
      "and an element carrying none is inert.",
  );
  lines.push("");
  lines.push("| Directive | Shorthand | Goes on | Example | What it does |");
  lines.push("|---|---|---|---|---|");
  for (const d of shown) {
    lines.push(
      `| \`${md(d.attribute)}\` | ${codeCell(d.shorthand)} | ${md(d.placement)} | ` +
        `\`${md(d.example)}\` | ${md(d.description)} |`,
    );
  }
  lines.push("");

  const priority = parseEngineMap(engineSource, "PRIORITY");
  if (priority.length > 0) {
    const byRank = new Map<string, string[]>();
    for (const [type, rank] of priority) {
      byRank.set(rank, [...(byRank.get(rank) ?? []), `\`l-${type}\``]);
    }
    const order = [...byRank.entries()].sort((a, b) => Number(a[0]) - Number(b[0]));
    lines.push(
      "**Application order** — directives on one element run in this order, whatever order the " +
        "attributes are written in: " +
        order.map(([, names]) => names.join(", ")).join(" → ") +
        ". That is why `l-data` sees no half-built scope and `l-cloak` clears last.",
    );
    lines.push("");
  }
  return lines;
}

/** The modifier tables, one per directive, plus the key aliases from KEY_MAP. */
function renderModifiers(vocab: EngineVocabulary, engineSource: string): string[] {
  const lines: string[] = ["## Modifiers", ""];
  lines.push(
    "Modifiers are dot-suffixes on the attribute name: `@input.debounce500ms`, " +
      "`l-model.number`, `l-source:items.optimistic.poll.10000.key.uuid`. " +
      "A modifier the engine does not know is ignored — silently in the production " +
      "engine, with a warning in the dev one.",
  );
  lines.push("");

  const directives = [...new Set(vocab.modifiers.map((m) => m.directive))];
  for (const directive of directives) {
    lines.push(`### \`${directive}\``);
    lines.push("");
    lines.push("| Modifier | Effect |");
    lines.push("|---|---|");
    for (const m of vocab.modifiers.filter((x) => x.directive === directive)) {
      lines.push(`| \`${m.modifier}\` | ${md(m.description)} |`);
    }
    lines.push("");
  }

  const keys = parseEngineMap(engineSource, "KEY_MAP");
  if (keys.length > 0) {
    lines.push("### Key modifiers");
    lines.push("");
    lines.push(
      "On `keydown` / `keyup` / `keypress`, a key modifier gates the handler on `event.key`. " +
        "The first recognised modifier wins; there are no combo modifiers — test `$event.ctrlKey`, " +
        "`$event.shiftKey`, `$event.altKey` or `$event.metaKey` in the expression instead.",
    );
    lines.push("");
    lines.push("| Modifier | `event.key` |");
    lines.push("|---|---|");
    for (const [modifier, key] of keys) {
      lines.push(`| \`.${modifier}\` | \`${key === " " ? "' '" : key}\` |`);
    }
    lines.push("");
  }
  return lines;
}

/** The magic table, with the engine internals named rather than dropped. */
function renderMagics(vocab: EngineVocabulary): string[] {
  const lines: string[] = ["## Magic Properties", ""];
  const magics = vocab.magics.filter((m) => m.where !== INTERNAL);
  const internals = vocab.magics.filter((m) => m.where === INTERNAL);
  lines.push(
    "Available on every scope without declaring them. They are non-enumerable, so `l-data` " +
      "object spreads and `Faqir.inspect()` snapshots never contain them.",
  );
  lines.push("");
  lines.push("| Magic | Available in | What it is |");
  lines.push("|---|---|---|");
  for (const m of magics) lines.push(`| \`${m.name}\` | ${md(m.where)} | ${md(m.description)} |`);
  lines.push("");
  if (internals.length > 0) {
    lines.push(
      "**Not vocabulary:** " +
        internals.map((m) => `\`${m.name}\` — ${md(m.description)}`).join(" ") +
        " It is named here so its absence from the table above reads as deliberate.",
    );
    lines.push("");
  }
  return lines;
}

/** `l-transition`: the presets are the engine's, the phases are the protocol's. */
function renderTransitions(engineSource: string): string[] {
  const presets = parseEngineMap(engineSource, "MOTION_PRESETS").map(([name]) => name);
  const motion = TOKEN_MODIFIERS.find((m) => m.attr === "data-motion");
  if (presets.length === 0 || !motion) return [];

  const lines: string[] = ["## Transitions — `l-transition` and `data-motion`", ""];
  lines.push(
    `\`l-transition\` names one of ${presets.length} presets shipped by ` +
      `\`registry/base/motion-presets.css\`: ${presets.map((p) => `\`${p}\``).join(", ")}. ` +
      "An empty value means `fade`; an unknown name still animates but has no styling, so the " +
      "engine warns.",
  );
  lines.push("");
  lines.push(
    "There are no per-stage CSS classes: the lifecycle runs through one frozen token modifier, " +
      `\`${motion.attr}\`.`,
  );
  lines.push("");
  lines.push(`- **Purpose:** ${motion.purpose}`);
  lines.push(`- **Values:** ${motion.values.map((v) => `\`${v}\``).join(", ")} — the phases below.`);
  lines.push(`- **Scope:** ${motion.scope}`);
  lines.push(`- **Written by:** the ${motion.owner}, never by an author.`);
  lines.push("");
  lines.push("```text");
  lines.push(`show:  data-motion="${motion.values[0]}"  →  "${motion.values[1]}"  →  (removed)`);
  lines.push(
    `hide:  data-motion="${motion.values[2]}"  →  "${motion.values[3]}"  →  (removed, then the element is)`,
  );
  lines.push("```");
  lines.push("");
  lines.push(
    "So a transition is auditable straight from the DOM. Under `prefers-reduced-motion` no phase " +
      "is stamped at all — the element simply appears and disappears.",
  );
  lines.push("");
  lines.push("```html");
  lines.push('<div l-data="{ open: false }">');
  lines.push('  <button @click="open = !open">Toggle</button>');
  lines.push('  <p l-show="open" l-transition="slide-up">Announced with motion.</p>');
  lines.push("</div>");
  lines.push("```");
  lines.push("");
  return lines;
}

/** `l-source`: what it injects, and the controller API read off the engine. */
function renderSource(engineSource: string, vocab: EngineVocabulary): string[] {
  const methods = parseSourceController(engineSource);
  const lines: string[] = ["## `l-source` — declarative REST binding", ""];
  lines.push("Place it on an `l-data` element; one scope may carry several.");
  lines.push("");
  lines.push("```html");
  lines.push('<div l-data="{ newTitle: \'\' }" l-source:tasks="/api/tasks">');
  lines.push('  <template l-for="task in tasks" l-key="task.id">');
  lines.push('    <li l-text="task.title"></li>');
  lines.push("  </template>");
  lines.push('  <p l-show="tasksLoading">Loading…</p>');
  lines.push('  <p l-show="tasksError" l-text="tasksError"></p>');
  lines.push('  <button @click="$tasks.create({ title: newTitle })">Add</button>');
  lines.push("</div>");
  lines.push("```");
  lines.push("");
  lines.push("Injected into the scope, for `l-source:tasks`:");
  lines.push("");
  lines.push("| Name | What it holds |");
  lines.push("|---|---|");
  lines.push("| `tasks` | The fetched items, reactive |");
  lines.push("| `tasksLoading` | `true` while a request is in flight |");
  lines.push("| `tasksError` | The last error message, or `null` |");
  lines.push("| `$tasks` | The controller below |");
  lines.push("");
  if (methods.length > 0) {
    lines.push(
      `Controller methods (\`$tasks.…\`), each returning a promise: ` +
        methods.map((m) => `\`${m.name}(${m.params})\``).join(", ") + ".",
    );
    lines.push("");
  }
  const sourceModifiers = vocab.modifiers.filter((m) => m.directive === "l-source");
  if (sourceModifiers.length > 0) {
    lines.push(
      `Modifiers: ${sourceModifiers.map((m) => `\`${m.modifier}\``).join(", ")} — see the table above. ` +
        "Teardown is automatic: removing the scope (an `l-if` flip, a keyed `l-for` removal) aborts " +
        "in-flight requests and stops polling.",
    );
    lines.push("");
  }
  return lines;
}

/**
 * The official plugins, from their `@ui:plugin` / `@ui:provides` headers — the
 * vocabulary the engine does not carry, documented where the agent is sent to
 * look for it. A new plugin file is a new row and nothing else.
 */
function renderPluginVocabulary(plugins: PluginMetadata[]): string[] {
  if (plugins.length === 0) return [];
  const lines: string[] = ["## Plugin Vocabulary", ""];
  lines.push(
    `${plugins.length} official plugins add directives and magics to the same expression language. ` +
      "Load one after `faqir-core.js` (`<script src=\"core/plugins/faqir-persist.js\"></script>`), or " +
      "bundle core plus every plugin with `faqir bundle --js`. Each self-registers, is dependency-free " +
      "and is ≤ 2 KB gzip.",
  );
  lines.push("");
  lines.push("| Plugin | Provides | File | What it does |");
  lines.push("|---|---|---|---|");
  for (const p of plugins) {
    lines.push(
      `| \`${p.name}\` | ${p.provides.map((v) => `\`${v}\``).join(", ") || "—"} | ` +
        `\`registry/core/plugins/${p.file}\` | ${md(p.description ?? "—")} |`,
    );
  }
  lines.push("");
  for (const p of plugins) {
    if (!p.example) continue;
    lines.push(`### \`${p.name}\``);
    lines.push("");
    if (p.notes) lines.push(p.notes, "");
    lines.push("```html");
    lines.push(p.example);
    lines.push("```");
    lines.push("");
  }
  return lines;
}

/**
 * The hand-written half. The global API, the worked patterns and the devtools
 * handle are not derivable from any declaration — they are the prose an agent
 * needs around the tables, and they stay authored.
 */
const DIRECTIVE_PROSE = `## Global API

\`\`\`js
Faqir.store('name', { count: 0 })   // Register a global store, read as $store.name
Faqir.data('name', () => ({ … }))   // Register a reusable l-data factory
Faqir.directive('name', handler)    // Register a custom l-name directive
Faqir.magic('name', callback)       // Register a custom $name magic
Faqir.plugin(fn)                    // Install a plugin (fn receives Faqir)
Faqir.controller('name', factory)   // Register a recipe controller
Faqir.initTree(el)                  // Bind a subtree added after load
\`\`\`

Anything injected into the DOM after page load — a fetched fragment, a cloned
row — is inert until \`Faqir.initTree(el)\` walks it.

## Common Patterns

### Counter

\`\`\`html
<div l-data="{ count: 0 }">
  <button @click="count--">-</button>
  <span l-text="count"></span>
  <button @click="count++">+</button>
</div>
\`\`\`

### Two-way binding

\`\`\`html
<div l-data="{ name: '' }">
  <input l-model.trim="name" placeholder="Name…">
  <p>Hello, <strong l-text="name || '…'"></strong></p>
</div>
\`\`\`

### Conditional rendering

\`\`\`html
<div l-data="{ show: true }">
  <button @click="show = !show" l-text="show ? 'Hide' : 'Show'"></button>
  <div l-show="show">Kept in the DOM, display toggled</div>
  <template l-if="show">
    <p>Created and destroyed with the flag</p>
  </template>
</div>
\`\`\`

### Keyed list

\`\`\`html
<div l-data="{ items: [{ id: 1, label: 'A' }, { id: 2, label: 'B' }] }">
  <template l-for="(item, i) in items" l-key="item.id">
    <span l-text="item.label"></span>
    <button @click="items.splice(i, 1)">Remove</button>
  </template>
</div>
\`\`\`

### Calling a controller through \`$ui\`

\`\`\`html
<div data-ui="dialog" data-state="closed" l-data>
  <button @click="$ui.open()">Open</button>
  <!-- … dialog structure … -->
</div>
\`\`\`

\`$state\` and \`$variant\` read the same component both ways: a controller
setting \`data-state="open"\` re-runs every expression that read \`$state\`.

### Global store

\`\`\`html
<script>
  Faqir.store('user', { name: 'Alice', role: 'admin' });
</script>
<div l-data>
  <p l-text="$store.user.name"></p>
</div>
\`\`\`

## Inspecting a live page

Both engine builds install \`window.__FAQIR_DEVTOOLS__\` (handle \`version: 1\`).
Use it when driving a browser to check what the engine actually bound.

| Key | Returns |
|-----|---------|
| \`inspect(el\\|selector)\` | full snapshot for one element (below) |
| \`scopes(within?)\` | \`{ el, id, label, scope }[]\` — declared scope roots |
| \`components(within?)\` | \`{ el, label, ui, variant, size, state, parts[], controller }[]\` |
| \`stores()\` | snapshot of every \`Faqir.store()\` |
| \`warnings()\` | recorded diagnostics; **always empty in the production engine** |
| \`dev\` | \`true\` only when the page loaded \`core/faqir-core.dev.js\` |

\`Faqir.inspect(el)\` (same function) returns:

\`\`\`js
{
  el, scopeRoot, scopeId,
  scope:      { /* plain copy of the scope's data; magics excluded */ },
  directives: [{ type, arg, expression, modifiers, raw }],
  controller: { ui, el, api, methods } | null,
  state:      { ui, part, variant, size, state }
}
\`\`\`

\`scope\` is a copy — mutating it does not touch the page, and inspecting
registers no reactive dependency.

### The development engine

\`core/faqir-core.dev.js\` behaves identically and adds four diagnostic classes,
each printed once with the offending element's \`outerHTML\` and readable via
\`warnings()\`: \`expression\` (a failed \`l-*\` expression), \`directive\` (an \`l-…\`
attribute nothing handles), \`reorder\` (an unkeyed \`l-for\` that reordered), and
\`html\` (\`l-html\` writes unsanitized markup). Swap the script tag while
developing; ship \`core/faqir-core.js\`.

\`faqir dev\` also injects an inspector overlay into every page it serves —
toggle it with \`Ctrl/Cmd + Shift + F\` (\`--no-overlay\` to disable). It is served
by the dev server only and is never written into the project.
`;

/**
 * Build `references/directives.md`. `engineSource` is `src/core-src/engine.js`
 * and `pluginsDir` is `registry/core/plugins/`; both are parameters so a test
 * can point them at fixtures and prove the file is derived, not transcribed.
 */
export function renderDirectivesReference(
  engineSource: string,
  pluginsDir: string,
  schemaVersion: string,
): string {
  const vocab = parseEngineVocabulary(engineSource);
  const plugins = loadPluginMetadata(pluginsDir);

  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir-Core Reactive Directives Reference");
  lines.push("");
  lines.push(
    "Every directive, modifier and magic the engine implements, read out of " +
      "`src/core-src/engine.js` — plus the vocabulary the official plugins add. " +
      "Load the engine with `<script src=\"core/faqir-core.js\" defer></script>`: it binds on " +
      "`DOMContentLoaded` and needs no build step. Add `data-manual` to that tag to bootstrap " +
      "yourself with `Faqir.start()`.",
  );
  lines.push("");
  lines.push(
    "Expressions are plain JavaScript evaluated against the nearest scope: any name the scope " +
      "declares is in scope unqualified, and the `$…` magics below are always available.",
  );
  lines.push("");

  lines.push(...renderDirectiveTable(vocab, engineSource));
  lines.push(...renderModifiers(vocab, engineSource));
  lines.push(...renderMagics(vocab));
  lines.push(...renderTransitions(engineSource));
  lines.push(...renderSource(engineSource, vocab));
  lines.push(...renderPluginVocabulary(plugins));
  lines.push(DIRECTIVE_PROSE);

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

// ---------------------------------------------------------------------------
// Manifest reference (task 1.0R-04) — derived from manifest.schema.json
//
// `references/manifest.md` was hand-maintained and actively misleading: it
// omitted `$schema`, `props`, `changes`, `aliases` and `variants.<group>.responsive`,
// listed nine categories where the schema closes the vocabulary at eleven, and
// — worst — never said that `definitions.componentManifest.required` names ALL
// seventeen fields, so its "Full Schema" block read as though everything were
// optional and an agent authoring by hand produced something that fails.
//
// Nothing below is transcribed. The definition sections, the required/optional
// split, every type, every description and every enum are walked out of the
// schema document, so a property added to `manifest.schema.json` appears here
// (and `check:skill` fails until it is regenerated). The one worked example is
// the shipped `button.manifest.json`, lifted byte-for-byte.
// ---------------------------------------------------------------------------

/** The Draft-07 subset `manifest.schema.json` uses, as read by the renderer. */
interface SchemaNode {
  type?: string | string[];
  description?: string;
  enum?: string[];
  properties?: Record<string, SchemaNode>;
  required?: string[];
  items?: SchemaNode;
  additionalProperties?: SchemaNode | boolean;
  minLength?: number;
  minItems?: number;
  minProperties?: number;
  $ref?: string;
}

/** How many registry components of one `kind` declare a `files.js` controller. */
export interface KindFileSet {
  kind: string;
  count: number;
  withJs: number;
}

/** The worked example a manifest reference carries, read off disk. */
export interface ManifestExample {
  /** Component name, e.g. `button`. */
  name: string;
  /** Repo-relative path of the manifest, quoted in the heading. */
  manifestPath: string;
  /** The manifest file, verbatim. */
  manifestJson: string;
  /** The component's HTML source (its `@ui:` header is lifted from it). */
  html?: string;
  /** The component's CSS source (same). */
  css?: string;
}

/** `#/definitions/slot` → `slot`. */
function refName(ref: string): string {
  return ref.split("/").pop() ?? ref;
}

/** A markdown table cell: one line, pipes escaped. */
function mdCell(text: string): string {
  return text.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
}

/** Backticked values, comma-separated — the form every enum is rendered in. */
function enumValues(values: string[]): string {
  return values.map((v) => `\`${v}\``).join(", ");
}

/**
 * The type of one property, as a table cell. `$ref`s render as the definition
 * name (each has its own section below), arrays as `<item>[]`, and open maps as
 * `{ <key>: <value> }` — the shape `slots`, `variants`, `props` and `states` use.
 */
function typeLabel(node: SchemaNode): string {
  if (node.$ref) return `\`${refName(node.$ref)}\``;
  const type = Array.isArray(node.type) ? node.type.join(" \\| ") : node.type;
  if (type === "array") {
    const item = node.items ? typeLabel(node.items) : "`any`";
    return `${item}[]`;
  }
  if (type === "object" && node.additionalProperties && typeof node.additionalProperties === "object") {
    return `{ \`<key>\`: ${typeLabel(node.additionalProperties)} }`;
  }
  if (node.enum) return `\`${type ?? "string"}\` (enum)`;
  return `\`${type ?? "any"}\``;
}

/** The constraints a node declares, spelled out for the Notes cell. */
function constraintNotes(node: SchemaNode): string[] {
  const out: string[] = [];
  if (node.minLength === 1) out.push("non-empty");
  else if (typeof node.minLength === "number") out.push(`at least ${node.minLength} characters`);
  if (typeof node.minItems === "number") out.push(`at least ${node.minItems} item${node.minItems === 1 ? "" : "s"}`);
  if (typeof node.minProperties === "number") {
    out.push(`at least ${node.minProperties} entr${node.minProperties === 1 ? "y" : "ies"}`);
  }
  if (node.enum) out.push(`one of ${enumValues(node.enum)}`);
  if (node.items?.enum) out.push(`each one of ${enumValues(node.items.enum)}`);
  if (node.items?.minLength === 1) out.push("items non-empty");
  return out;
}

/**
 * The Notes cell: the schema's own description plus its constraints. A `$ref`
 * carries neither, so the referenced definition's description and constraints
 * are read through — `category` states its eleven values on the row that uses it.
 */
function notesCell(node: SchemaNode, definitions: Record<string, SchemaNode>): string {
  const target = node.$ref ? definitions[refName(node.$ref)] : undefined;
  const parts = [
    ...(node.description ? [node.description] : []),
    ...(target?.description && target.description !== node.description ? [target.description] : []),
    ...constraintNotes(node),
    ...(target ? constraintNotes(target) : []),
  ];
  return parts.length > 0 ? mdCell(parts.join(" · ")) : "—";
}

/** One `| field | type | notes |` row. */
function propertyRow(name: string, node: SchemaNode, definitions: Record<string, SchemaNode>): string {
  return `| \`${name}\` | ${typeLabel(node)} | ${notesCell(node, definitions)} |`;
}

/** A property table, in the order given. */
function propertyTable(
  properties: Record<string, SchemaNode>,
  names: string[],
  definitions: Record<string, SchemaNode>,
): string[] {
  const lines = ["| Field | Type | Notes |", "|---|---|---|"];
  for (const name of names) lines.push(propertyRow(name, properties[name], definitions));
  return lines;
}

/**
 * A top-level manifest definition (component or theme), split the way the
 * schema splits it: `required` first, in the order the schema lists them, then
 * everything else. The split is the point — the old file never stated it.
 */
function renderManifestDefinition(
  title: string,
  node: SchemaNode,
  filename: string,
  definitions: Record<string, SchemaNode>,
): string[] {
  const properties = node.properties ?? {};
  const required = (node.required ?? []).filter((name) => name in properties);
  const optional = Object.keys(properties).filter((name) => !required.includes(name));

  const lines: string[] = [`## ${title}`, ""];
  if (node.description) {
    lines.push(node.description, "");
  }
  lines.push(`Shipped as \`${filename}\`.`, "");
  lines.push(`### Required — all ${required.length}`, "");
  lines.push(
    `\`required\` names **every one of these ${required.length} fields**. A manifest that omits any ` +
      "of them does not validate, however sensible the omission looks — an empty object (`{}`) or " +
      "an empty array (`[]`) is how a component with nothing to say says it.",
    "",
  );
  lines.push(...propertyTable(properties, required, definitions), "");
  lines.push(`### Optional — ${optional.length}`, "");
  lines.push(...propertyTable(properties, optional, definitions), "");
  return lines;
}

/** A nested definition — one table, with each property marked required or not. */
function renderNestedDefinition(
  name: string,
  node: SchemaNode,
  definitions: Record<string, SchemaNode>,
): string[] {
  const lines: string[] = [`### \`${name}\``, ""];
  if (node.description) lines.push(node.description, "");

  if (node.enum) {
    lines.push(`A closed \`${node.type ?? "string"}\` vocabulary — ${node.enum.length} values:`, "");
    lines.push(...node.enum.map((v) => `- \`${v}\``), "");
    return lines;
  }

  const properties = node.properties ?? {};
  const required = new Set(node.required ?? []);
  const names = Object.keys(properties);
  if (names.length === 0) {
    if (node.additionalProperties && typeof node.additionalProperties === "object") {
      lines.push(`Every value is ${typeLabel(node.additionalProperties)}.`, "");
    }
    for (const note of constraintNotes(node)) lines.push(`- ${note}`);
    if (constraintNotes(node).length > 0) lines.push("");
    return lines;
  }

  lines.push("| Field | Type | Required | Notes |", "|---|---|---|---|");
  for (const prop of names) {
    lines.push(
      `| \`${prop}\` | ${typeLabel(properties[prop])} | ${required.has(prop) ? "yes" : "no"} | ` +
        `${notesCell(properties[prop], definitions)} |`,
    );
  }
  lines.push("");
  for (const note of constraintNotes(node)) lines.push(`- ${note}`);
  if (constraintNotes(node).length > 0) lines.push("");
  return lines;
}

/** Every `enum` in the document, with the path it sits at — walked, not listed. */
function collectEnums(node: unknown, path: string, out: { path: string; values: string[] }[] = []) {
  if (node === null || typeof node !== "object") return out;
  if (Array.isArray(node)) {
    node.forEach((item, i) => collectEnums(item, `${path}[${i}]`, out));
    return out;
  }
  const record = node as Record<string, unknown>;
  if (Array.isArray(record.enum) && record.enum.every((v) => typeof v === "string")) {
    out.push({ path, values: record.enum as string[] });
  }
  for (const [key, value] of Object.entries(record)) {
    if (key === "enum") continue;
    // `properties`/`definitions` are name maps, not keywords: skip the level so
    // the path reads `variant.responsive` rather than
    // `definitions.variant.properties.responsive`.
    const next = key === "properties" || key === "definitions" ? path : path ? `${path}.${key}` : key;
    collectEnums(value, next, out);
  }
  return out;
}

/** The `@ui:` header comment lines a component source carries, verbatim. */
function machineComments(source: string | undefined, prefix: string): string[] {
  if (!source) return [];
  return source
    .split("\n")
    .filter((line) => line.includes("@ui:"))
    .filter((line) => line.trimStart().startsWith(prefix))
    .map((line) => line.trim());
}

/**
 * Build `references/manifest.md` from the schema document plus one shipped
 * manifest as the worked example. Both are parameters so a test can hand it a
 * fixture schema and prove the file is derived rather than transcribed.
 */
export function renderManifestReference(
  schema: Record<string, unknown>,
  example: ManifestExample,
  schemaVersion: string,
  fileSets: KindFileSet[] = [],
): string {
  const definitions = (schema.definitions ?? {}) as Record<string, SchemaNode>;
  const lines: string[] = [];

  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir Manifest Schema Reference");
  lines.push("");
  if (typeof schema.description === "string") {
    lines.push(schema.description);
    lines.push("");
  }
  lines.push(
    `Everything below is read out of \`manifest.schema.json\` — \`schema_version\` ` +
      `${schema.schema_version}, \`stability\` ${schema.stability}, published at \`${schema.$id}\`` +
      (schema.amendment_policy ? `, amendment policy \`${schema.amendment_policy}\`` : "") +
      ". Field names, types, descriptions and enums are the schema's own, so this file cannot " +
      "drift from the contract it documents.",
  );
  lines.push("");
  lines.push(
    "A component manifest sits beside its HTML and CSS at " +
      "`registry/<primitives|recipes|patterns>/<name>/<name>.manifest.json`; a theme manifest is " +
      "`registry/themes/<name>.theme.json`. Every manifest carries a `$schema` — a path relative " +
      "to its own directory, so it resolves at any depth. `faqir create` writes one, and " +
      "`bun scripts/add-schema-refs.mjs --check` fails on any manifest whose value is missing or stale.",
  );
  lines.push("");
  lines.push(
    "The document is a `oneOf`: a file validates as **either** a component manifest **or** a theme " +
      "manifest, never both and never neither.",
  );
  lines.push("");
  lines.push(
    "**Authoring one.** `faqir create <name> --kind <primitive|recipe|pattern>` scaffolds a manifest " +
      "that already carries every required field and a resolvable `$schema`, and registers the " +
      "component — start there and fill it in, rather than from a blank file. Writing one by hand " +
      "means writing every field in the required table below: there is no field the validator " +
      "infers for you, and `faqir inspect <component>` prints a shipped one to work from.",
  );
  lines.push("");

  if (definitions.componentManifest) {
    lines.push(
      ...renderManifestDefinition(
        "Component Manifest",
        definitions.componentManifest,
        "<name>.manifest.json",
        definitions,
      ),
    );
  }
  if (definitions.themeManifest) {
    lines.push(
      ...renderManifestDefinition("Theme Manifest", definitions.themeManifest, "<name>.theme.json", definitions),
    );
  }

  const nested = Object.keys(definitions).filter(
    (name) => name !== "componentManifest" && name !== "themeManifest",
  );
  if (nested.length > 0) {
    lines.push("## Nested Types", "");
    lines.push(
      `The ${nested.length} shapes the two manifest definitions \`$ref\` into. A field typed ` +
        "`slot` above takes exactly the object documented here.",
      "",
    );
    for (const name of nested) lines.push(...renderNestedDefinition(name, definitions[name], definitions));
  }

  if (fileSets.length > 0) {
    const total = fileSets.reduce((n, k) => n + k.count, 0);
    lines.push("## File Set Per Kind", "");
    lines.push(
      "`files` requires `html`, `css` and `manifest` whatever the kind — `js` is declared by the " +
        `components that ship a controller, and only those. Counted across the ${total} manifests ` +
        "in `registry/`:",
      "",
    );
    lines.push("| `kind` | Components | Declare `files.js` |", "|---|---|---|");
    for (const k of fileSets) lines.push(`| \`${k.kind}\` | ${k.count} | ${k.withJs} |`);
    lines.push("");
  }

  const enums = collectEnums(schema.definitions, "");
  if (enums.length > 0) {
    lines.push("## Closed Enums", "");
    lines.push(
      `${enums.length} fields are closed vocabularies — a value outside the list fails validation. ` +
        "Widening one is a schema amendment, not a manifest edit.",
      "",
    );
    lines.push("| Field | Values |", "|---|---|");
    for (const e of enums) lines.push(`| \`${e.path}\` | ${enumValues(e.values)} |`);
    lines.push("");
  }

  const changelog = Array.isArray(schema.changelog) ? (schema.changelog as Record<string, unknown>[]) : [];
  if (changelog.length > 0) {
    lines.push("## Schema Changelog", "");
    lines.push("The schema carries its own history. `1.0` is frozen: until `2.0` it may only gain optional fields and widen enums.", "");
    lines.push("| Version | Task | Breaking | Note |", "|---|---|---|---|");
    for (const entry of changelog) {
      lines.push(
        `| \`${entry.version}\` | ${entry.task ? `\`${entry.task}\`` : "—"} | ` +
          `${entry.breaking ? "yes" : "no"} | ${mdCell(String(entry.note ?? ""))} |`,
      );
    }
    lines.push("");
  }

  lines.push(`## Worked Example — \`${example.manifestPath}\``, "");
  lines.push(
    `The shipped \`${example.name}\` manifest, verbatim. Not an illustration of one: this is the ` +
      "file in the registry, so every field it shows is a field that validates today.",
    "",
  );
  lines.push("```json");
  lines.push(example.manifestJson.replace(/\s+$/, ""));
  lines.push("```");
  lines.push("");

  const htmlComments = machineComments(example.html, "<!--");
  const cssComments = machineComments(example.css, "/*");
  if (htmlComments.length > 0 || cssComments.length > 0) {
    lines.push("## Machine Comments", "");
    lines.push(
      "The manifest is the contract; the sources repeat the machine-readable part of it in their " +
        `header comments, which \`faqir audit\` and the registry gate parse. From \`${example.name}\`:`,
      "",
    );
    if (htmlComments.length > 0) {
      lines.push("```html", ...htmlComments, "```", "");
    }
    if (cssComments.length > 0) {
      lines.push("```css", ...cssComments, "```", "");
    }
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

// ---------------------------------------------------------------------------
// Manifest loading
// ---------------------------------------------------------------------------

/** Load every manifest in the registry, grouped by layer, sorted by name. */
async function loadRegistryManifests(): Promise<Record<Layer, Manifest[]>> {
  const registry = getRegistryPath();
  const out: Record<Layer, Manifest[]> = { primitives: [], recipes: [], patterns: [] };
  for (const layer of LAYERS) {
    const dir = join(registry, layer);
    if (!existsSync(dir)) continue;
    const glob = new Bun.Glob("*/*.manifest.json");
    const paths: string[] = [];
    for (const rel of glob.scanSync({ cwd: dir })) paths.push(join(dir, rel));
    for (const p of paths.sort()) out[layer].push(await loadManifest(p));
  }
  return out;
}

/** Load a project's installed manifests, grouped by layer. */
async function loadInstalledManifests(cwd: string): Promise<Record<Layer, Manifest[]>> {
  const config = await readConfig(cwd);
  const out: Record<Layer, Manifest[]> = { primitives: [], recipes: [], patterns: [] };
  for (const layer of LAYERS) {
    for (const name of config.installed[layer]) {
      const path = join(cwd, config.output_dir, layer, name, `${name}.manifest.json`);
      if (existsSync(path)) out[layer].push(await loadManifest(path));
    }
  }
  return out;
}

function renderPlugins(plugins: PluginMetadata[], corePrefix: string): string[] {
  if (plugins.length === 0) return [];
  const lines: string[] = [];
  lines.push("## Official Plugins");
  lines.push("");
  lines.push("Load a plugin after `faqir-core.js`, or combine core plus every plugin with `faqir bundle --js`:");
  lines.push("");
  for (const plugin of plugins) {
    const summary = plugin.description ? ` — ${plugin.description}` : "";
    lines.push(
      `- \`${plugin.name}\` (${plugin.provides.map((item) => `\`${item}\``).join(", ")}): ` +
        `\`${corePrefix}/plugins/${plugin.file}\`${summary}`,
    );
  }
  lines.push("");
  return lines;
}

// ---------------------------------------------------------------------------
// Project skill: self-contained .faqir/SKILL.md
// ---------------------------------------------------------------------------

/**
 * Generate a project's `.faqir/SKILL.md`, scoped to its installed component set.
 * Self-contained (no external reference files): each installed component gets a
 * full manifest-derived section inline. Carries the generation header.
 */
export async function generateSkill(cwd: string): Promise<string> {
  const byLayer = await loadInstalledManifests(cwd);
  const schemaVersion = await getSchemaVersion();
  const config = await readConfig(cwd);
  const corePrefix = `${config.output_dir.replace(/\/$/, "")}/core`;
  const plugins = loadPluginMetadata(join(cwd, corePrefix, "plugins"));

  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir UI Framework Skill");
  lines.push("");
  lines.push("Zero-class, manifest-driven UI. When building UI, read `.faqir/context.json` first; this skill documents the components this project installs.");
  lines.push("");

  lines.push(...renderAttributeProtocol());
  lines.push(...renderStrictRules());
  lines.push(...renderLayoutSystem());
  lines.push(...renderInventory(byLayer));
  lines.push(...renderPlugins(plugins, corePrefix));

  // Aliases — alternate names installed components answer to, so an agent
  // searching e.g. "alert" discovers it maps to "callout".
  const aliasPairs: string[] = [];
  for (const layer of LAYERS) {
    for (const m of byLayer[layer]) {
      for (const alias of m.aliases ?? []) aliasPairs.push(`- \`${alias}\` → \`${m.name}\``);
    }
  }
  if (aliasPairs.length > 0) {
    lines.push("## Aliases");
    lines.push("");
    lines.push("These names resolve to the component on the right — use `faqir add <alias>` or the canonical `data-ui` value:");
    lines.push("");
    lines.push(...aliasPairs);
    lines.push("");
  }

  // Recipe controllers (interactive components need their JS controller loaded).
  if (byLayer.recipes.length > 0) {
    lines.push("## Recipe Controllers");
    lines.push("");
    lines.push("Interactive components auto-initialize via the core script, or import a controller directly:");
    lines.push("");
    for (const m of byLayer.recipes) {
      lines.push(
        `- \`import { ${factoryName(m.name)} } from "./${config.output_dir}/recipes/${m.name}/${m.name}.js"\``,
      );
    }
    lines.push("");
    lines.push(`Auto-init: \`<script type="module" src="${config.output_dir}/core/faqir.js"></script>\``);
    lines.push("");
  }

  // Per-component sections.
  const sectionTitle: Record<Layer, string> = {
    primitives: "Primitives",
    recipes: "Recipes",
    patterns: "Patterns",
  };
  for (const layer of LAYERS) {
    if (byLayer[layer].length === 0) continue;
    lines.push(`## ${sectionTitle[layer]}`);
    lines.push("");
    for (const m of byLayer[layer]) lines.push(...renderComponentSection(m, 3));
  }

  // Canonical compositions from installed patterns.
  const compositions = renderCompositions(byLayer.patterns);
  if (compositions.length) lines.push(...compositions);

  lines.push(...renderDataDriven());
  // Scaffolds and themes are registry-wide, not per-install: a project agent
  // needs `faqir scaffold invoice` and a theme name it can actually pass just as
  // much as the shipped skill does, and it keeps the CLI reference's pointers
  // resolvable in both skills.
  lines.push(...renderScaffolds());
  lines.push(...renderThemes(getRegistryPath()));
  lines.push(...renderCliReference());

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/** Write the project's `.faqir/SKILL.md`. */
export async function writeSkillFile(cwd: string): Promise<string> {
  const content = await generateSkill(cwd);
  const faqirDir = join(cwd, ".faqir");
  ensureDir(faqirDir);
  const outPath = join(faqirDir, "SKILL.md");
  await Bun.write(outPath, content);
  return outPath;
}

// ---------------------------------------------------------------------------
// Shipped skill: registry-wide .claude/skills/faqir-creator
// ---------------------------------------------------------------------------

/**
 * The skill's own metadata (frontmatter). This is authored identity, not
 * manifest-derived — Claude Code matches on it to route Faqir tasks here.
 */
const SHIPPED_FRONTMATTER_DESCRIPTION =
  "Expert agent for the Faqir UI framework — generates, audits, repairs, and explains zero-class, manifest-driven UI components and pages. Use when building HTML pages or components with Faqir UI, when the user asks to create/modify/audit Faqir UI markup, when working with data-ui/data-part/data-variant/data-state attributes, when generating page layouts using Faqir tokens and primitives, when creating new registry components (primitives, recipes, patterns), when connecting pages to server data via l-source directive or apiSource(), when picking or switching the visual theme of a page, or when building printable documents (invoices, reports, forms). Triggers on any Faqir UI task including component creation, page scaffolding, code auditing, token usage, theme selection, reactive directive usage (l-data, l-model, l-for, l-source), data-driven rendering, document/print layout, and CLI operations.";

/** A single generated file destined for the shipped skill directory. */
export interface GeneratedFile {
  /** Path relative to `.claude/skills/faqir-creator/`. */
  relPath: string;
  content: string;
}

const REFERENCE_LABEL: Record<Layer, string> = {
  primitives: "Primitives",
  recipes: "Recipes",
  patterns: "Patterns",
};

/** Build one per-layer reference file (references/<layer>.md). */
function renderReferenceFile(layer: Layer, manifests: Manifest[], schemaVersion: string): string {
  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push(`# Faqir ${REFERENCE_LABEL[layer]} Reference`);
  lines.push("");
  lines.push(
    `${manifests.length} ${layer}, each with its anatomy tree, variant table, and safe/unsafe transforms — all derived from the component manifest.`,
  );
  lines.push("");
  for (const m of manifests) lines.push(...renderComponentSection(m, 2));
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/** Build the shipped SKILL.md (frontmatter + framework sections + inventory + compositions). */
function renderShippedSkill(
  byLayer: Record<Layer, Manifest[]>,
  schemaVersion: string,
  plugins: PluginMetadata[],
): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("name: faqir-creator");
  lines.push(`description: ${SHIPPED_FRONTMATTER_DESCRIPTION}`);
  lines.push("---");
  lines.push("");
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir Creator");
  lines.push("");
  lines.push(
    "Expert agent for the Faqir UI framework. Generate class-free HTML using data attributes, design tokens, and manifest contracts. Every component contract below is generated from its manifest.",
  );
  lines.push("");

  lines.push(...renderAttributeProtocol());
  lines.push(...renderStrictRules());
  lines.push(...renderLayoutSystem());
  lines.push(...renderInventory(byLayer));
  lines.push(...renderPlugins(plugins, "registry/core"));
  lines.push(...renderCompositions(byLayer.patterns));
  lines.push(...renderDataDriven());
  lines.push(...renderScaffolds());
  lines.push(...renderThemes(getRegistryPath()));
  lines.push(...renderCliReference());

  lines.push("## Per-Component Reference");
  lines.push("");
  lines.push("Full anatomy trees, variant tables, and safe/unsafe transforms for every component:");
  lines.push("");
  for (const layer of LAYERS) {
    if (byLayer[layer].length === 0) continue;
    lines.push(
      `- [references/${layer}.md](references/${layer}.md) — ${byLayer[layer].length} ${REFERENCE_LABEL[layer].toLowerCase()}`,
    );
  }
  lines.push("- [references/tokens.md](references/tokens.md) — every design token, derived from `registry/tokens/*.css`");
  lines.push(
    "- [references/directives.md](references/directives.md) — every faqir-core directive, modifier " +
      "and magic, plus the plugin vocabulary",
  );
  lines.push(
    "- [references/manifest.md](references/manifest.md) — the manifest contract, derived from " +
      "`manifest.schema.json`: which fields are required, every closed enum, one shipped example",
  );
  lines.push("");

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/**
 * Generate every file of the shipped `faqir-creator` skill from the registry:
 * the SKILL.md plus one reference file per layer. Deterministic and idempotent.
 */
export async function generateShippedSkillFiles(): Promise<GeneratedFile[]> {
  const byLayer = await loadRegistryManifests();
  const schemaVersion = await getSchemaVersion();
  const plugins = loadPluginMetadata(join(getRegistryPath(), "core", "plugins"));

  const files: GeneratedFile[] = [
    { relPath: "SKILL.md", content: renderShippedSkill(byLayer, schemaVersion, plugins) },
  ];
  for (const layer of LAYERS) {
    files.push({
      relPath: join("references", `${layer}.md`),
      content: renderReferenceFile(layer, byLayer[layer], schemaVersion),
    });
  }
  // The token reference is derived from registry/tokens/*.css rather than the
  // manifests, so `check:skill` gates it exactly like the per-layer files.
  files.push({
    relPath: join("references", "tokens.md"),
    content: renderTokensReference(getRegistryPath(), schemaVersion),
  });
  // Likewise the directive reference: derived from the engine's declared
  // vocabulary and the plugin headers, so `check:skill` gates it too.
  files.push({
    relPath: join("references", "directives.md"),
    content: renderDirectivesReference(
      readFileSync(enginePath(), "utf8"),
      join(getRegistryPath(), "core", "plugins"),
      schemaVersion,
    ),
  });
  // And the manifest reference: derived from `manifest.schema.json` itself, so
  // a field added to the contract cannot go undocumented — with `check:skill`
  // now covering all seven files of the skill directory.
  files.push({
    relPath: join("references", "manifest.md"),
    content: renderManifestReference(
      await loadManifestSchema(),
      manifestExample(),
      schemaVersion,
      kindFileSets(byLayer),
    ),
  });
  return files;
}

/**
 * Per-`kind` controller counts, read off the manifests rather than asserted: a
 * kind that starts shipping JS moves its own row.
 */
export function kindFileSets(byLayer: Record<Layer, Manifest[]>): KindFileSet[] {
  const out = new Map<string, KindFileSet>();
  for (const layer of LAYERS) {
    for (const m of byLayer[layer]) {
      const row = out.get(m.kind) ?? { kind: m.kind, count: 0, withJs: 0 };
      row.count++;
      if (m.files?.js) row.withJs++;
      out.set(m.kind, row);
    }
  }
  return [...out.values()].sort((a, b) => a.kind.localeCompare(b.kind));
}

/**
 * The worked example the manifest reference carries: the shipped `button`
 * component, read off disk rather than transcribed — the version, the `$schema`
 * and the `changes[]` entry in the reference are whatever the registry ships.
 */
export function manifestExample(): ManifestExample {
  const dir = join(getRegistryPath(), "primitives", "button");
  const read = (file: string) => (existsSync(join(dir, file)) ? readFileSync(join(dir, file), "utf8") : undefined);
  return {
    name: "button",
    manifestPath: "registry/primitives/button/button.manifest.json",
    manifestJson: readFileSync(join(dir, "button.manifest.json"), "utf8"),
    html: read("button.html"),
    css: read("button.css"),
  };
}

/** The engine source the directive vocabulary is declared in. */
export function enginePath(): string {
  return join(getPackageRoot(), "src", "core-src", "engine.js");
}

/** Absolute path to the shipped skill directory. */
export function shippedSkillDir(): string {
  return join(getPackageRoot(), ".claude", "skills", "faqir-creator");
}

/**
 * Write the shipped skill to `.claude/skills/faqir-creator/`. Returns the
 * absolute paths written. Used by `scripts/gen-skill.mjs`.
 */
export async function writeShippedSkill(): Promise<string[]> {
  const files = await generateShippedSkillFiles();
  const dir = shippedSkillDir();
  const written: string[] = [];
  for (const f of files) {
    const abs = join(dir, f.relPath);
    ensureDir(join(abs, ".."));
    await Bun.write(abs, f.content);
    written.push(abs);
  }
  return written;
}
