// Manifest-derived Claude Code skill generator (task 0.5-07, FAQIR-PLAN §8.2).
//
// Replaces the old static SKILL.md template. Every per-component section —
// anatomy tree, variant table, safe/unsafe transforms — plus the canonical
// compositions are DERIVED from manifests, so the shipped `faqir-creator` skill
// is regenerated from this same pipeline (dogfood) and never hand-maintained.
//
// Two entry points share one set of renderers:
//   • generateSkill(cwd)          → a project's self-contained .faqir/SKILL.md,
//                                    scoped to its installed component set.
//   • generateShippedSkillFiles() → the registry-wide .claude/skills/faqir-creator
//                                    skill (SKILL.md + per-layer references),
//                                    covering every component in registry/.
//
// Output carries a grep-able generation header and no timestamps, so
// regeneration is byte-idempotent (gated by `bun run check:skill`).

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { readConfig } from "../utils/config";
import { ensureDir, getPackageRoot, getRegistryPath } from "../utils/fs";
import { loadManifest, type Manifest } from "../manifest";
import { BREAKPOINTS, BREAKPOINT_LIST, TIERS, responsiveAttribute } from "../utils/breakpoints";
import {
  ARCHETYPES,
  LAYOUT_MECHANISMS,
  LAYOUT_PRIMITIVES,
  LAYOUT_RULES,
  MEASURE_TOKENS,
  RHYTHM_TOKENS,
  SPACING_BANDS,
  grammarLine,
  rhythmLine,
  spacingLadderLine,
} from "../utils/layout";
import { TOKEN_MODIFIERS } from "../protocol";
import { getSchemaVersion } from "../utils/schema";
import { loadPluginMetadata, type PluginMetadata } from "./plugins";

/** Stable, grep-able marker proving a file came out of this generator. */
export const SKILL_GENERATION_MARKER = "GENERATED by faqir · manifest-derived skill";

const LAYERS = ["primitives", "recipes", "patterns"] as const;
type Layer = (typeof LAYERS)[number];

/**
 * The generation header stamped into every generated file. No timestamp — the
 * only variable is `schema_version`, so identical inputs produce identical bytes.
 */
function generationHeader(schemaVersion: string): string {
  return (
    `<!-- ${SKILL_GENERATION_MARKER} · schema_version ${schemaVersion} · ` +
    `regenerate with \`bun run gen:skill\` · do not edit by hand -->`
  );
}

/** Turn `date-picker` into `createDatePicker` (recipe controller factory). */
function factoryName(recipe: string): string {
  return "create" + recipe.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
}

// ---------------------------------------------------------------------------
// Per-component renderers (manifest-derived)
// ---------------------------------------------------------------------------

/**
 * Render a component's anatomy tree: the root element followed by its named
 * slots, each annotated with its tag hint, required-ness, and description.
 * Derived entirely from `anatomy` + `slots`.
 */
function renderAnatomyTree(m: Manifest): string[] {
  const lines: string[] = ["```text"];
  const content = m.anatomy.content_model ? ` · content: ${m.anatomy.content_model}` : "";
  lines.push(`${m.anatomy.selector}  ·  <${m.anatomy.tag}>${content}`);

  const slots = Object.entries(m.slots ?? {});
  slots.forEach(([name, slot], i) => {
    const branch = i === slots.length - 1 ? "└─" : "├─";
    const tag = slot.tag_hint ? `<${slot.tag_hint}>` : "";
    const req = slot.required ? "required" : "optional";
    const desc = slot.description ? `  — ${slot.description}` : "";
    // name is informational; the real contract is the selector.
    lines.push(`${branch} ${slot.selector}  ${tag}  ${req}${desc}`.replace(/\s+$/g, ""));
  });

  lines.push("```");
  return lines;
}

/**
 * Render a markdown variant table from `variants` (empty → a single note).
 *
 * A component declaring a responsive group (task 0.8-02) gains a Responsive
 * column plus one grammar line below the table, so an agent reading the skill
 * learns `data-cols-md="6"` from the manifest rather than from prose someone
 * remembered to write. Emitted only when a group declares it — the column is
 * absent, not dashed, everywhere else.
 */
function renderVariantTable(m: Manifest): string[] {
  const entries = Object.entries(m.variants ?? {});
  if (entries.length === 0) return ["_No variants._"];

  const responsiveGroups = entries.filter(([, v]) => v.responsive === true);
  const responsive = responsiveGroups.length > 0;
  const lines: string[] = responsive
    ? [
        "| Variant | Values | Default | Attribute | Applied to | Responsive |",
        "|---------|--------|---------|-----------|------------|------------|",
      ]
    : [
        "| Variant | Values | Default | Attribute | Applied to |",
        "|---------|--------|---------|-----------|------------|",
      ];
  for (const [name, v] of entries) {
    const values = v.values.map((x) => `\`${x}\``).join(", ");
    const row = `| ${name} | ${values} | \`${v.default}\` | \`${v.attr}\` | ${v.applied_to ?? "root"} |`;
    if (!responsive) {
      lines.push(row);
      continue;
    }
    const tiers =
      v.responsive === true ? TIERS.map((t) => `\`${responsiveAttribute(v.attr, t)}\``).join(", ") : "—";
    lines.push(`${row} ${tiers} |`);
  }
  if (responsive) {
    const example = responsiveGroups[0][1];
    lines.push("");
    lines.push(
      `- **Responsive:** the marked groups accept \`<attr>-<tier>\` for the canon tiers ` +
        `${TIERS.map((t) => `\`${t}\` (${BREAKPOINTS[t].rem}rem)`).join(", ")} — ` +
        `\`${responsiveAttribute(example.attr, "md")}="${example.values[example.values.length - 1]}"\` ` +
        `applies that value from \`md\` up. Mobile-first: the unsuffixed attribute is the base.`,
    );
  }
  return lines;
}

/** Render the safe / unsafe transform lists. */
function renderTransforms(m: Manifest): string[] {
  const lines: string[] = [];
  if (m.safe_transforms?.length) {
    lines.push(`- **Safe transforms:** ${m.safe_transforms.map((t) => `\`${t}\``).join(", ")}`);
  }
  if (m.unsafe_transforms?.length) {
    lines.push(`- **Unsafe (never do):** ${m.unsafe_transforms.map((t) => `\`${t}\``).join(", ")}`);
  }
  return lines;
}

/** One-line accessibility summary derived from `a11y`. */
function renderA11y(m: Manifest): string[] {
  const a = m.a11y;
  if (!a) return [];
  const parts: string[] = [];
  if (a.role) parts.push(`role=${a.role}`);
  if (a["aria-modal"]) parts.push("aria-modal");
  if (a.focus_trap) parts.push("focus-trap");
  if (a.escape_closes) parts.push("escape-closes");
  if (a.return_focus) parts.push(`return-focus→${a.return_focus}`);
  const keys = a.keyboard ? Object.keys(a.keyboard) : [];
  if (keys.length) parts.push(`keys: ${keys.join(", ")}`);
  if (parts.length === 0 && (!a.required_attrs || a.required_attrs.length === 0)) return [];
  const lines: string[] = [];
  if (parts.length) lines.push(`- **A11y:** ${parts.join(" · ")}`);
  if (a.required_attrs?.length) {
    lines.push(`- **Required ARIA:** ${a.required_attrs.map((x) => `\`${x}\``).join("; ")}`);
  }
  return lines;
}

/** The canonical HTML template for a component (first of `html`, else first key). */
function primaryTemplate(m: Manifest): string | undefined {
  const t = m.templates ?? {};
  if (typeof t.html === "string") return t.html;
  const first = Object.values(t)[0];
  return typeof first === "string" ? first : undefined;
}

/**
 * A full per-component reference section: heading, meta line, description,
 * canonical template, anatomy tree, variant table, transforms, and a11y.
 * `headingLevel` lets the caller nest it (### in references, #### inline).
 */
export function renderComponentSection(m: Manifest, headingLevel = 3): string[] {
  const h = "#".repeat(headingLevel);
  const lines: string[] = [];
  lines.push(`${h} ${m.name}`);
  lines.push("");
  const meta = [`kind: ${m.kind}`];
  if (m.category) meta.push(`category: ${m.category}`);
  if (m.aliases?.length) meta.push(`aliases: ${m.aliases.join(", ")}`);
  if (m.files?.js) meta.push(`controller: ${factoryName(m.name)}()`);
  lines.push(`_${meta.join(" · ")}_`);
  lines.push("");
  if (m.description) {
    lines.push(m.description);
    lines.push("");
  }

  const tpl = primaryTemplate(m);
  if (tpl) {
    lines.push("```html");
    lines.push(tpl);
    lines.push("```");
    lines.push("");
  }

  lines.push("**Anatomy**");
  lines.push("");
  lines.push(...renderAnatomyTree(m));
  lines.push("");

  lines.push("**Variants**");
  lines.push("");
  lines.push(...renderVariantTable(m));
  lines.push("");

  const transforms = renderTransforms(m);
  const a11y = renderA11y(m);
  if (transforms.length || a11y.length) {
    lines.push(...transforms);
    lines.push(...a11y);
    lines.push("");
  }

  return lines;
}

/**
 * Render up to `limit` canonical compositions from pattern manifests. A pattern
 * IS a canonical composition — its template wires primitives/recipes together
 * and `composition.contains` names them. Deterministic: patterns sorted by name.
 */
function renderCompositions(patterns: Manifest[], limit = 3): string[] {
  const chosen = [...patterns].sort((a, b) => a.name.localeCompare(b.name)).slice(0, limit);
  if (chosen.length === 0) return [];

  const lines: string[] = ["## Canonical Compositions", ""];
  lines.push(
    "Real component compositions, taken verbatim from pattern manifests. Each shows how primitives and recipes assemble into a working unit.",
  );
  lines.push("");
  for (const p of chosen) {
    lines.push(`### ${p.name}`);
    lines.push("");
    if (p.description) {
      lines.push(p.description);
      lines.push("");
    }
    const uses = p.composition?.contains ?? [];
    if (uses.length) {
      lines.push(`Composes: ${uses.map((u) => `\`${u}\``).join(", ")}`);
      lines.push("");
    }
    const tpl = primaryTemplate(p);
    if (tpl) {
      lines.push("```html");
      lines.push(tpl);
      lines.push("```");
      lines.push("");
    }
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Shared framework sections (constant — the DOM contract, not per-component)
// ---------------------------------------------------------------------------

function renderAttributeProtocol(): string[] {
  return [
    "## The Attribute Protocol",
    "",
    "Every Faqir component uses exactly five data attributes — this is the DOM contract.",
    "",
    "| Attribute | Purpose | Example |",
    "|-----------|---------|---------|",
    "| `data-ui` | Component identity (root) | `data-ui=\"button\"` |",
    "| `data-part` | Named slot within parent | `data-part=\"trigger\"` |",
    "| `data-state` | Runtime state (JS-only) | `data-state=\"open\"` |",
    "| `data-variant` | Visual variant (set once) | `data-variant=\"primary\"` |",
    "| `data-size` | Size variant | `data-size=\"lg\"` |",
    "",
    "CSS targets attributes (`[data-ui=\"button\"]`), state via `[data-state=\"open\"]`, theme via `data-theme` on `<html>`. Every value comes from a `--token`.",
    "",
  ];
}

function renderStrictRules(): string[] {
  return [
    "## Strict Rules",
    "",
    "1. **NEVER** use `class=` attributes. Use `data-ui`/`data-variant`/`data-size`/`data-state`/`data-part`.",
    "2. **NEVER** hardcode colors, spacing, or sizes. Use `var(--token-name)`.",
    "3. **NEVER** use `!important`.",
    "4. **NEVER** use IDs as CSS selectors. IDs are for ARIA relationships only.",
    "5. CSS selectors **MUST** be attribute selectors: `[data-ui=\"button\"]`, not `.btn`.",
    "6. `data-state` is the **ONLY** attribute JS may modify at runtime.",
    "7. Always add the ARIA attributes each manifest requires.",
    "8. Recipes auto-initialize — include `faqir-core.js` and emit the full inner structure.",
    "",
  ];
}

/**
 * The layout system (task 0.8-12): the doctrine, the five primitives, the
 * ladder and the grammar. Authored prose lives in `src/utils/layout.ts` and the
 * numbers in `src/utils/breakpoints.ts` — this renderer only arranges them, so
 * the skill cannot drift from README, `docs/layout.md` or `faqir context`.
 */
function renderLayoutSystem(): string[] {
  const lines: string[] = ["## Layout System", ""];
  lines.push(
    "Page structure is five primitives, one token ladder and one breakpoint canon — never a utility class, never a hand-written `max-width`. Reach for the FIRST mechanism that solves the problem:",
  );
  lines.push("");
  for (const m of LAYOUT_MECHANISMS) lines.push(`${m.step}. **${m.title}.** ${m.summary}`);
  lines.push("");
  lines.push("| Primitive | Mechanism | Reach for it when |");
  lines.push("|-----------|-----------|-------------------|");
  for (const p of LAYOUT_PRIMITIVES) {
    lines.push(`| \`${p.name}\` | ${p.mechanism} | ${p.use} |`);
  }
  lines.push("");
  lines.push("**The ladder** — every responsive threshold in Faqir is one of these four:");
  lines.push("");
  lines.push("| Tier | Min-width | px |");
  lines.push("|------|-----------|----|");
  for (const b of BREAKPOINT_LIST) lines.push(`| \`${b.tier}\` | \`${b.rem}rem\` | ${b.px} |`);
  lines.push("");
  lines.push(`**The grammar** — ${grammarLine()}`);
  lines.push("");
  lines.push("```html");
  lines.push(
    `<div data-ui="grid" data-cols="1" ${responsiveAttribute("cols", "md")}="2" ${responsiveAttribute("cols", "lg")}="4" data-gap="4">`,
  );
  lines.push('  <div data-ui="card"><div data-part="body">One up on a phone, four from 64rem.</div></div>');
  lines.push("</div>");
  lines.push("```");
  lines.push("");
  for (const r of LAYOUT_RULES) lines.push(`- ${r}`);
  lines.push("");
  lines.push(
    `**Measure** (centred column widths): ${MEASURE_TOKENS.map((m) => `\`--${m.token}\` (${m.role})`).join(", ")}.`,
  );
  lines.push(
    `**Rhythm** (page air): ${RHYTHM_TOKENS.map((r) => `\`--${r.token}\` (${r.role})`).join(", ")}.`,
  );
  lines.push("");
  lines.push("**The default rhythm** (FAQIR-SPEC §20) — the one thing that means you do NOT have to wrap a sequence to space it:");
  lines.push("");
  lines.push(rhythmLine());
  lines.push("");
  lines.push(`**Spacing ladder** — ${spacingLadderLine()}.`);
  lines.push("");
  for (const band of SPACING_BANDS) {
    lines.push(`- **${band.label}:** \`--${band.from}\` through \`--${band.to}\` — ${band.use}.`);
  }
  lines.push("");
  lines.push(
    "**Density axis** — `data-density=\"compact\"` tightens the element and its subtree; `data-density=\"comfortable\"` resets a nested subtree. Spacing through `--space-64`, control heights, `--section-gap-sm|md|lg`, and `--content-gutter` remap in the nearest scope. It is pure CSS, not a sixth protocol attribute.",
  );
  lines.push("");
  lines.push(
    `Copy-ready page archetypes — ${ARCHETYPES.map((a) => a.title).join(", ")} — are in \`docs/layout.md\`, and each one is audited on every test run.`,
  );
  lines.push("");
  return lines;
}

function renderDataDriven(): string[] {
  return [
    "## Data-Driven Rendering",
    "",
    "`l-source` (built into `faqir-core.js`) binds any `l-data` element to a REST endpoint:",
    "",
    "```html",
    "<div l-data=\"{ newTitle: '' }\" l-source:tasks=\"/api/tasks\">",
    "  <template l-for=\"task in tasks\"><span l-text=\"task.title\"></span></template>",
    "  <form @submit.prevent=\"$tasks.create({ title: newTitle }).then(() => newTitle = '')\">",
    "    <input data-ui=\"input\" l-model=\"newTitle\">",
    "    <button data-ui=\"button\" data-variant=\"primary\">Add</button>",
    "  </form>",
    "</div>",
    "```",
    "",
    "Auto-injected: `tasks` (array), `tasksLoading`, `tasksError`. Controller: `$tasks.load()`, `.create()`, `.update(id, payload)`, `.remove(id)`, `.refresh()`.",
    "Modifiers: `.lazy`, `.optimistic`, `.poll.5000`, `.key.uuid`.",
    "The legacy `apiSource()` factory (spread into `l-data`, needs `api-source.js` first) injects `items`/`loading`/`submitting`/`error` + `load()`/`create()`/`update()`/`remove()`.",
    "Both are **data layers** — recipe controllers still never call `fetch`.",
    "",
  ];
}

function renderCliReference(): string[] {
  return [
    "## CLI Reference",
    "",
    "```bash",
    "faqir init [--theme <name>]          # scaffold a project",
    "faqir add <component...>             # add components (resolves deps, accepts aliases)",
    "faqir remove <component...>          # remove (checks dependents)",
    "faqir list                          # installed / available",
    "faqir search <query>                # find by name, alias, or description",
    "faqir create <name> --kind <type>   # scaffold a custom component",
    "faqir inspect <component>           # full manifest",
    "faqir explain <component> [--json]  # human/agent explanation",
    "faqir trace <component> [--json]    # dependency graph",
    "faqir audit [--json]                # validate markup against manifests",
    "faqir repair                        # auto-fix audit issues",
    "faqir conform [--dry-run]           # normalize markup",
    "faqir diff [component...]           # user drift vs pristine baseline",
    "faqir upgrade [component...]        # three-way merge to the latest version",
    "faqir bundle [--minify] [--watch]   # compose CSS into one file",
    "faqir theme set|list|create <name>  # manage themes",
    "faqir context [--format json|md|cursorrules|llms] [--skill]",
    "```",
    "",
  ];
}

/** Component inventory grouped by layer, derived from the loaded manifests. */
function renderInventory(byLayer: Record<Layer, Manifest[]>): string[] {
  const lines: string[] = ["## Component Inventory", ""];
  const label: Record<Layer, string> = {
    primitives: "Primitives (CSS-only)",
    recipes: "Recipes (CSS + JS controller)",
    patterns: "Patterns (composition, no JS)",
  };
  for (const layer of LAYERS) {
    const names = byLayer[layer].map((m) => m.name).sort();
    if (names.length === 0) continue;
    lines.push(`**${names.length} ${label[layer]}:** ${names.join(", ")}`);
    lines.push("");
  }
  return lines;
}

// ---------------------------------------------------------------------------
// Token reference (task 1.0R-02) — derived from registry/tokens/*.css
//
// `references/tokens.md` was hand-maintained and drifted: it quoted shadow values
// the source had not carried for months, and the surface ramp, the measure ladder
// and `--leading-loose` were missing outright. Nothing below is transcribed — the
// group names, their blurbs, the `── Banner ──` sub-headings, every value and
// every px note are read out of the token sources, and the modifier table is
// `TOKEN_MODIFIERS` verbatim, so `data-density` / `data-motion` / `data-theme`
// are stated once in the codebase and read twice (here and by `SPEC-1.0.md` §4).
// ---------------------------------------------------------------------------

/** One declared custom property, with the banner it sits under. */
interface TokenDeclaration {
  /** Name without the leading `--`. */
  name: string;
  /** Declared value, verbatim, whitespace collapsed. */
  value: string;
  /** Trailing same-line comment, e.g. `16px`. */
  note?: string;
  /** The `── Label ──` banner this declaration follows, if any. */
  section?: string;
}

/** One token file: its `@ui:tokens` group, header blurb and `:root` declarations. */
interface TokenGroup {
  group: string;
  file: string;
  blurb?: string;
  tokens: TokenDeclaration[];
  /** `true` when the file declares into `[data-density]` scopes (density.css). */
  scoped: boolean;
}

/** Drop the internal task/plan references the source comments carry. */
function stripSourceRefs(text: string): string {
  return text.replace(/\s*\((?:task|see)\s[^)]*\)/gi, "").trim();
}

/** Collapse a comment or value onto one line. */
function oneLine(text: string): string {
  return text.trim().replace(/\s+/g, " ");
}

/**
 * A same-length copy with every comment blanked. Brace scanning runs against
 * this, because a `:root` body legitimately contains `}` inside a comment
 * (`document.css` documents `@page { … }` there) and would otherwise truncate.
 */
function maskComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, (c) => " ".repeat(c.length));
}

/**
 * The bodies of every `<selector> { … }` block, sliced out of the ORIGINAL css
 * (comments intact — they carry the sub-headings and px notes) using offsets
 * found on the masked copy. `selector` must contain no capture group.
 */
function blockBodies(css: string, selector: string): string[] {
  const masked = maskComments(css);
  const out: string[] = [];
  for (const m of masked.matchAll(new RegExp(`${selector}\\s*\\{([^{}]*)\\}`, "g"))) {
    const start = (m.index ?? 0) + m[0].indexOf("{") + 1;
    out.push(css.slice(start, start + m[1].length));
  }
  return out;
}

/**
 * Walk a block body in source order, returning every custom property with the
 * banner it follows and its trailing same-line comment. Comments are read, not
 * skipped: they carry the sub-headings and the px equivalents.
 */
function scanDeclarations(body: string): TokenDeclaration[] {
  const out: TokenDeclaration[] = [];
  let section: string | undefined;
  let prevEnd = -1;
  for (const m of body.matchAll(/\/\*([\s\S]*?)\*\/|--([a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    const start = m.index ?? 0;
    if (m[1] !== undefined) {
      const banner = /──\s*([^─]+?)\s*──/.exec(m[1]);
      if (banner) {
        section = stripSourceRefs(oneLine(banner[1]));
      } else if (prevEnd >= 0 && out.length > 0 && !body.slice(prevEnd, start).includes("\n")) {
        // A comment on the same line as the previous declaration annotates it.
        out[out.length - 1].note = oneLine(m[1]);
      }
      continue;
    }
    out.push({ name: m[2], value: oneLine(m[3]), section });
    prevEnd = start + m[0].length;
  }
  return out;
}

/** The `@ui:tokens <group> — <blurb>` header every token file carries. */
function tokenHeader(css: string): { group: string; blurb?: string } | undefined {
  const line = /@ui:tokens\s+(\S+)([^\n]*)/.exec(css);
  if (!line) return undefined;
  const tail = /—\s*(.+?)\s*(?:\*\/)?$/.exec(line[2]);
  return { group: line[1], blurb: tail ? stripSourceRefs(tail[1]) : undefined };
}

/**
 * The token files in cascade order, read out of `tokens/index.css` itself — the
 * order the reference documents is the order the browser resolves.
 */
function tokenFileOrder(tokensDir: string): string[] {
  const index = join(tokensDir, "index.css");
  if (!existsSync(index)) return [];
  return [...readFileSync(index, "utf8").matchAll(/@import\s+['"]\.\/([^'"]+)['"]/g)].map((m) => m[1]);
}

/** Every token file's `:root` declarations, grouped, in cascade order. */
function loadTokenGroups(tokensDir: string): TokenGroup[] {
  const groups: TokenGroup[] = [];
  for (const file of tokenFileOrder(tokensDir)) {
    const path = join(tokensDir, file);
    if (!existsSync(path)) continue;
    const css = readFileSync(path, "utf8");
    const header = tokenHeader(css);
    if (!header) continue;
    groups.push({
      group: header.group,
      file,
      blurb: header.blurb,
      tokens: blockBodies(css, ":root").flatMap(scanDeclarations),
      scoped: /\[data-density="/.test(maskComments(css)),
    });
  }
  return groups;
}

/** The `[data-density="<scope>"]` declarations of a token file, in source order. */
function densityScope(css: string, scope: string): TokenDeclaration[] {
  return blockBodies(css, `\\[data-density="${scope}"\\]`).flatMap(scanDeclarations);
}

/** A markdown cell — token values never contain a backtick, but may contain a pipe. */
function cell(value: string): string {
  return `\`${value.replace(/\|/g, "\\|")}\``;
}

/** One table of declarations. Optional columns appear only when they carry data. */
function renderTokenTable(
  tokens: TokenDeclaration[],
  valueLabel = "Value",
  extra?: { label: string; render: (t: TokenDeclaration) => string },
): string[] {
  const noted = tokens.some((t) => t.note);
  const head = ["Token", valueLabel, ...(extra ? [extra.label] : []), ...(noted ? ["Notes"] : [])];
  const lines = [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`];
  for (const t of tokens) {
    const row = [cell(`--${t.name}`), cell(t.value)];
    if (extra) row.push(extra.render(t));
    if (noted) row.push(t.note ?? "—");
    lines.push(`| ${row.join(" | ")} |`);
  }
  return lines;
}

/** Split declarations into their `── Banner ──` runs, preserving source order. */
function bySection(tokens: TokenDeclaration[]): { section?: string; tokens: TokenDeclaration[] }[] {
  const out: { section?: string; tokens: TokenDeclaration[] }[] = [];
  for (const t of tokens) {
    const last = out[out.length - 1];
    if (last && last.section === t.section) last.tokens.push(t);
    else out.push({ section: t.section, tokens: [t] });
  }
  return out;
}

/** The sanctioned token modifiers, stated once in `src/protocol.ts`. */
function renderTokenModifiers(): string[] {
  const lines: string[] = ["## Sanctioned Token Modifiers", ""];
  lines.push(
    `${TOKEN_MODIFIERS.length} attributes are part of the frozen contract without being protocol ` +
      "attributes: each re-declares design tokens for its subtree, and every descendant inherits the " +
      "result. None names a component, fills a slot, or needs a manifest declaration.",
  );
  lines.push("");
  lines.push("| Attribute | Purpose | Values | Written by | Scope |");
  lines.push("|---|---|---|---|---|");
  for (const m of TOKEN_MODIFIERS) {
    lines.push(
      `| \`${m.attr}\` | ${m.purpose} | ${m.values.map((v) => `\`${v}\``).join(", ")} | ` +
        `${m.owner} | ${m.scope} |`,
    );
  }
  lines.push("");
  return lines;
}

/**
 * The `[data-density]` remap, derived from `density.css` rather than described:
 * a token added to the compact scope appears here without editing this file.
 */
function renderDensityRemap(css: string, group: TokenGroup, rootGroups: TokenGroup[]): string[] {
  const compact = densityScope(css, "compact");
  const comfortable = new Map(densityScope(css, "comfortable").map((t) => [t.name, t.value]));
  if (compact.length === 0) return [];

  const lines: string[] = [];
  lines.push(`## ${group.group}${group.blurb ? ` — ${group.blurb}` : ""}`);
  lines.push("");
  lines.push(`_\`registry/tokens/${group.file}\` · ${compact.length} tokens re-declared per scope_`);
  lines.push("");

  const origin = new Map<string, string>();
  for (const g of rootGroups) for (const t of g.tokens) if (!origin.has(t.name)) origin.set(t.name, g.group);
  const counts = new Map<string, number>();
  const ownTokens: string[] = [];
  for (const t of compact) {
    const from = origin.get(t.name);
    if (from) counts.set(from, (counts.get(from) ?? 0) + 1);
    else ownTokens.push(t.name);
  }
  lines.push(
    `Remapped by source group: ${[...counts].map(([g, n]) => `\`${g}\` (${n})`).join(", ")}` +
      (ownTokens.length
        ? `, plus ${ownTokens.map((n) => `\`--${n}\``).join(", ")} declared only in these scopes.`
        : "."),
  );
  // Where a group is mostly remapped, the handful it leaves alone is the news:
  // `--space-0` is 0 at any density and a 1px hairline is a hairline. Groups the
  // scope barely touches (or never touches) say nothing here.
  const remapped = new Set(compact.map((t) => t.name));
  for (const g of rootGroups) {
    const untouched = g.tokens.filter((t) => !remapped.has(t.name));
    if (untouched.length === 0 || untouched.length >= g.tokens.length - untouched.length) continue;
    lines.push("");
    lines.push(
      `Invariant in \`${g.group}\`: ${untouched.map((t) => `\`--${t.name}\``).join(", ")} — ` +
        "never scaled, at any density.",
    );
  }
  lines.push("");
  for (const run of bySection(compact)) {
    if (run.section) {
      lines.push(`### ${run.section}`);
      lines.push("");
    }
    lines.push(
      ...renderTokenTable(run.tokens, "`compact`", {
        label: "`comfortable`",
        render: (t) => (comfortable.has(t.name) ? cell(comfortable.get(t.name)!) : "—"),
      }),
    );
    lines.push("");
  }
  return lines;
}

/**
 * Build `references/tokens.md` from `<registryRoot>/tokens/*.css`. Exported so a
 * test can point it at a fixture registry and prove the file is derived rather
 * than transcribed.
 */
export function renderTokensReference(registryRoot: string, schemaVersion: string): string {
  const tokensDir = join(registryRoot, "tokens");
  const groups = loadTokenGroups(tokensDir);
  const rootGroups = groups.filter((g) => g.tokens.length > 0);
  const scopedGroups = groups.filter((g) => g.scoped);

  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir Design Tokens Reference");
  lines.push("");
  lines.push(
    "Every token the registry declares, read out of `registry/tokens/*.css` — the values below ARE " +
      "the declarations. Never hardcode a colour, size, duration or shadow: reference one of these " +
      "tokens through `var()`.",
  );
  lines.push("");
  lines.push(
    `Cascade order, as \`tokens/index.css\` imports them: ${groups.map((g) => `\`${g.file}\``).join(" → ")}. ` +
      "First declaration wins, and each heading below is the `@ui:tokens` group name its file carries — " +
      "palette (raw values) feeds semantic (purpose) feeds aliases (per-component).",
  );
  lines.push("");

  lines.push(...renderTokenModifiers());

  const total = rootGroups.reduce((n, g) => n + g.tokens.length, 0);
  lines.push("## Token Groups");
  lines.push("");
  lines.push(`${total} tokens in ${rootGroups.length} groups:`);
  lines.push("");
  for (const g of rootGroups) {
    lines.push(`- \`${g.group}\` (${g.tokens.length})${g.blurb ? ` — ${g.blurb}` : ""}`);
  }
  lines.push("");

  for (const g of rootGroups) {
    lines.push(`## ${g.group}${g.blurb ? ` — ${g.blurb}` : ""}`);
    lines.push("");
    lines.push(`_\`registry/tokens/${g.file}\` · ${g.tokens.length} tokens_`);
    lines.push("");
    for (const run of bySection(g.tokens)) {
      if (run.section) {
        lines.push(`### ${run.section}`);
        lines.push("");
      }
      lines.push(...renderTokenTable(run.tokens));
      lines.push("");
    }
  }

  for (const g of scopedGroups) {
    lines.push(...renderDensityRemap(readFileSync(join(tokensDir, g.file), "utf8"), g, rootGroups));
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

// ---------------------------------------------------------------------------
// Manifest loading
// ---------------------------------------------------------------------------

/** Load every manifest in the registry, grouped by layer, sorted by name. */
async function loadRegistryManifests(): Promise<Record<Layer, Manifest[]>> {
  const registry = getRegistryPath();
  const out: Record<Layer, Manifest[]> = { primitives: [], recipes: [], patterns: [] };
  for (const layer of LAYERS) {
    const dir = join(registry, layer);
    if (!existsSync(dir)) continue;
    const glob = new Bun.Glob("*/*.manifest.json");
    const paths: string[] = [];
    for (const rel of glob.scanSync({ cwd: dir })) paths.push(join(dir, rel));
    for (const p of paths.sort()) out[layer].push(await loadManifest(p));
  }
  return out;
}

/** Load a project's installed manifests, grouped by layer. */
async function loadInstalledManifests(cwd: string): Promise<Record<Layer, Manifest[]>> {
  const config = await readConfig(cwd);
  const out: Record<Layer, Manifest[]> = { primitives: [], recipes: [], patterns: [] };
  for (const layer of LAYERS) {
    for (const name of config.installed[layer]) {
      const path = join(cwd, config.output_dir, layer, name, `${name}.manifest.json`);
      if (existsSync(path)) out[layer].push(await loadManifest(path));
    }
  }
  return out;
}

function renderPlugins(plugins: PluginMetadata[], corePrefix: string): string[] {
  if (plugins.length === 0) return [];
  const lines: string[] = [];
  lines.push("## Official Plugins");
  lines.push("");
  lines.push("Load a plugin after `faqir-core.js`, or combine core plus every plugin with `faqir bundle --js`:");
  lines.push("");
  for (const plugin of plugins) {
    const summary = plugin.description ? ` — ${plugin.description}` : "";
    lines.push(
      `- \`${plugin.name}\` (${plugin.provides.map((item) => `\`${item}\``).join(", ")}): ` +
        `\`${corePrefix}/plugins/${plugin.file}\`${summary}`,
    );
  }
  lines.push("");
  return lines;
}

// ---------------------------------------------------------------------------
// Project skill: self-contained .faqir/SKILL.md
// ---------------------------------------------------------------------------

/**
 * Generate a project's `.faqir/SKILL.md`, scoped to its installed component set.
 * Self-contained (no external reference files): each installed component gets a
 * full manifest-derived section inline. Carries the generation header.
 */
export async function generateSkill(cwd: string): Promise<string> {
  const byLayer = await loadInstalledManifests(cwd);
  const schemaVersion = await getSchemaVersion();
  const config = await readConfig(cwd);
  const corePrefix = `${config.output_dir.replace(/\/$/, "")}/core`;
  const plugins = loadPluginMetadata(join(cwd, corePrefix, "plugins"));

  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir UI Framework Skill");
  lines.push("");
  lines.push("Zero-class, manifest-driven UI. When building UI, read `.faqir/context.json` first; this skill documents the components this project installs.");
  lines.push("");

  lines.push(...renderAttributeProtocol());
  lines.push(...renderStrictRules());
  lines.push(...renderLayoutSystem());
  lines.push(...renderInventory(byLayer));
  lines.push(...renderPlugins(plugins, corePrefix));

  // Aliases — alternate names installed components answer to, so an agent
  // searching e.g. "alert" discovers it maps to "callout".
  const aliasPairs: string[] = [];
  for (const layer of LAYERS) {
    for (const m of byLayer[layer]) {
      for (const alias of m.aliases ?? []) aliasPairs.push(`- \`${alias}\` → \`${m.name}\``);
    }
  }
  if (aliasPairs.length > 0) {
    lines.push("## Aliases");
    lines.push("");
    lines.push("These names resolve to the component on the right — use `faqir add <alias>` or the canonical `data-ui` value:");
    lines.push("");
    lines.push(...aliasPairs);
    lines.push("");
  }

  // Recipe controllers (interactive components need their JS controller loaded).
  if (byLayer.recipes.length > 0) {
    lines.push("## Recipe Controllers");
    lines.push("");
    lines.push("Interactive components auto-initialize via the core script, or import a controller directly:");
    lines.push("");
    for (const m of byLayer.recipes) {
      lines.push(
        `- \`import { ${factoryName(m.name)} } from "./${config.output_dir}/recipes/${m.name}/${m.name}.js"\``,
      );
    }
    lines.push("");
    lines.push(`Auto-init: \`<script type="module" src="${config.output_dir}/core/faqir.js"></script>\``);
    lines.push("");
  }

  // Per-component sections.
  const sectionTitle: Record<Layer, string> = {
    primitives: "Primitives",
    recipes: "Recipes",
    patterns: "Patterns",
  };
  for (const layer of LAYERS) {
    if (byLayer[layer].length === 0) continue;
    lines.push(`## ${sectionTitle[layer]}`);
    lines.push("");
    for (const m of byLayer[layer]) lines.push(...renderComponentSection(m, 3));
  }

  // Canonical compositions from installed patterns.
  const compositions = renderCompositions(byLayer.patterns);
  if (compositions.length) lines.push(...compositions);

  lines.push(...renderDataDriven());
  lines.push(...renderCliReference());

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/** Write the project's `.faqir/SKILL.md`. */
export async function writeSkillFile(cwd: string): Promise<string> {
  const content = await generateSkill(cwd);
  const faqirDir = join(cwd, ".faqir");
  ensureDir(faqirDir);
  const outPath = join(faqirDir, "SKILL.md");
  await Bun.write(outPath, content);
  return outPath;
}

// ---------------------------------------------------------------------------
// Shipped skill: registry-wide .claude/skills/faqir-creator
// ---------------------------------------------------------------------------

/**
 * The skill's own metadata (frontmatter). This is authored identity, not
 * manifest-derived — Claude Code matches on it to route Faqir tasks here.
 */
const SHIPPED_FRONTMATTER_DESCRIPTION =
  "Expert agent for the Faqir UI framework — generates, audits, repairs, and explains zero-class, manifest-driven UI components and pages. Use when building HTML pages or components with Faqir UI, when the user asks to create/modify/audit Faqir UI markup, when working with data-ui/data-part/data-variant/data-state attributes, when generating page layouts using Faqir tokens and primitives, when creating new registry components (primitives, recipes, patterns), when connecting pages to server data via l-source directive or apiSource(), or when building printable documents (invoices, reports, forms). Triggers on any Faqir UI task including component creation, page scaffolding, code auditing, token usage, reactive directive usage (l-data, l-model, l-for, l-source), data-driven rendering, document/print layout, and CLI operations.";

/** A single generated file destined for the shipped skill directory. */
export interface GeneratedFile {
  /** Path relative to `.claude/skills/faqir-creator/`. */
  relPath: string;
  content: string;
}

const REFERENCE_LABEL: Record<Layer, string> = {
  primitives: "Primitives",
  recipes: "Recipes",
  patterns: "Patterns",
};

/** Build one per-layer reference file (references/<layer>.md). */
function renderReferenceFile(layer: Layer, manifests: Manifest[], schemaVersion: string): string {
  const lines: string[] = [];
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push(`# Faqir ${REFERENCE_LABEL[layer]} Reference`);
  lines.push("");
  lines.push(
    `${manifests.length} ${layer}, each with its anatomy tree, variant table, and safe/unsafe transforms — all derived from the component manifest.`,
  );
  lines.push("");
  for (const m of manifests) lines.push(...renderComponentSection(m, 2));
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/** Build the shipped SKILL.md (frontmatter + framework sections + inventory + compositions). */
function renderShippedSkill(
  byLayer: Record<Layer, Manifest[]>,
  schemaVersion: string,
  plugins: PluginMetadata[],
): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("name: faqir-creator");
  lines.push(`description: ${SHIPPED_FRONTMATTER_DESCRIPTION}`);
  lines.push("---");
  lines.push("");
  lines.push(generationHeader(schemaVersion));
  lines.push("");
  lines.push("# Faqir Creator");
  lines.push("");
  lines.push(
    "Expert agent for the Faqir UI framework. Generate class-free HTML using data attributes, design tokens, and manifest contracts. Every component contract below is generated from its manifest.",
  );
  lines.push("");

  lines.push(...renderAttributeProtocol());
  lines.push(...renderStrictRules());
  lines.push(...renderLayoutSystem());
  lines.push(...renderInventory(byLayer));
  lines.push(...renderPlugins(plugins, "registry/core"));
  lines.push(...renderCompositions(byLayer.patterns));
  lines.push(...renderDataDriven());
  lines.push(...renderCliReference());

  lines.push("## Per-Component Reference");
  lines.push("");
  lines.push("Full anatomy trees, variant tables, and safe/unsafe transforms for every component:");
  lines.push("");
  for (const layer of LAYERS) {
    if (byLayer[layer].length === 0) continue;
    lines.push(
      `- [references/${layer}.md](references/${layer}.md) — ${byLayer[layer].length} ${REFERENCE_LABEL[layer].toLowerCase()}`,
    );
  }
  lines.push("- [references/tokens.md](references/tokens.md) — every design token, derived from `registry/tokens/*.css`");
  lines.push("- [references/directives.md](references/directives.md) — faqir-core reactive directives");
  lines.push("- [references/manifest.md](references/manifest.md) — manifest schema and examples");
  lines.push("");

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/g, "") + "\n";
}

/**
 * Generate every file of the shipped `faqir-creator` skill from the registry:
 * the SKILL.md plus one reference file per layer. Deterministic and idempotent.
 */
export async function generateShippedSkillFiles(): Promise<GeneratedFile[]> {
  const byLayer = await loadRegistryManifests();
  const schemaVersion = await getSchemaVersion();
  const plugins = loadPluginMetadata(join(getRegistryPath(), "core", "plugins"));

  const files: GeneratedFile[] = [
    { relPath: "SKILL.md", content: renderShippedSkill(byLayer, schemaVersion, plugins) },
  ];
  for (const layer of LAYERS) {
    files.push({
      relPath: join("references", `${layer}.md`),
      content: renderReferenceFile(layer, byLayer[layer], schemaVersion),
    });
  }
  // The token reference is derived from registry/tokens/*.css rather than the
  // manifests, so `check:skill` gates it exactly like the per-layer files.
  files.push({
    relPath: join("references", "tokens.md"),
    content: renderTokensReference(getRegistryPath(), schemaVersion),
  });
  return files;
}

/** Absolute path to the shipped skill directory. */
export function shippedSkillDir(): string {
  return join(getPackageRoot(), ".claude", "skills", "faqir-creator");
}

/**
 * Write the shipped skill to `.claude/skills/faqir-creator/`. Returns the
 * absolute paths written. Used by `scripts/gen-skill.mjs`.
 */
export async function writeShippedSkill(): Promise<string[]> {
  const files = await generateShippedSkillFiles();
  const dir = shippedSkillDir();
  const written: string[] = [];
  for (const f of files) {
    const abs = join(dir, f.relPath);
    ensureDir(join(abs, ".."));
    await Bun.write(abs, f.content);
    written.push(abs);
  }
  return written;
}
